package net.anei.cadpage.parsers.NC;


import java.util.regex.Pattern;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchSouthernParser;



public class NCHaywoodCountyParser extends DispatchSouthernParser {
  
  public NCHaywoodCountyParser() {
    super(null, "HAYWOOD COUNTY", "NC", 
                DSFLG_ADDR | DSFLG_ADDR_TRAIL_PLACE2 | DSFLG_X | DSFLG_OPT_CODE | DSFLG_TIME | DSFLG_NO_INFO);
    removeWords("COUNTY", "COVE", "PARK");
    setupCities(CITY_LIST);
    setupMultiWordStreets(MWORD_STREET_LIST);
    setupSaintNames("APTS");
  }

  @Override
  public String getFilter() {
    return "CAD@haywoodnc.net,4702193544";
  }
  
  @Override
  protected boolean parseMsg(String body, Data data) {
    body = stripFieldStart(body, "CAD:");
    if (!super.parseMsg(body, data)) return false;
    int pt = data.strCall.indexOf(' ');
    if (pt >= 0) {
      data.strSupp = data.strCall.substring(pt+1).trim();
      data.strCall = data.strCall.substring(0,pt);
    }
    return true;
  }
  
  @Override
  public String adjustMapAddress(String addr) {
    return STONEY_PK_PTN.matcher(addr).replaceAll("STONEY PARK");
  }
  private static final Pattern STONEY_PK_PTN = Pattern.compile("\\bSTONEY +PK\\b", Pattern.CASE_INSENSITIVE);
  
  @Override
  public String adjustMapCity(String city) {
    if (city.equalsIgnoreCase("NEWPORT")) city = "HAYWOOD COUNTY";
    return city;
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
      "ABBEYS COVE",
      "ABBOTT MOORE",
      "AQUA VISTA",
      "ACRE WOOD",
      "ACRES VIEW",
      "ALBERT RHODES",
      "ALLEN FARM",
      "ALLEN HILL",
      "ALLENS CREEK",
      "AMOS ARRINGTON",
      "AMOS MOUNTAIN",
      "ANDERSON CREEK",
      "APPLE CREEK",
      "ARDEN ACRES",
      "ARRINGTON ACRES",
      "ARROWOOD ACRES",
      "AUBURN PARK",
      "AVERY PATRICK",
      "BALD CREEK",
      "BALSAM LOOKOUT",
      "BALSAM MEADOWS",
      "BALSAM RIDGE",
      "BARBER BLVD RUSS",
      "BARN COVE",
      "BARN LOFT",
      "BARN VIEW",
      "BEAR HUNTER",
      "BEATTY SPRING",
      "BELLE MEADE",
      "BERRY PATCH",
      "BETHEL VIEW",
      "BETSYS GAP",
      "BIG BRANCH",
      "BIG COVE",
      "BIG ROCK",
      "BIRD DOG",
      "BLACK BEAR",
      "BLACK BRANCH",
      "BLACK CAMP GAP",
      "BLAZING STAR",
      "BLUCHER HILL",
      "BLUE RIDGE",
      "BLUE SKY MTN",
      "BLUEBIRD HILL",
      "BOB WHITE",
      "BOTTOM RIDGE",
      "BOYD MOUNTAIN",
      "BRIAR PATCH",
      "BROWN COVE",
      "BRUSHY CREEK",
      "BUCKEYE BRANCH",
      "BUCKEYE COVE",
      "BUILDING SAWMILL",
      "BUNNY RUN",
      "BURNETTE COVE",
      "BURRESS MESSER",
      "BUTLER HILLS",
      "BYERS DEN",
      "C E SMATHERS",
      "CABIN COVE",
      "CABIN CREEK",
      "CABIN FEVER",
      "CALHOUN RIDGE",
      "CALM CREEK",
      "CAMP BRANCH",
      "CAMP HOPE",
      "CAMPBELL CREEK",
      "CANEBRAKE CREEK",
      "CANSADIE TOP",
      "CARING PLACE",
      "CAROLINA CONNECTOR",
      "CAROLINA MTN",
      "CARTER MOUNTAIN",
      "CASS KELL",
      "CASTLE CREEK",
      "CATHEY COVE",
      "CEDAR BEND",
      "CEDAR HILL",
      "CEDAR ROCK",
      "CENTER PIGEON",
      "CHAMBERS FARM",
      "CHAMBERS MTN",
      "CHAMBERS VIEW",
      "CHAPEL VIEW",
      "CHARLES WESLEY",
      "CHARLIE MULL",
      "CHESTNUT FLATS",
      "CHESTNUT HILL",
      "CHESTNUT MOUNTAIN",
      "CHESTNUT PARK",
      "CHIMNEY RIDGE",
      "CITY SPRING",
      "CLARK CEMETERY",
      "CLOUDY HILL",
      "COFFEE BRANCH",
      "COLD CREEK",
      "COLD SPRINGS CREEK",
      "COLEMAN MTN",
      "CONNECTOR 103",
      "CONNECTOR 104",
      "CONNECTOR 106",
      "CONNECTOR 112",
      "CONNECTOR 114",
      "CONNER RIDGE",
      "COUNTRY CLUB",
      "COUNTRY HAVEN",
      "COVE CREEK",
      "COYOTE HOLLOW",
      "COZY CREEK",
      "CRABAPPLE HILL",
      "CRABTREE CHURCH",
      "CRABTREE FARM",
      "CRABTREE MTN",
      "CREDIT UNION",
      "CREEDS COVE",
      "CRIMSON DOWN",
      "CRITTER CREEK",
      "CROSS CREEK",
      "CROSSROAD HILL",
      "CRYMES COVE",
      "CURLY OAKS",
      "DARK COVE",
      "DAVIS COVE",
      "DEE ANN",
      "DEEP WOODS",
      "DEER RUN",
      "DELLWOOD CITY",
      "DENNIS FARM",
      "DIX CREEK",
      "DOC GRAHAM",
      "DOCK RATCLIFFE",
      "DOUBLE SIDES",
      "DOWNS COVE",
      "DREAM MOUNTAIN",
      "DRY BRANCH",
      "DRY SPRING",
      "DUCKETT COVE",
      "DUTCH COVE",
      "EAGLES NEST",
      "EARL BRADLEY",
      "EAST N MAIN",
      "EASTERN SKY",
      "ED GREEN",
      "EDEN BROOK",
      "EDWIN CALDWELL",
      "ELBERT BURNETT",
      "ELIZABETH CHAPEL",
      "ELM TREE",
      "ENGLISH OAKS",
      "ERNEST CARVER",
      "ERNEST ROGERS",
      "EVANS COVE",
      "EVERGREEN FALLS",
      "FALL CREEK",
      "FALLING SPRING",
      "FANNIE MAE",
      "FERGUSON CONNECTOR",
      "FIE TOP",
      "FILTER PLANT",
      "FINES CREEK",
      "FISH POND",
      "FLAT ROCK",
      "FLAT TOP",
      "FLOWING HILLS",
      "FORD HOLLOW",
      "FOREST SERVICE",
      "FORK RANCH",
      "FOX RUN",
      "FRAGRANT PINE",
      "FRANCIS ASBURY",
      "FRANCIS ORCHARD",
      "FRANK DAVIS",
      "FRANK MEHAFFEY",
      "FRIENDLY ACRES",
      "FROG POND",
      "GADDIS BRANCH",
      "GALE WIND",
      "GEORGE ROGERS",
      "GEORGE SUTTON",
      "GIBSON BRANCH",
      "GIHON WATERS",
      "GINSENG HOLLOW",
      "GLADE MOUNTAIN",
      "GLEN MEADOW",
      "GOLD FINCH",
      "GOLDEN WILLOW",
      "GOLF COURSE",
      "GRANNYS COVE",
      "GRASSY BALD",
      "GREAT OAK",
      "GREEN PASTURE",
      "GREEN VALLEY",
      "GROUNDHOG HILL",
      "GROVERS MTN",
      "HALL TOP",
      "HAPPY ACRES",
      "HARLEY CREEK",
      "HARLEY DAVIDSON",
      "HARRY ROGERS",
      "HAVEN HILL",
      "HAWK HAVEN",
      "HAWKS CREST",
      "HAYNES HILL",
      "HAYSTACK HILL",
      "HAYWOOD OFFICE",
      "HEATH PEAK",
      "HEMLOCK HILL",
      "HEMLOCK SPRING",
      "HEMLOCK SPRINGS",
      "HENRY HOLLOW",
      "HENSON COVE",
      "HI LANE",
      "HICKORY HILL",
      "HICKORY NUT",
      "HIDDEN COVE",
      "HIDDEN VALLEY",
      "HIGH ACRES",
      "HIGH COUNTRY",
      "HIGH HOPES",
      "HIGH RIDGE",
      "HIGH WINDY",
      "HILL N DALE",
      "HILL TOP",
      "HILL VIEW",
      "HILLTOP FARM",
      "HOBBLE HILL",
      "HOLSTON VILLAGE",
      "HOME PLACE",
      "HOOT HILL",
      "HORSE COVE",
      "HORSECART PATH",
      "HOWARD VALLEY",
      "HOWELL COVE",
      "HOWELL MILL",
      "HUB PATCH",
      "HUNGRY CREEK",
      "HUNTERS RIDGE",
      "HURRICANE CREEK",
      "HURRICANE RIDGE",
      "HY VU",
      "HYATT CREEK",
      "HYDER MOUNTAIN",
      "INDIAN SPRINGS",
      "INDIAN TRACE",
      "INDUSTRIAL PARK",
      "INTERSTATE 40",
      "IRON DUFF",
      "IVY BRANCH",
      "IVY HILL",
      "J D FOX",
      "J F MORRIS",
      "J FARM",
      "J R SAYLES",
      "JACK PINE",
      "JACKSON POND",
      "JAMES HILL",
      "JAYNES COVE",
      "JENNY GAP",
      "JESS COVE",
      "JIMS COVE",
      "JODY COVE",
      "JOE BROWN",
      "JOE CARVER",
      "JOE PRESSLEY",
      "JOHN PAUL",
      "JOHN ROCK",
      "JOHN WAYNE",
      "JOHNS CREEK",
      "JOHNSON BRANCH",
      "JOHNSON FARM",
      "JONATHAN CREEK CONNECTOR",
      "JONATHAN CREEK",
      "JONES COVE",
      "JULE NOLAND",
      "JUMPING BRANCH",
      "JUNALUSKA OAKS",
      "KELLY SPRINGS",
      "KETNER COVE",
      "KIMS COVE",
      "KING COVE",
      "LAB MOUNTAIN",
      "LADY BYRD",
      "LADY HUNTINGDON",
      "LAKE LOGAN",
      "LAST COYOTE",
      "LAUREL BRANCH",
      "LAUREL BROOK",
      "LAUREL RIDGE",
      "LEA PLANT",
      "LEATHERWOOD COVE",
      "LEE GRANT",
      "LEROY GEORGE",
      "LINDA MORGAN",
      "LIBERTY CHURCH",
      "LINER COVE",
      "LINER CREEK",
      "LIONS DEN",
      "LITTLE COVE",
      "LITTLE CREEK",
      "LITTLE EAST FORK",
      "LITTLE MOUNTAIN",
      "LITTLE OAK",
      "LIVESTOCK MARKET",
      "LOCUST GROVE",
      "LOG CABIN",
      "LOGANS LEAP",
      "LONESOME PINE",
      "LONESOME PINES",
      "LONG BRANCH",
      "LORI HILL",
      "LOST COVE",
      "LOVE CARRIAGE",
      "LOVE JOY",
      "LOW GAP",
      "LUM BOONE",
      "LYNNE BIRCH",
      "MAGNOLIA BLUFF",
      "MAIN ST NORMAN",
      "MAPLE GROVE CH",
      "MAPLE KNOLL",
      "MAPLE SPRINGS",
      "MARSHALL HILL",
      "MARTINS CREEK",
      "MARY GALE",
      "MARY GRAY",
      "MASON HILL",
      "MATTIE MARION",
      "MAUNEY COVE",
      "MAX PATCH",
      "MAYAPPLE MOUNTAIN",
      "MCELROY COVE",
      "MCKAY FARM",
      "MEADOWS GROVE CHURCH",
      "MEADOW VIEW",
      "MENDEN HALL",
      "MERIDA GAP",
      "METCALF MOUNTAIN",
      "MICA MINE",
      "MILL CREEK",
      "MILL WHISTLE",
      "MILLER LOOP",
      "MINGUS COVE",
      "MINGUS HILL",
      "MISTY VIEW",
      "MONTE VISTA",
      "MOODY FARM",
      "MORNING DEW",
      "MORNING GLORY",
      "MORNING STAR",
      "MOUNT STERLING",
      "MOUNT VALLEY",
      "MOUNTAIN LAKE",
      "MOUNTAIN VIEW",
      "MOUNTAIN VISTA",
      "MTN MISSION",
      "MUCKLE COVE",
      "MULE STOMP",
      "MUNDY FIELD",
      "MUSTANG ALLEY",
      "NARROW GAUGE",
      "NATIVE TROUT",
      "NATURAL SPRING",
      "NED COVE",
      "NELLIE JOHN",
      "NELLS HOLLOW",
      "NIX CREEK",
      "NOLAND DOWNS",
      "NOLAND GAP",
      "OAK PARK",
      "OAK RIDGE",
      "OAK TREE",
      "ORION DAVIS",
      "OSBORNE FARM",
      "OSBORNE RIDGE",
      "OWL HOLLER",
      "OWL RIDGE",
      "OXNER COVE",
      "PANTHER CREEK",
      "PARADISE MTN",
      "PARK TERRACE",
      "PATCHEN ESTATE",
      "PATCHENS ESTATE",
      "PEBBLE BROOK",
      "PETERS COVE",
      "PHOENIX GLEN",
      "PIGEON GAP",
      "PIGEON VALLEY",
      "PINEY GROVE",
      "PINEY MOUNTAIN",
      "PINEY RIDGE",
      "PINK LAUREL",
      "PISGAH CREEK",
      "PISGAH MOUNTAIN",
      "PLACID KNOLL",
      "PLEASANT HILL",
      "PLOTT CREEK",
      "PLOTT FARM",
      "PLOTT MOUNTAIN",
      "PLOTT VALLEY",
      "POINT OF VIEW",
      "POISON COVE",
      "POISON IVY",
      "POLYANNA CREEK",
      "POPLAR BRANCH",
      "POSSUM RIDGE",
      "POT LEG",
      "PRECIOUS METAL",
      "PRICE TOWN",
      "PUMP HOUSE",
      "PUTNAM PHILLIPS",
      "QUAIL MOUNTAIN",
      "QUEEN COVE",
      "RABBIT SHADOW",
      "RABBIT SKIN",
      "RACKING HORSE",
      "RADIO HILL",
      "RAIL FENCE",
      "RAINY BRANCH",
      "RAMBLING RIDGE",
      "RANGER STATION",
      "RATCLIFF COVE",
      "RATTLESNAKE BRANCH",
      "RAVEN ROCK",
      "RAY BEST",
      "RAY MEMORIAL GARDENS HALE",
      "RED BANK",
      "RED FOX",
      "RED MAPLE",
      "RED OAK",
      "REED COVE",
      "REED CREEK",
      "RENO FARM",
      "REUBEN BRANCH",
      "REYNOLDS SCHOOL",
      "RICE COVE",
      "RICH COVE",
      "RICHLAND CREEK",
      "RIDDLE COVE",
      "RIDING HORSE",
      "RIVER POINT",
      "RIVERVIEW HILLS",
      "ROBERTS SHOP",
      "ROBIN ROOST",
      "ROBINS NEST",
      "ROCK HOUSE COVE",
      "ROCKY BRANCH",
      "ROCKY HOLLOW",
      "ROCKY LANE",
      "ROCKY TOP",
      "ROGERS COVE",
      "ROGERS HILL",
      "ROLLING ACRES",
      "ROLLING HILLS",
      "ROME BEAUTY",
      "ROSE GARDEN",
      "ROSE HILL",
      "ROTH STREAM",
      "ROUND ROCK",
      "RUBY BEN",
      "RUFFED GROUSE",
      "RUMBLING GAP",
      "RUSH FORK",
      "RUSHING CREEK",
      "RUSTIC HEIGHTS",
      "RUSTIC RIDGE",
      "RYAN RIDGE",
      "SANDY BOTTOMS",
      "SARA RIDGE",
      "SCENIC VIEW",
      "SCHOOLHOUSE GAP",
      "SENG BRANCH",
      "SERENITY MTN",
      "SHADOW OAK",
      "SHADY BROOK",
      "SHALLOW CREEK",
      "SHANDY DUSTY",
      "SHARP MOUNTAIN",
      "SHELTON COVE",
      "SHORT RIDGE",
      "SILENT ACRES",
      "SILO RIDGE",
      "SILVER BLUFF",
      "SILVERS COVE",
      "SKI LODGE",
      "SLEEPY HOLLOW",
      "SLOW PACE",
      "SMATHERS COVE",
      "SMITH FARM",
      "SMOKEY COVE",
      "SMOKEY MEADOWS",
      "SMOKEY PARK",
      "SMOKY FALLS",
      "SNEAKING CREEK",
      "SNOW FLAKE",
      "SNOW WHITE",
      "SOCO ACRES",
      "SOLITARY MEADOW",
      "SORRELLS COVE",
      "SORRELLS CREEK",
      "SPY ROCK",
      "SQUAW RIDGE",
      "SQUIRREL HILL",
      "SUNNY ACRES",
      "STALL BRANCH",
      "STAMEY COVE",
      "STEVENS CREEK",
      "STEVENSON COVE",
      "STILL POND",
      "STILLHOUSE COVE",
      "STONE HAVEN",
      "STONEY BROOK",
      "SUGAR COVE",
      "SUGAR GROVE",
      "SUGAR MOUNTAIN",
      "SUGAR PLUM",
      "SULPHUR SPRINGS",
      "SUMMER PLACE",
      "SUNSET RIDGE",
      "SUSIE NOLAND",
      "SUTTON TOWN",
      "SWISS VALLEY",
      "TALL PINES",
      "TALL TIMBER",
      "TATER HILL FARM",
      "TAYLOR SPRINGS",
      "TERRELL COVE",
      "TEST FARM",
      "THE HARD",
      "THE HAWKS NEST",
      "THE HIGH",
      "THOMPSON COVE",
      "THORNY KNOLL",
      "THUNDER RIDGE",
      "TIGER LILY",
      "TIGER MOUNTAIN",
      "TIMBER RIDGE",
      "TIMBERLANE CONNECTOR",
      "TINKER BELL",
      "TIPP FIELD",
      "TOBACCO BARN",
      "TOUCH THE STARS",
      "TOWN CENTER",
      "TRAILS END",
      "TRI LAKES",
      "TRI LAKES",
      "TRICKLE CREEK",
      "TRIPLE CREEK",
      "TROUT POND",
      "TUG FORK",
      "TUG HILL",
      "TUMBLING FORK",
      "TURKEY CREEK",
      "TURNER BRANCH",
      "TUSCOLA SCHOOL",
      "TWIN BROOK",
      "TWIN MAPLES",
      "TWIN OAKS",
      "UNDERWOOD COVE",
      "UP OVER",
      "UTAH MOUNTAIN",
      "VALLEY BROOK",
      "VALLEY HILL",
      "VALLEY VIEW CIR",
      "VALLEY VILLAS",
      "VAN ARRINGTON",
      "WADY BRANCH",
      "WAGON WHEEL",
      "WAITSEL CONNECTOR",
      "WALMART PLAZA",
      "WALNUT CREEK",
      "WALNUT FORD",
      "WALNUT RIDGE",
      "WALNUT TRAIL",
      "WALTER C",
      "WARREN COVE",
      "WEEPING CHERRY",
      "WELCH MESSER",
      "WELLS EVENTS",
      "WESLEY CREEK",
      "WHEELER HILL",
      "WHISTLING OAK",
      "WHITE OAK",
      "WHY WORRY",
      "WILD ROCK",
      "WILD ROSE",
      "WILDCHERRY HILL",
      "WILKINSON PASS",
      "WILL BAILEY",
      "WILL HYATT",
      "WILLIAMS MOUNTAIN",
      "WILLIE BILLS",
      "WILLIS COVE",
      "WILLIS HILL",
      "WILLOW TREE",
      "WILLS COVE",
      "WILSON COVE",
      "WINCHESTER CREEK",
      "WIND SPIRIT",
      "WINDING CREEK",
      "WINDSWEPT RIDGE",
      "WINDY HILL",
      "WOLF RIDGE",
      "WOODLAND CHURCH",
      "WORLEY COVE",
      "WOUNDED KNEE",
      "YATES COVE",
      "YELLOW PATCH",
      "YONDER MOUNTAIN",
      "ZEMRY CALDWELL",
      "ZEPHIE SPRINGS"
  };
  
  private static String[] CITY_LIST = new String[]{
    "CANTON",
    "CLYDE",
    "LAKE JUNALUSKA",
    "MAGGIE VALLEY",
    "NEWPORT",
    "WAYNESVILLE",
    "WEST CANTON",
    
    "BUNCOMBE",
    "BALSAM",
    "CANDLER",
    "ENKA",
    "LEICESTER"
  };
  
}