package net.anei.cadpage.parsers.NC;


import java.util.regex.Pattern;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchSouthernParser;



public class NCHaywoodCountyParser extends DispatchSouthernParser {

  public NCHaywoodCountyParser() {
    super(null, "HAYWOOD COUNTY", "NC",
                DSFLG_ADDR | DSFLG_ADDR_TRAIL_PLACE2 | DSFLG_OPT_X | DSFLG_OPT_CODE | DSFLG_TIME | DSFLG_NO_INFO);
    removeWords("COUNTY", "COVE", "PARK");
    setupCities(CITY_LIST);
    setupMultiWordStreets(MWORD_STREET_LIST);
    setupSaintNames("APTS");
  }

  @Override
  public String getFilter() {
    return "CAD@haywoodnc.net,4702193544";
  }

  @Override
  public int getMapFlags() {
    return MAP_FLG_PREFER_GPS;
  }

  @Override
  protected boolean parseMsg(String body, Data data) {
    body = stripFieldStart(body, "CAD:");
    if (!super.parseMsg(body, data)) return false;
    int pt = data.strCall.indexOf(' ');
    if (pt >= 0) {
      data.strSupp = data.strCall.substring(pt+1).trim();
      data.strCall = data.strCall.substring(0,pt);
    }
    return true;
  }

  @Override
  public String adjustMapAddress(String addr) {
    return STONEY_PK_PTN.matcher(addr).replaceAll("STONEY PARK");
  }
  private static final Pattern STONEY_PK_PTN = Pattern.compile("\\bSTONEY +PK\\b", Pattern.CASE_INSENSITIVE);

  @Override
  public String adjustMapCity(String city) {
    if (city.equalsIgnoreCase("NEWPORT")) city = "HAYWOOD COUNTY";
    return city;
  }

  private static final String[] MWORD_STREET_LIST = new String[]{
      "ABBEYS COVE",
      "ABBOTT MOORE",
      "ACRE WOOD",
      "ACRES VIEW",
      "ALBERT RHODES",
      "ALLEN FARM",
      "ALLEN HILL",
      "ALLENS CREEK",
      "AMOS ARRINGTON",
      "AMOS MOUNTAIN",
      "ANDERSON CREEK",
      "ANTLER SPRINGS",
      "APPLE BLOSSOM",
      "APPLE CREEK",
      "AQUA VISTA",
      "ARDEN ACRES",
      "ARRINGTON ACRES",
      "ARROWOOD ACRES",
      "AUBURN PARK",
      "AUTUMN RIDGE",
      "AVERY PATRICK",
      "BALD CREEK",
      "BALSAM LOOKOUT",
      "BALSAM MEADOWS",
      "BALSAM RIDGE",
      "BALSAM SHADOWS",
      "BARBER BLVD RUSS",
      "BARBER HILL",
      "BARN COVE",
      "BARN LOFT",
      "BARN VIEW",
      "BEAR HUNTER",
      "BEATTY SPRING",
      "BELLE MEADE",
      "BELMONT CHURCH",
      "BEN MEDFORD",
      "BERRY PATCH",
      "BEST VIEW",
      "BETHEL VIEW",
      "BETSYS GAP",
      "BIG BRANCH",
      "BIG COVE",
      "BIG ROCK",
      "BILL MCELROY",
      "BIRD CREEK",
      "BIRD DOG",
      "BLACK BEAR",
      "BLACK BETTY MTN",
      "BLACK BRANCH",
      "BLACK CAMP GAP",
      "BLACK HAWK",
      "BLAZING STAR",
      "BLINK BONNY",
      "BLUCHER HILL",
      "BLUE RIDGE",
      "BLUE SKY MTN",
      "BLUEBIRD HILL",
      "BOB BOYD",
      "BOB EVANS",
      "BOB WHITE",
      "BOBBY JONES",
      "BOTTOM RIDGE",
      "BOW N ARROW",
      "BOYD MOUNTAIN",
      "BRIAR PATCH",
      "BROKEN BOW",
      "BROKEN WHEEL",
      "BROWN COVE",
      "BROWNING BRANCH",
      "BRUSHY CREEK",
      "BUCKEYE BRANCH",
      "BUCKEYE COVE",
      "BUCKSKIN BRANCH",
      "BUENA VISTA",
      "BUG HOLLOW",
      "BUILDING JONES COVE",
      "BUILDING SAWMILL",
      "BUNNY RUN",
      "BURNETTE COVE",
      "BURRESS MESSER",
      "BUTLER HILLS",
      "BYERS DEN",
      "C E SMATHERS",
      "C J JUSTICE",
      "CABIN COVE",
      "CABIN CREEK",
      "CABIN FEVER",
      "CALHOUN RIDGE",
      "CALM CREEK",
      "CAMP ADVENTURE",
      "CAMP BRANCH",
      "CAMP HOPE",
      "CAMPBELL CREEK",
      "CANEBRAKE CREEK",
      "CANSADIE TOP",
      "CARING PLACE",
      "CAROLINA CONNECTOR",
      "CAROLINA MTN",
      "CARTER MOUNTAIN",
      "CASS KELL",
      "CASTLE CREEK",
      "CATHEY COVE",
      "CEDAR BEND",
      "CEDAR HILL",
      "CEDAR ROCK",
      "CENTER PIGEON",
      "CHAMBERS FARM",
      "CHAMBERS MTN",
      "CHAMBERS VIEW",
      "CHAMPION DRIVE N CANTON",
      "CHAPEL VIEW",
      "CHARLES WESLEY",
      "CHARLIE MULL",
      "CHESTNUT FLATS",
      "CHESTNUT HILL",
      "CHESTNUT MOUNTAIN",
      "CHESTNUT PARK",
      "CHIMNEY RIDGE",
      "CHINQUAPIN HILL",
      "CHIPPING SPARROW",
      "CHURCH VIEW",
      "CITY SPRING",
      "CLARK CEMETERY",
      "CLOUDY HILL",
      "COFFEE BRANCH",
      "COLD CREEK",
      "COLD MTN VIEW",
      "COLD SPRINGS CREEK",
      "COLDWATER CREEK",
      "COLEMAN MTN",
      "CONNECTOR 103",
      "CONNECTOR 104",
      "CONNECTOR 106",
      "CONNECTOR 112",
      "CONNECTOR 114",
      "CONNER RIDGE",
      "COPPER SPUR",
      "COUNTRY CLUB",
      "COUNTRY HAVEN",
      "COUNTY HOME",
      "COVE CREEK",
      "COYOTE HOLLOW",
      "COZY CREEK",
      "CRABAPPLE HILL",
      "CRABTREE CHURCH",
      "CRABTREE FARM",
      "CRABTREE MTN",
      "CREDIT UNION",
      "CREEDS COVE",
      "CRIMSON DOWN",
      "CRITTER CREEK",
      "CROOKED BRANCH",
      "CROSS CREEK",
      "CROSSROAD HILL",
      "CROWBAR HILL",
      "CRYMES COVE",
      "CUR DOG",
      "CURLY OAKS",
      "DARK COVE",
      "DAVIS COVE",
      "DEE ANN",
      "DEEP WOODS",
      "DEER RUN",
      "DELLWOOD CITY",
      "DENNIS FARM",
      "DEWEY ROSS",
      "DIX CREEK",
      "DOC GRAHAM",
      "DOCK RATCLIFFE",
      "DOGWOOD KNOLL",
      "DOUBLE SIDES",
      "DOUBLE TOP",
      "DOWNS COVE",
      "DREAM MOUNTAIN",
      "DRY BRANCH",
      "DRY SPRING",
      "DUCKETT COVE",
      "DUTCH COVE",
      "EAGLES NEST",
      "EARL BRADLEY",
      "EAST N MAIN",
      "EASTERN SKY",
      "ED GREEN",
      "EDEN BROOK",
      "EDWIN CALDWELL",
      "ELBERT BURNETT",
      "ELIZABETH CHAPEL",
      "ELM TREE",
      "EMERALD MTN",
      "ENGLISH OAKS",
      "ERNEST CARVER",
      "ERNEST ROGERS",
      "EVANS COVE",
      "EVERGREEN FALLS",
      "EVERGREEN FARM",
      "FALL CREEK",
      "FALLING SPRING",
      "FANNIE MAE",
      "FERGUSON CONNECTOR",
      "FIE TOP",
      "FILTER PLANT",
      "FINES CREEK",
      "FISH POND",
      "FLAT CREEK",
      "FLAT HILLS",
      "FLAT ROCK",
      "FLAT TOP",
      "FLOWING HILLS",
      "FORD HOLLOW",
      "FOREST SERVICE",
      "FORK RANCH",
      "FOX RUN",
      "FOXFIRE ESTATES",
      "FRAGRANT PINE",
      "FRANCIS ASBURY",
      "FRANCIS FARM",
      "FRANCIS ORCHARD",
      "FRANK DAVIS",
      "FRANK MEHAFFEY",
      "FRIENDLY ACRES",
      "FRIENDLY HOUSE",
      "FROG POND",
      "GADDIS BRANCH",
      "GALE WIND",
      "GARDENING FROG",
      "GEORGE ROGERS",
      "GEORGE SUTTON",
      "GERMANY COVE",
      "GIBSON BRANCH",
      "GIHON WATERS",
      "GINSENG HOLLOW",
      "GLADE MOUNTAIN",
      "GLEN MEADOW",
      "GOBBLERS KNOB",
      "GODS COUNTRY",
      "GOLD FINCH",
      "GOLDEN WILLOW",
      "GOLF COURSE",
      "GRACE RIDGE",
      "GRANNYS COVE",
      "GRASSY BALD",
      "GREAT OAK",
      "GREAT SMOKY MTN",
      "GREEN PASTURE",
      "GREEN VALLEY",
      "GROUNDHOG HILL",
      "GROVERS MTN",
      "HALL TOP",
      "HAPPY ACRES",
      "HARLEY CREEK",
      "HARLEY DAVIDSON",
      "HARRIS RIDGE",
      "HARRY ROGERS",
      "HAVEN HILL",
      "HAWK HAVEN",
      "HAWK HILL",
      "HAWKS CREST",
      "HAYNES HILL",
      "HAYSTACK HILL",
      "HAYWOOD OFFICE",
      "HEATH PEAK",
      "HEAVENLY MTN",
      "HEMLOCK HILL",
      "HEMLOCK SPRING",
      "HEMLOCK SPRINGS",
      "HENRY DINGUS",
      "HENRY HOLLOW",
      "HENSON COVE",
      "HI LANE",
      "HICKORY HILL",
      "HICKORY NUT",
      "HIDDEN COVE",
      "HIDDEN VALLEY",
      "HIGH ACRES",
      "HIGH COUNTRY",
      "HIGH HOPES",
      "HIGH RIDGE",
      "HIGH WINDY",
      "HIGHLAND RIDGE",
      "HILL N DALE",
      "HILL TOP",
      "HILL VIEW",
      "HILLTOP FARM",
      "HOBBLE HILL",
      "HOG HEAVEN",
      "HOLDER BRANCH",
      "HOLLY HILL",
      "HOLSTON VILLAGE",
      "HOME PLACE",
      "HOOT HILL",
      "HOOT OWL BILL",
      "HOOT OWL HOLLOW",
      "HORSE COVE",
      "HORSECART PATH",
      "HOWARD VALLEY",
      "HOWARDS HOLLOW",
      "HOWELL COVE",
      "HOWELL MILL",
      "HUB PATCH",
      "HUNGRY CREEK",
      "HUNT ESTATES",
      "HUNTERS RIDGE",
      "HURRICANE CREEK",
      "HURRICANE RIDGE",
      "HY VU",
      "HYATT CREEK",
      "HYDER MOUNTAIN",
      "INDIAN CREEK",
      "INDIAN SPRINGS",
      "INDIAN TRACE",
      "INDUSTRIAL PARK",
      "INMAN BRANCH",
      "INTERSTATE 40",
      "INTERSTATE HOLDER BRANCH",
      "IRON DUFF",
      "ISLER BRANCH",
      "IVY BRANCH",
      "IVY HILL",
      "J B IVEY",
      "J D FOX",
      "J F MORRIS",
      "J FARM",
      "J R SAYLES",
      "JACK PINE",
      "JACKSON POND",
      "JAMES CHAPEL",
      "JAMES HILL",
      "JAYNES COVE",
      "JENNY GAP",
      "JESS COVE",
      "JIMS COVE",
      "JODY COVE",
      "JOE BROWN",
      "JOE CARVER",
      "JOE PRESSLEY",
      "JOHN PAUL",
      "JOHN ROCK",
      "JOHN WAYNE",
      "JOHNS CREEK",
      "JOHNSON BRANCH",
      "JOHNSON FARM",
      "JONATHAN CREEK CONNECTOR",
      "JONATHAN CREEK",
      "JONES COVE",
      "JULE NOLAND",
      "JUMPING BRANCH",
      "JUNALUSKA OAKS",
      "KELLY SPRINGS",
      "KETNER COVE",
      "KIMS COVE",
      "KING COVE",
      "LAB MOUNTAIN",
      "LADY BYRD",
      "LADY HUNTINGDON",
      "LAKE LOGAN",
      "LAST COYOTE",
      "LAUREL BRANCH",
      "LAUREL BROOK",
      "LAUREL RIDGE",
      "LEA PLANT",
      "LEATHERWOOD COVE",
      "LEE GRANT",
      "LEES CREEK",
      "LEROY GEORGE",
      "LIBERTY CHURCH",
      "LILY PAD",
      "LINDA MORGAN",
      "LINER COVE",
      "LINER CREEK",
      "LIONS DEN",
      "LITTLE ACRES",
      "LITTLE COVE",
      "LITTLE CREEK",
      "LITTLE EAST FORK",
      "LITTLE MOUNTAIN",
      "LITTLE OAK",
      "LIVESTOCK MARKET",
      "LIVING WATERS",
      "LOCUST GROVE",
      "LOG CABIN",
      "LOGANS LEAP",
      "LONESOME HOLLOW",
      "LONESOME PINE",
      "LONESOME PINES",
      "LONG BRANCH",
      "LORI HILL",
      "LOST COVE",
      "LOVE CARRIAGE",
      "LOVE JOY",
      "LOW GAP",
      "LUM BOONE",
      "LYNNE BIRCH",
      "MACS BARNYARD",
      "MAGNOLIA BLUFF",
      "MAIN ST NORMAN",
      "MAPLE GROVE CH",
      "MAPLE KNOLL",
      "MAPLE LEAF",
      "MAPLE SPRINGS",
      "MARION S HIPPS",
      "MARSHALL HILL",
      "MARTINS CREEK",
      "MARY GALE",
      "MARY GRAY",
      "MARY JOHN",
      "MARY LEE",
      "MASON HILL",
      "MATTIE MARION",
      "MAUNEY COVE",
      "MAX PATCH",
      "MAX THOMPSON",
      "MAYAPPLE MOUNTAIN",
      "MCCLURE CREEK",
      "MCELROY COVE",
      "MCKAY FARM",
      "MEADOW VIEW",
      "MEADOWS GROVE CHURCH",
      "MEDFORD HANNAH",
      "MENDEN HALL",
      "MERIDA GAP",
      "METCALF MOUNTAIN",
      "MICA MINE",
      "MIJOS BACKYARD",
      "MILE HIGH",
      "MILL CREEK",
      "MILL WHISTLE",
      "MILLER LOOP",
      "MINGUS COVE",
      "MINGUS HILL",
      "MISTY MOUNTAIN",
      "MISTY VIEW",
      "MONTE VISTA",
      "MOODY FARM",
      "MORNING DEW",
      "MORNING GLORY",
      "MORNING STAR",
      "MOUNT STERLING",
      "MOUNT VALLEY",
      "MOUNTAIN COVE",
      "MOUNTAIN LAKE",
      "MOUNTAIN VIEW",
      "MOUNTAIN VISTA",
      "MTN MISSION",
      "MUCKLE COVE",
      "MULE STOMP",
      "MUNDY FIELD",
      "MUSTANG ALLEY",
      "NARROW GAUGE",
      "NATIVE TROUT",
      "NATURAL SPRING",
      "NED COVE",
      "NELLIE JOHN",
      "NELLS HOLLOW",
      "NIX CREEK",
      "NOLAND DOWNS",
      "NOLAND GAP",
      "OAK PARK",
      "OAK RIDGE",
      "OAK TREE",
      "ORCHARD COVE",
      "ORION DAVIS",
      "OSBORNE FARM",
      "OSBORNE RIDGE",
      "OUR SONNY",
      "OWL HOLLER",
      "OWL RIDGE",
      "OXNER COVE",
      "PANTHER CREEK",
      "PARADISE MTN",
      "PARK TERRACE",
      "PATCHEN ESTATE",
      "PATCHENS ESTATE",
      "PEBBLE BROOK",
      "PETERS COVE",
      "PHEASANT RUN",
      "PHOENIX GLEN",
      "PIGEON FORD",
      "PIGEON GAP",
      "PIGEON VALLEY",
      "PIGPEN COVE",
      "PINEY GROVE",
      "PINEY MOUNTAIN",
      "PINEY RIDGE",
      "PINK LAUREL",
      "PISGAH CREEK",
      "PISGAH MOUNTAIN",
      "PISGAH SCHOOL",
      "PLACID KNOLL",
      "PLEASANT HILL",
      "PLOTT CREEK",
      "PLOTT FARM",
      "PLOTT MOUNTAIN",
      "PLOTT VALLEY",
      "POINT OF VIEW",
      "POISON COVE",
      "POISON IVY",
      "POLYANNA CREEK",
      "POPLAR BRANCH",
      "POPLAR COVE",
      "POPLAR LOOP",
      "POSSUM RIDGE",
      "POT LEG",
      "PRECIOUS METAL",
      "PRICE TOWN",
      "PUMP HOUSE",
      "PUTNAM PHILLIPS",
      "QUAIL MOUNTAIN",
      "QUEEN COVE",
      "RABBIT SHADOW",
      "RABBIT SKIN",
      "RACKING HORSE",
      "RADIO HILL",
      "RAIL FENCE",
      "RAINY BRANCH",
      "RAMBLING RIDGE",
      "RANGER STATION",
      "RATCLIFF COVE",
      "RATTLESNAKE BRANCH",
      "RAVEN ROCK",
      "RAY BEST",
      "RAY MEMORIAL GARDENS HALE",
      "RAYS HILL",
      "REBEL RIDGE",
      "RED BANK",
      "RED FOX",
      "RED MAPLE",
      "RED OAK",
      "REED COVE",
      "REED CREEK",
      "REEVES COVE",
      "RENO FARM",
      "REUBEN BRANCH",
      "REYNOLDS SCHOOL",
      "RICE COVE",
      "RICH COVE",
      "RICH PUTNAM",
      "RICHLAND CREEK",
      "RIDDLE COVE",
      "RIDING HIGH",
      "RIDING HORSE",
      "RILEY TRULL",
      "RIVER POINT",
      "RIVERVIEW HILLS",
      "ROBERTS SHOP",
      "ROBIN ROOST",
      "ROBINS NEST",
      "ROCK HOUSE COVE",
      "ROCKY BRANCH",
      "ROCKY HOLLOW",
      "ROCKY LANE",
      "ROCKY SPRINGS",
      "ROCKY TOP",
      "ROGERS COVE",
      "ROGERS HILL",
      "ROLLING ACRES",
      "ROLLING HILLS",
      "ROME BEAUTY",
      "ROSE GARDEN",
      "ROSE HILL",
      "ROTH STREAM",
      "ROUND ROCK",
      "RUBY BEN",
      "RUFFED GROUSE",
      "RULES RUN",
      "RUMBLING GAP",
      "RUSH FORK",
      "RUSHING CREEK",
      "RUSSELL MTN",
      "RUSTIC HEIGHTS",
      "RUSTIC RIDGE",
      "RYAN RIDGE",
      "SALLYS BRANCH",
      "SANDY BOTTOMS",
      "SANDY SHOALS",
      "SARA RIDGE",
      "SAW BRANCH",
      "SCENIC VIEW",
      "SCHOOLHOUSE GAP",
      "SCREECH OWL",
      "SENG BRANCH",
      "SERENITY MTN",
      "SETZER COVE",
      "SHADOW OAK",
      "SHADY BROOK",
      "SHALLOW CREEK",
      "SHANDY DUSTY",
      "SHARP MOUNTAIN",
      "SHEEPBACK MTN",
      "SHELTON COVE",
      "SHELTON LAUREL",
      "SHOOTING STAR",
      "SHORT RIDGE",
      "SILENT ACRES",
      "SILO RIDGE",
      "SILVER BLUFF",
      "SILVERS COVE",
      "SKI LODGE",
      "SLEEPY HOLLOW",
      "SLOW PACE",
      "SMATHERS COVE",
      "SMITH FARM",
      "SMOKEY COVE",
      "SMOKEY MEADOWS",
      "SMOKEY PARK",
      "SMOKY FALLS",
      "SMOKY PINES",
      "SNEAKING CREEK",
      "SNOW FLAKE",
      "SNOW WHITE",
      "SOCO ACRES",
      "SOLITARY MEADOW",
      "SORRELLS COVE",
      "SORRELLS CREEK",
      "SPLIT PINE",
      "SPY ROCK",
      "SQUAW RIDGE",
      "SQUIRREL HILL",
      "STALL BRANCH",
      "STAMEY COVE",
      "STAR RIDGE",
      "STEVENS CREEK",
      "STEVENSON COVE",
      "STILL HILL",
      "STILL POND",
      "STILLHOUSE COVE",
      "STONE HAVEN",
      "STONEY BROOK",
      "STONEY RIDGE",
      "STRAWBERRY HILL",
      "SUGAR COVE",
      "SUGAR GROVE",
      "SUGAR MOUNTAIN",
      "SUGAR PLUM",
      "SULPHUR SPRINGS",
      "SUMMER PLACE",
      "SUN VALLEY",
      "SUNNY ACRES",
      "SUNSET FALLS",
      "SUNSET RIDGE",
      "SUNSHINE COVE",
      "SUNSHINE HILL",
      "SUSIE NOLAND",
      "SUTTON TOWN",
      "SWEET LEAF",
      "SWIMMING HOLE",
      "SWISS VALLEY",
      "TALL PINES",
      "TALL TIMBER",
      "TALL TIMBERS",
      "TARA NOVA",
      "TATER HILL FARM",
      "TAYLOR SPRINGS",
      "TERRELL COVE",
      "TEST FARM",
      "THE HARD",
      "THE HAWKS NEST",
      "THE HIGH",
      "THE RED OX",
      "THOMPSON COVE",
      "THORNY KNOLL",
      "THUNDER RIDGE",
      "THURMAN EVANS",
      "TIGER LILY",
      "TIGER MOUNTAIN",
      "TIMBER RIDGE",
      "TIMBERLANE CONNECTOR",
      "TINKER BELL",
      "TIPP FIELD",
      "TOBACCO BARN",
      "TOUCH THE STARS",
      "TOWN CENTER",
      "TRAILS END",
      "TRI LAKES",
      "TRI LAKES",
      "TRICKLE CREEK",
      "TRILLIUM END",
      "TRIPLE CREEK",
      "TROUT POND",
      "TUG FORK",
      "TUG HILL",
      "TUMBLING FORK",
      "TURKEY CREEK",
      "TURKEY HOLLOW",
      "TURNER BRANCH",
      "TUSCOLA SCHOOL",
      "TWIN BROOK",
      "TWIN FORKS",
      "TWIN MAPLES",
      "TWIN OAKS",
      "UNDERWOOD COVE",
      "UP OVER",
      "UTAH MOUNTAIN",
      "VALLEY BROOK",
      "VALLEY CREEK",
      "VALLEY HILL",
      "VALLEY OVERLOOK",
      "VALLEY VIEW CIR",
      "VALLEY VILLAS",
      "VAN ARRINGTON",
      "WADE REECE",
      "WADY BRANCH",
      "WAGON WHEEL",
      "WAITSEL CONNECTOR",
      "WALKING HORSE",
      "WALMART PLAZA",
      "WALNUT CREEK",
      "WALNUT FORD",
      "WALNUT RIDGE",
      "WALNUT TRAIL",
      "WALTER C",
      "WALTS PATH",
      "WARREN COVE",
      "WARREN MESSER",
      "WATER WHEEL",
      "WEEPING CHERRY",
      "WELCH MESSER",
      "WELLS EVENTS",
      "WESLEY CREEK",
      "WHEELER HILL",
      "WHISTLING OAK",
      "WHITE DOGWOOD",
      "WHITE MOUNTAIN",
      "WHITE OAK",
      "WHITEWATER FALLS",
      "WHY WORRY",
      "WILD ROCK",
      "WILD ROSE",
      "WILDCHERRY HILL",
      "WILKINSON PASS",
      "WILL BAILEY",
      "WILL HYATT",
      "WILLIAMS MOUNTAIN",
      "WILLIE BILLS",
      "WILLIS COVE",
      "WILLIS HILL",
      "WILLOW TREE",
      "WILLS COVE",
      "WILSON COVE",
      "WINCHESTER CREEK",
      "WIND SPIRIT",
      "WINDING CREEK",
      "WINDSWEPT RIDGE",
      "WINDY HILL",
      "WOLF RIDGE",
      "WOODLAND CHURCH",
      "WOODS EDGE",
      "WORLEY COVE",
      "WOUNDED KNEE",
      "YATES COVE",
      "YELLOW PATCH",
      "YONDER MOUNTAIN",
      "ZEMRY CALDWELL",
      "ZEPHIE SPRINGS"

  };

  private static String[] CITY_LIST = new String[]{
    "CANTON",
    "CLYDE",
    "LAKE JUNALUSKA",
    "MAGGIE VALLEY",
    "NEWPORT",
    "WAYNESVILLE",
    "WEST CANTON",

    "BUNCOMBE",
    "BALSAM",
    "CANDLER",
    "ENKA",
    "LEICESTER"
  };

}