
package net.anei.cadpage.parsers.NC;

import java.util.Properties;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.SplitMsgOptions;
import net.anei.cadpage.parsers.SplitMsgOptionsCustom;
import net.anei.cadpage.parsers.dispatch.DispatchSouthernParser;

public class NCMcDowellCountyParser extends DispatchSouthernParser {

  public NCMcDowellCountyParser() {
    super(null, "MCDOWELL COUNTY", "NC", 
          DSFLG_OPT_DISP_ID | DSFLG_ADDR | DSFLG_ADDR_TRAIL_PLACE | DSFLG_OPT_X | DSFLG_OPT_CODE | DSFLG_TIME);
    setupMultiWordStreets(MWORD_STREET_LIST);
    setupSaintNames("JOSEPH");
    removeWords("COVE");
    setupCities(CITY_LIST);
  }
  
  @Override
  public SplitMsgOptions getActive911SplitMsgOptions() {
    return new SplitMsgOptionsCustom();
  }

  @Override
  public boolean parseMsg(String body, Data data) {
    if (! super.parseMsg(body, data)) return false;
    data.strCall = stripFieldEnd(data.strCall, "-");
    data.strCity = stripFieldEnd(data.strCity, " CITY");
    data.strCity = stripFieldEnd(data.strCity, " AREA");
    return true;
  }
  
  @Override
  public String adjustMapAddress(String addr) {
    addr = PK_PTN.matcher(addr).replaceAll("PARK");
    return super.adjustMapAddress(addr);
  }
  private static final Pattern PK_PTN = Pattern.compile("\\bPK\\b", Pattern.CASE_INSENSITIVE);
  
  @Override
  public String adjustMapCity(String city) {
    city = city.toUpperCase();
    city = stripFieldEnd(city, " AREA");
    return convertCodes(city, MAP_CITY_TABLE);
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
    "AB ELLIOTT",
    "AG SERVICES",
    "ALBERT JOYNER SR",
    "ALLISON HOLLOW",
    "AMERICAN THREAD VILLAGE",
    "AMERICAN THREAD",
    "APPALACHIAN HILL",
    "APPLE VALLEY",
    "ARBOR VIEW",
    "ARMSTRONG CREEK",
    "AUTUMN VIEW",
    "BAT CAVE",
    "BEACON RIDGE",
    "BEAR CLIFF",
    "BEAR CUB",
    "BEAR DEN MOUNTAIN",
    "BEAVER CREEK",
    "BETHEL CHURCH",
    "BIG BEAR",
    "BIG BUCK",
    "BIG SKY",
    "BILL COOK",
    "BILL DECK",
    "BLACK FOREST",
    "BLACK GUM",
    "BLUE RIDGE",
    "BOULDER ROCK",
    "BOX CREEK",
    "BRACKETT TOWN",
    "BRADLEY PARK",
    "BRANSON CREEK",
    "BREEZY HILL",
    "BROWN BROTHERS",
    "BUCK CREEK",
    "BUMPY HILL",
    "BYRDS MOBILE HOME",
    "CAMP GRIER",
    "CANE CREEK",
    "CANNON WOODS",
    "CARRIAGE STATION",
    "CATAWBA RIVER",
    "CE GOODE",
    "CHARLES WILLIAMS",
    "CHARLIE T",
    "CHESTNUT HILL",
    "CHESTNUT OAK FOREST",
    "CLEAR CREEK",
    "CLEAR WATER",
    "CLOVER VIEW",
    "CLUB HOUSE",
    "CLUB VIEW",
    "COACHMAN HILLS",
    "COLE HILL",
    "COLUMBIA CAROLINA",
    "COOL SPRING",
    "COOL WATERS",
    "COPPER POT",
    "COTTAGE GROVE",
    "COUNTRY ACRES",
    "CROSS CREEK NORTH RIDGE",
    "CROWN RIDGE",
    "CURTIS CREEK",
    "DAVIS TOWN",
    "DEEP COVE SPRINGS",
    "DEEP WOODS",
    "DEER PARK RESORT",
    "DEER PARK",
    "DEER PATH",
    "DEWEY BROWN",
    "DEWEY R JONES",
    "DOBSONS VIEW",
    "DOC ROBINSON",
    "DRUCILLA CHURCH",
    "DRUMS INLET",
    "DUSTY HOLLOW",
    "DWIGHT BERRY",
    "EAGLE CREEK",
    "EAGLE HILL",
    "EARL LEE",
    "EASTFIELD SCHOOL",
    "EBENEZER CHURCH",
    "ED ALLISON",
    "EMMA GRACE",
    "EP BOYD",
    "FALLING CREEK",
    "FARM HILL",
    "FIELD STREAM",
    "FIFTH C",
    "FIFTH EM",
    "FOGGY MOUNTAIN",
    "FOREST HILL",
    "FOREST LAKE HEIGHTS",
    "FOREST PARK",
    "FOREST RIDGE",
    "FORK RIVER",
    "FORT SUGAR HILL",
    "FOUR WHEEL",
    "FOURTH C",
    "FOURTH EM",
    "FOX TAIL",
    "FRED PARKER",
    "GARDEN CREEK",
    "GLENWOOD BAPTIST CHURCH",
    "GOLDEN LEAF",
    "GOLF COURSE",
    "GOOSE CREEK",
    "GRAND OAKS",
    "GRASSY HOLLOW",
    "GREAT OAKS",
    "GREEN LEAF",
    "GREEN MEADOW",
    "GREEN MOUNTAIN",
    "GREY WOLF",
    "HALF TIMBER",
    "HALL ESTATES",
    "HARMONY GROVE",
    "HAW BRANCH",
    "HEMLOCK RIDGE",
    "HENRY MCCALL",
    "HENSLEYS GROVE",
    "HIDDEN VALLEY",
    "HIGH COUNTRY",
    "HIGH TRAIL",
    "HILL CREEK",
    "HOLLY HILL",
    "HOLLY HOCK",
    "HOOVER HOLLOW",
    "HOPE WELL",
    "HOPPY TOM HOLLOW",
    "HUNNICUT MOUNTAIN",
    "HUNT CAMP",
    "HUSKINS BRANCH",
    "JACK CORPENING",
    "JAKES BRANCH",
    "JAY DAN",
    "JENNY LIND",
    "JESSIE JAMES",
    "JOHN ROACH",
    "JOHN SR",
    "JOHNSON HOLLOW",
    "JUMPING BRANCH",
    "KATHLEEN PARK",
    "KEN TOM",
    "LAKE CLUB",
    "LAKE JAMES LANDING",
    "LAKE JAMES",
    "LAKE TAHOMA",
    "LAUREL CROSSING",
    "LAWRENCE HOLLIFIELD",
    "LEGACY PATH",
    "LEVEL PLAINS",
    "LIMEKIL VIEW",
    "LINVILLE HOLLOW",
    "LIPE THOMPSON",
    "LITTLE BUCK CREEK",
    "LITTLE DOE",
    "LITTLE GARDEN",
    "LITTLE SWITZERLAND",
    "LOCUST COVE",
    "LOG CABIN",
    "LONESOME PINE",
    "LOOKING GLASS",
    "LOOKING ROCK",
    "LOS PINOS",
    "LOST COVE",
    "LYTLE MOUNTAIN",
    "MACHINE SHOP",
    "MACK NOBLITT",
    "MACKEY CREEK",
    "MAJOR CONLEY",
    "MAPLE HILL",
    "MARTIN BRANCH",
    "MASHBURN BRANCH",
    "MCDOWELL HIGH",
    "MCDOWELL JUNIOR HIGH",
    "MEDICAL PARK",
    "MELODY HAVEN",
    "MEMORIAL PARK",
    "MIRACLE VALLEY",
    "MISTY MOUNTAIN",
    "MISTY SHADOW",
    "MOCKING BIRD",
    "MOFFITT BRANCH",
    "MOFFITT HILL CHURCH",
    "MOFFITT HILL",
    "MONTFORD COVE",
    "MOOSE CAMPGROUND",
    "MORNING DOVE",
    "MORRIS HOLLOW",
    "MOUNTAIN IVY",
    "MOUNTAIN VIEW",
    "MOUNTAIN VISTA",
    "MUD CUT",
    "MUDDY CREEK",
    "MYERS NORTON",
    "MYSTIC LANDING",
    "NANCY TOLLEY",
    "NEAL MOUNTAIN",
    "NEBO SCHOOL",
    "NED MCGIMSEY",
    "NEWBERRY CREEK",
    "NIX CREEK CHURCH",
    "NIX CREEK",
    "NORA ALLISON",
    "NORTH COVE SCHOOL",
    "NORTH ON RAMP TATE",
    "NORTH RIDGE",
    "NORTH WAYCASTER",
    "OAK HILL",
    "OAK PINE",
    "OAKDALE ESTATES",
    "OBE MOORE",
    "OCONEE FALLS",
    "OLDE DUFFER",
    "OPEN VALLEY",
    "OPHARD HENSLEY",
    "OVERLOOK PARK",
    "OWL HOLLOW",
    "PARKER PADGETT",
    "PAXTON CREEK",
    "PEPPERS CREEK",
    "PERSIMMON BRANCH",
    "PG BAPTIST CHURCH",
    "PINE COVE",
    "PINE HOLLOW",
    "PINNACLE CHURCH",
    "PINNACLE HEIGHTS",
    "PITTS STATION",
    "PLEASANT HILL",
    "PLEASANT VIEW",
    "POLLY SPOUT",
    "PORTER RIDGE",
    "POST OFFICE",
    "PROCTORS KNOB",
    "QUAIL HOLLOW",
    "QUARTER MOUNTAIN",
    "RAINBOW TROUT",
    "RED HILL",
    "RED OAK",
    "REVIS CEMETERY",
    "RHOM TOWN",
    "RIVER BEND",
    "RIVER BREEZE",
    "RIVER VIEW",
    "ROBERT MAYNOR",
    "ROBY CONLEY",
    "ROCKING ROBYN",
    "ROCKY PASS",
    "ROCKY SPUR",
    "ROCKY TOP",
    "ROLANDS CHAPEL",
    "ROLLING HILLS",
    "ROLLING MEADOW",
    "ROSE LEE",
    "ROSES CHAPEL",
    "ROY HOLLIFIELD",
    "ROY MOORE",
    "SADDLE WOOD",
    "SALEM CHURCH",
    "SALLY GAP",
    "SHADY BROOK",
    "SHADY GROVE",
    "SHERWOOD FOREST",
    "SILVERS WELCH",
    "SILVERY SANDS",
    "SIXTH EM",
    "SLIPPERY ROCK",
    "SMOKY MOUNTAIN",
    "SNAKE WHITE",
    "SOUTH CREEK",
    "STACY FARM",
    "STACY HILL",
    "STACY HOLLOW",
    "STONES THROW",
    "STONEY BROOKE",
    "STONEY CREEK",
    "SUGAR HILL",
    "SUNNY GROVE",
    "TABLE TOP",
    "TATER TOT",
    "TAYLOR LAKE",
    "THOUSAND OAKS",
    "THREE POINT",
    "TOMS CREEK",
    "TRAVELERS REST",
    "TRIPLE J",
    "TRIPLE R",
    "TWIN LAKES",
    "UPTONS LANDING",
    "US 221",
    "VEIN MOUNTAIN",
    "VERNON BRADLEY",
    "WAITES HOLLIFIELD",
    "WALNUT GROVE",
    "WARREN MOUNTAIN",
    "WATERS EDGE",
    "WEST CAMP",
    "WEST HENDERSON",
    "WEST LAKE",
    "WESTWOOD CHATEAU",
    "WHISPERING RIDGE",
    "WHITE PINES",
    "WILDCAT BLUES",
    "WILDLIFE CLUB",
    "WILDLIFE LAKE",
    "WILLOW CREEK",
    "WILSON FARM",
    "WILSON VALLEY",
    "WINDING STAIRS",
    "WINSOME FOREST",
    "WOLF CREEK",
    "WOODY FARM",
    "ZEB VANCE",
    "ZION HILL"
  };
  
  private static final Properties MAP_CITY_TABLE = buildCodeTable(new String[]{
      "ASHFORD",            "MARION",
      "HANKINS NORTH FORK", "MARION",
      "NORTH ASHFORD",      "MARION",
      "NORTH WOODLAWN",     "MARION",
      "PG",                 "MARION",
      "PLEASANT GARDEN",    "MARION",
      "SUGAR HILL",         "MARION",
      "WOODLAWN",           "MARION"
  });
  
  private static final String[] CITY_LIST = new String[]{
      
    //cities
    "MARION",
    "MARION AREA",
    "MARION CITY",
    "HANKINS NORTH FORK",
    "WOODLAWN",
    "NORTH WOODLAWN",
    
    //towns
    "OLD FORT",
    "OLD FORT AREA",
    "OLD FORT TOWN",
    
    //Census-designated place
    "WEST MARION",
    "WEST MARION CITY",
    
    //Unincorporated communities
    "ASHFORD",
    "GLENWOOD",
    "LINVILLE FALLS",
    "LITTLE SWITZERLAND",
    "NEBO",
    "NORTH ASHFORD",
    "NORTH COVE",
    "PG",
    "PLEASANT GARDENS",
    "PROVIDENCE",

    //townships
    "CROOKED CREEK",
    "DYSARTSVILLE",
    "MONTFORD COVE",
    "PLEASANT GARDENS",
    "WOODLAWN-SEVIER",
    "SUGAR HILL",
    
    // Buncombe County
    "ASHEVILLE",
    "BLACK MOUNTAIN",
    
    // Rutherford County
    "UNION MILLS",
    
    // Mitchell County
    "SPRUCE PINE"
  };
}
