package net.anei.cadpage.parsers.NC;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchSouthernParser;


public class NCSampsonCountyParser extends DispatchSouthernParser {
  
  public NCSampsonCountyParser() {
    super(CITY_LIST, "SAMPSON COUNTY", "NC", DSFLAG_BOTH_PLACE | DSFLAG_FOLLOW_CROSS);
    setupMultiWordStreets(MULT_WORD_STREET_LIST);
    setupSaintNames("MATTHEWS");
    removeWords("TRAIL", "SQUARE", "STREET");
  }
  
  @Override
  public String getFilter() {
    return "@sampsonnc.com";
  }
  
  @Override
  protected boolean parseMsg(String body, Data data) {
    if (!super.parseMsg(body, data)) return false;
    if (data.strApt.toUpperCase().startsWith("TAC")) {
      data.strChannel = data.strApt;
      data.strApt = "";
    }
    else if (data.strCity.length() == 0 && data.strPlace.startsWith("TAC")) {
      int brk = 3;
      while (brk < data.strPlace.length() && brk == ' ') brk++;
      while (brk < data.strPlace.length() && brk != ' ') brk++;
      data.strChannel = data.strPlace.substring(0,brk).trim();
      data.strPlace = data.strPlace.substring(brk).trim();
    }
    return true;
  }
  
  @Override
  public String getProgram() {
    return super.getProgram().replace("APT", "APT CH");
  }
  
  private static final String[] MULT_WORD_STREET_LIST = new String[]{

    "ALDERMAN MILL",
    "ALEX BENTON",
    "ALPINE CHURCH",
    "AM FARM",
    "AMAN DAIRY",
    "AMY JORDAN",
    "ANDREWS CHAPEL",
    "ANNIE BELL",
    "APPLE BLOSSOM",
    "ARCHIE LEE",
    "AUNT JANIE",
    "AUTO WAY",
    "AUTRY MILL",
    "AUTUMN LEAF",
    "BALLEY CASTLE",
    "BAPTIST CHAPEL",
    "BARBER COOPER",
    "BASS LAKE",
    "BATTLE CREEK",
    "BEAMAN WOODS",
    "BEAVER DAM",
    "BELL WOODS",
    "BELLS BRANCH",
    "BELVIN MAYNARD",
    "BELVOIR FARM",
    "BELVOIR SCHOOL",
    "BENT TREE",
    "BERRY WOOD LOOP",
    "BEULAH CHURCH",
    "BF GRADY",
    "BIG FARM",
    "BIG PINEY GROVE",
    "BILL WATERS",
    "BILL WILLIAMS",
    "BILLIE BRITT",
    "BIRD DOG TEW",
    "BIRDY P",
    "BJ JOHNSON",
    "BLACK BEAR",
    "BLACK RIVER",
    "BLAND SCHOOL",
    "BOB RUPERT",
    "BOBBY HOPE",
    "BONEY MILL",
    "BOREN BRICK",
    "BOYKIN BRIDGE",
    "BOYKIN HAYES",
    "BRICK MILL",
    "BROWNS CHURCH",
    "BUBBA GUMP",
    "BUBBLING BROOK",
    "BUCKHORN CREEK",
    "BUD JOHNSON",
    "BUD MARTIN",
    "BUD SPELL",
    "BUDD GODWIN",
    "BULL TAIL",
    "BULLARD PIT",
    "BUSH WAY",
    "BUSY BEE",
    "BUTLER CREST",
    "BUTLER ISLAND",
    "BUTLER LAKES",
    "BYRON BUTLER",
    "CABBAGE PATCH",
    "CABIN MUSEUM",
    "CAMP FOUR",
    "CAPERS WALK",
    "CAPTAIN WESTBROOK",
    "CARR CHURCH",
    "CARROLL A BRITT",
    "CARROLL STORE",
    "CARRY BRIDGE",
    "CASE FARM",
    "CATTLE CROSSING",
    "CECIL HALL",
    "CEDAR POINT",
    "CHALLENGE CLUB",
    "CHARLES NEWLAND",
    "CHERRY TREE",
    "CHRISTMAS TREE",
    "CLAUDES DRAG",
    "CLEAR RUN SCHOOL",
    "CLEAR SPRING",
    "CLIVE JACOBS",
    "CLUB HOUSE",
    "COKER STORE",
    "CONCORD SCHOOL",
    "CORINTH CHURCH",
    "COTTON GIN",
    "COUNTRY CLUB",
    "COUNTRY DEW",
    "COUNTRY HILL",
    "COUNTRY MANOR",
    "COUNTRY MEADOW",
    "COUNTRY SIDE",
    "COUNTY COMPLEX",
    "CRESCENT POND",
    "CROOKED PINE",
    "CROW BEST",
    "CROWN CASTLE",
    "CRYSTAL SAND",
    "CURTIS IVEY",
    "DAUGHTRY TOWN",
    "DAVE BRIGHT",
    "DAVID HOBBS",
    "DAVID PARKER",
    "DEEP FOREST",
    "DEER RUN",
    "DEER VIEW",
    "DELL MURPHY",
    "DELLA CHESNUTT",
    "DEVANES FARM",
    "DEWITT WILLIAMS",
    "DICK POPE",
    "DICKSON SLOAN",
    "DIXIE CHOPS",
    "DM RANCH",
    "DOC HIGHSMITH",
    "DOCK AUTRY",
    "DONALD TUCKER",
    "DR KERR",
    "DR MARTIN L KING JR",
    "DR MARTIN L KING",
    "DR MARTIN LUTH KING JR",
    "DR MARTIN LUTH KING",
    "DR MARTIN LUTHER KING JR",
    "DRAG STRIP",
    "DUCK POND",
    "EASTER LILY",
    "EBENEZER FOREST",
    "ED COLLINS",
    "EDDIE L JONES",
    "EDMOND MATTHIS",
    "EFFIE PETERSON",
    "ELBERT SPELL",
    "ELDON STORE",
    "ELDON THORNTON",
    "ELM TREE",
    "EMMET THORNTON",
    "ERNEST TANN",
    "ERNEST WILLIAMS",
    "ERVIN WILLIAMS",
    "EUGENE JERNIGAN",
    "EVA KATE",
    "EVERGREEN CHURCH",
    "FAIRCLOTH BRIDGE",
    "FALLING LEAVES",
    "FAMILY FARM",
    "FANN SCHOOL",
    "FARM TREE",
    "FEED MILL",
    "FIVE BRIDGE",
    "FLEET COOPER",
    "FORK LAKE",
    "FOX HILLS",
    "FOX RUN",
    "FRED SMITH",
    "FRED TEW",
    "FUTRELL POPE",
    "GARCIA FAMILY",
    "GARDEN SPOT",
    "GARLAND AIRPORT",
    "GE MORGAN",
    "GEORGE HI",
    "GEORGE MCKENZIE",
    "GODWIN ESTATE",
    "GODWIN FARM",
    "GODWIN LAKE",
    "GOODSON FARM",
    "GOSHEN CHURCH",
    "GOVERNOR MOORE",
    "GRACE D KING",
    "GRADY TEW",
    "GREEN PATH",
    "GREENE FARM",
    "GREENS BRIDGE",
    "GRUBBS DALE",
    "HAGAR MURPHY",
    "HAL REGISTER",
    "HAMTOWN GREENS",
    "HAPPY TRAIL",
    "HARMONY CHURCH",
    "HARNETT CHURCH",
    "HARPER HOUSE",
    "HARPERS GLEN",
    "HARVEY LEWIS",
    "HATTIES MIRACLE",
    "HAWLEY RIDGE",
    "HAY BARN",
    "HAY FIELD",
    "HAYES CHAPEL",
    "HAYES MILL",
    "HAYNE EXIT",
    "HAYNE STRETCH",
    "HB LEWIS",
    "HEART PINE",
    "HELL TOWN",
    "HENRY VANN FARM",
    "HENRYS LANDING",
    "HERRING LOOP",
    "HICKORY GROVE",
    "HIDDEN POND",
    "HIGH HOUSE",
    "HITCHING POST",
    "HOBBS VIEW",
    "HOBSON MAYNER",
    "HOG HOUSE",
    "HOLLOW BRIDGE",
    "HOLLY THICKET",
    "HOLLY TREE",
    "HOME PLACE",
    "HOPE CHURCH",
    "HORACE HENRY",
    "HORSE PASTURE",
    "HOSS RIDGE",
    "HOUSES MILL",
    "HUBBARD BUTLER",
    "HUNTERS RIDGE",
    "HUNTERS WALK",
    "HUNTLEY SCHOOL",
    "HW JERNIGAN",
    "INDIAN HILL",
    "INDIAN TOWN",
    "IRA B TART",
    "ISAAC WEEKS",
    "IVEY PARK",
    "JACOB FARM",
    "JACOB WEST",
    "JADA ALLEN",
    "JAMES BAREFOOT",
    "JAMES DAVID",
    "JAMES MCLAMB",
    "JB ALDERMAN",
    "JB WILSON",
    "JERNIGAN LOOP",
    "JIM MATTHEWS",
    "JOE BUD",
    "JOE W SMITH",
    "JOEL JONES",
    "JOHN ALLEN",
    "JOHN M JACKSON",
    "JOHN MARK",
    "JOHN NUNNERY",
    "JOHNSON BREEDER",
    "JOHNSON TANNER",
    "JONES POND",
    "JOSH SESSOMS",
    "JULIUS SUTTON",
    "JUMPING RUN",
    "JUNIOUS LUCAS",
    "JUNK YARD",
    "JV FARM",
    "K BRYAN",
    "KADER MERRITT",
    "KATTIE TART",
    "KENAN WEEKS",
    "KENNETH CARTER",
    "KINGS POND",
    "KITTY FORK",
    "KOOPMAN DAIRIES",
    "KORNEGAY TOWN",
    "LAKE ARTESIA",
    "LAKEWOOD SCHOOL",
    "LARK HILL",
    "LAS VEGAS",
    "LAUREL LAKE",
    "LAUREL WOOD",
    "LAUREN BROOKE",
    "LD JOHNSON",
    "LEA ANN",
    "LEE ALLEN POPE",
    "LEE FARM",
    "LEE`S CHAPEL CHURCH",
    "LEES CHAPEL CHURCH",
    "LEIGHTON HALL",
    "LEON HOLLAND",
    "LEROY AUTRY",
    "LEWIS ILEY TEW",
    "LILLY MAE",
    "LINDSAY FARM",
    "LISBON BRIDGE",
    "LITTLE COHARIE",
    "LITTLE HAWK",
    "LITTLE JOES",
    "LITTLE POND",
    "LOIS DAVIS",
    "LONE STAR",
    "LONG LEAF",
    "LONGVIEW LAKE",
    "LONNIE PARKER",
    "LOVE OF KIDS",
    "LUCAS DAIRY",
    "LUKE HOBBS FARM",
    "MA KITCHEN",
    "MACK JOSEPH",
    "MAMA ETHEL",
    "MAPLE GROVE CHURCH",
    "MAPLE LEAF",
    "MARSH KORNEGAY",
    "MARTIN L KING JR",
    "MARTIN L KING",
    "MARTIN LUTH KING JR",
    "MARTIN LUTH KING",
    "MARTIN LUTHER KING JR",
    "MARTIN LUTHER KING",
    "MARTIN LUTHER KING",
    "MARY E SMITH",
    "MARY MARSH",
    "MAURICE PATE",
    "MAXTON BASS",
    "MB BENNETT",
    "MCGEE CHURCH",
    "MCKOY LOOP",
    "MEADOW OAK",
    "MERRY OAKS",
    "MICROWAVE TOWER",
    "MIDWAY ELEMENTARY SCHOOL",
    "MILL BRANCH",
    "MILL BROOK",
    "MILL CREEK CHURCH",
    "MILL POND",
    "MILL RIDGE",
    "MINGO CHURCH",
    "MIRIE NAYLOR",
    "MJ JOHNSON",
    "ML GILBERT",
    "MOON JOHNSON",
    "MOORE`S BRIDGE",
    "MOORES BRIDGE",
    "MOSES NEWTON",
    "MOSES REGISTER",
    "MOUNT CARMEL CHURCH",
    "MOUNT ELAM CHURCH",
    "MOUNT GILEAD CHURCH",
    "MOUNT MORIAH CHURCH",
    "MT OLIVE",
    "NAYLOR SCHOOL",
    "NEW HOPE CHURCH",
    "NEWTON GROVE",
    "NN ELLIS",
    "NORTH JOHNSON",
    "NORTH PEAVINE",
    "NORTHEAST MAIN",
    "OAK GROVE CHURCH",
    "OAK RIDGE",
    "OLDE STORE",
    "OLLIE ROBINSON",
    "OPEN ACRES",
    "OSCAR TATE",
    "OTTIS TEW",
    "PAPA JACKS",
    "PAPA MOO",
    "PARKER MEMORIAL",
    "PATRICK HENRY",
    "PAUL CROMARTIE",
    "PAULA MATTHEWS",
    "PAYTON DANIELS",
    "PECAN TRACE",
    "PEE WEE",
    "PENNY FARM",
    "PENNY TEW MILL",
    "PERDIE HALL",
    "PETERSON FARM",
    "PICKLE SHED",
    "PIG CRADLES",
    "PIGGY BANK",
    "PINE ACRES",
    "PINE CREST",
    "PINE FOREST SCHOOL",
    "PINE LOG",
    "PINE LOOP",
    "PINE OAK",
    "PINE RIDGE",
    "PINE TOP",
    "PINE TREE",
    "PINELAND COURT",
    "PINEY GROVE",
    "PLAIN VIEW",
    "PLEASANT UNION",
    "POPLAR GROVE CHURCH",
    "PORK CHOP HILL",
    "POTATO HOUSE",
    "POWELL PAGE",
    "PREACHER HENRY",
    "QUAIL RUN",
    "QUEENS GRANT",
    "QUIET WATER",
    "R HALL",
    "RALPH HARGROVE",
    "RANDALL CHAPEL",
    "RB TART",
    "RB TYNDALL",
    "RED HILL CHURCH",
    "RED RANCH",
    "RED TIP",
    "REEDA BRANCH",
    "REGISTER SUTTON",
    "REPSIE COY",
    "RICHARD PARKER",
    "RILEY TOWN",
    "RIVER BEND",
    "RIVER DANCE",
    "RIVER MOON",
    "ROBERTS GROVE",
    "ROCK HOLLOW",
    "ROGERS MILL",
    "ROSIN HILL",
    "ROY C JACKSON",
    "ROY CASHWELL",
    "ROY JONES",
    "ROYALS CHAPEL",
    "RUFUS WELLS",
    "RUNNING BRANCH",
    "SADDLE CLUB",
    "SAMPSON ACRES",
    "SAND STONE",
    "SAND TRAP",
    "SANDY ACRES",
    "SANDY BOTTOM",
    "SANDY RIDGE",
    "SAVANNAH HILL",
    "SERENITY LAKE",
    "SEVEN EAGLES",
    "SEVEN MILE CHURCH",
    "SHADY ACRES",
    "SHADY OAK",
    "SHALLOW SPRING",
    "SHARE CAKE",
    "SHIRLEY GRAY",
    "SHORT CUT",
    "SHRINE CLUB",
    "SIMMONS POND",
    "SINCLAIR LAKE",
    "SIX ACRE",
    "SIX RUNS CHURCH",
    "SIX RUNS",
    "SKEETER POINT",
    "SLEEPY HOLLOW",
    "SMITH FARM",
    "SMITH KEY",
    "SMITH WAY",
    "SOUTH CLINTON",
    "SOUTH ELDRIDGE",
    "SOUTH RIVER",
    "SOUTHERN PINES",
    "SPICY JANE",
    "SPIVEYS CORNER",
    "SPRING BRANCH",
    "SPRING VALE",
    "STAGE COACH",
    "STANLEY HALL",
    "STAR BITE",
    "STAR BRIGHT",
    "STAR LEGACY",
    "STATEN HALL",
    "STEVE HARRIS",
    "STONE PLACE",
    "STONEWALL KELLY",
    "STRAW DEN",
    "STRAW POND SCHOOL",
    "STRICKLAND CABIN",
    "SUMMER TIME",
    "SUMMIT RIDGE",
    "SUMNER HOBBS",
    "SURLES HARMON",
    "TARTS RIDGE",
    "TAYLORS BRIDGE",
    "TAYLORS CHAPEL",
    "TEN ACRE",
    "THREE PINES",
    "TOM AUTRY",
    "TOM BUTLER",
    "TOM CAT",
    "TOM MORRIS",
    "TOM NEWMAN",
    "TOM OATES",
    "TRAIL END",
    "TRAPPERS RUN",
    "TRINITY CHURCH",
    "TRIPLE B",
    "TRIPLE H",
    "TURKEY FARM",
    "TURTLE CREEK",
    "TYNDALL BRIDGE",
    "TYNDALL GROVE",
    "TYNDALL TOWN",
    "TYSON CARRIAGE",
    "UNION GROVE CHURCH",
    "UNION SCHOOL",
    "VADA W",
    "VELNA JACKSON",
    "WADE DAUGHTRY",
    "WADE STEDMAN",
    "WAGON WHEEL",
    "WALKER MALVIN",
    "WALKING STICK",
    "WALTER K EVANS",
    "WALTER K EVANS",
    "WALTER MOORE",
    "WARREN LAKE",
    "WARREN MILL",
    "WASH MCLAMB",
    "WATER OAK",
    "WATER RIDGE",
    "WATERY BRANCH",
    "WE CARE",
    "WELCOME SCHOOL",
    "WELLS CHAPEL CHURCH",
    "WEST DARDEN",
    "WEST GROVE",
    "WEST SIDE",
    "WEST STRICKLAND",
    "WHITE LAKE",
    "WHITE OAK CHURCH",
    "WHITE OAK",
    "WHITE WOODS",
    "WILBUR PRIDGEN",
    "WILD IRIS",
    "WILLIAM FORTNER",
    "WILLIAM PARKER",
    "WILLIAM R KING",
    "WILLIE BROWN",
    "WILLIE SADDLER",
    "WOLF TRAIL",
    "WOOD GLEN",
    "WOOD LAND",
    "WOOD VALLEY",
    "WOODY PINE",
    "WRENCH SCHOOL",
    "WRIGHT BRIDGE",
    "WRYE BRANCH",
    "YELLOW SKIN",
    "ZOAR CHURCH"
  };

  private static final String[] CITY_LIST = new String[]{
    // City
    "CLINTON",

    // Towns
    "AUTRYVILLE",
    "FAISON",
    "GARLAND",
    "HARRELLS",
    "NEWTON GROVE",
    "ROSEBORO",
    "SALEMBURG",
    "TURKEY",

    // Census-designated places
    "BONNETSVILLE",
    "DELWAY",
    "INGOLD",
    "IVANHOE",
    "KEENER",
    "PLAIN VIEW",
    "SPIVEYS CORNER",
    "VANN CROSSROADS",

    // Unincorporated communities
    "HOBBTON",
    "SUTTONTOWN",
    "WILLARD",

    // Townships
    "BELVOIR TWP",
    "DISMAL TWP",
    "FRANKLIN TWP",
    "HALLS TWP",
    "HERRING TWP",
    "HONEYCUTT TWP",
    "LISBON TWP",
    "LITTLE COHARIE TWP",
    "MCDANIELS TWP",
    "MINGO TWP",
    "NEWTON GROVE TWP",
    "NORTH CLINTON TWP",
    "PINEY GROVE TWP",
    "PLAIN VIEW TWP",
    "SOUTH CLINTON TWP",
    "SOUTH RIVER TWP",
    "TAYLORS BRIDGE TWP",
    "TURKEY TWP",
    "WESTBROOK TWP",
    
    // Cumberland County
    "GODWIN",
    "STEDMAN",
    
    // Duplin County
    "MAGNOLIA",
    "MT OLIVE",
    "ROSE HILL",
    "WALLACE",
    
    // Harnett County
    "DUNN"
  };
}
