package net.anei.cadpage.parsers.MI;

import java.util.Properties;

import net.anei.cadpage.parsers.GroupBestParser;

public class MILeelanauCountyParser extends GroupBestParser {

  public MILeelanauCountyParser() {
    super(new MILeelanauCountyAParser(), new MILeelanauCountyBParser());
  }

  static final Properties CALL_CODES = buildCodeTable(new String[] {
      "WELFARECHECK",     "Welfare Check",
      "WEATHER",          "Severe Weather Notification",
      "WEAPONVIOL",       "Weapon Violation",
      "WCTRAFFICSTOP",    "Boat Traffic Stop",
      "WCSUNK",           "Boat Sunk",
      "WCRECKLESS",       "Boat Operation Reckless",
      "WCOVERDUE",        "Boat Overdue",
      "WCMISC",           "Watercraft - Misc",
      "WCLOST",           "Lost Boat",
      "WCLIVERY",         "Watercraft Livery Inspection",
      "WCINSPECTION",     "Watercraft Inspection",
      "WCHAZARD",         "Watercraft Hazard",
      "WCFOUND",          "Found Boat",
      "WCFIRE",           "Boat Fire",
      "WCDISABLED",       "Boat Disabled",
      "WCCAPSIZE",        "Boat Capsize",
      "WCAI",             "Watercraft Injury Accident",
      "WCA",              "Boat Property Damage Accident",
      "WARRANTARREST",    "Warrant Arrest",
      "VININSPECTION",    "Vin Inspection",
      "VEHICLEDITCH",     "Vehicle In The Ditch",
      "VCSA",             "Violation Of Controlled Subst",
      "UNKNOWNPROBLEM",   "Unknown Prob/Person (Down)",
      "UNCONSCIOUS",      "Unconscious / Fainting (Near)",
      "UDAA",             "Stolen Vehicle",
      "TRESPASSING",      "Trespassing",
      "TRAUMATICINJ",     "Traumatic Injuries (Specific)",
      "TRAFFICVIOL",      "Traffic Violation",
      "TRAFFICSTOP",      "Traffic Stop",
      "THREATS",          "Threats",
      "TEST",             "Test/Training",
      "SUSPVEHICLE",      "Suspicious Vehicle",
      "SUSPPERSON",       "Suspicious Person",
      "SUSPINCIDENT",     "Suspicious Incident",
      "SUICIDEATT",       "Attempt Suicide",
      "SUICIDE",          "Suicide Death",
      "STROKE",           "Stroke/Transient Ischemic",
      "STANDBY",          "Civil Standby",
      "STALKING",         "Stalking",
      "STAB/GUNSHOT",     "Stab/Gunshot/Penetrating",
      "SORVIOLATION",     "Sex Offender Registry",
      "SNOWMISC",         "Snowmobile-Miscellaneous",
      "SMUGGLEJAIL",      "Smuggle Contraband into Jail",
      "SICKPERSON",       "Sick Person (Specific)",
      "SECUREMODE",       "School Secure Mode",
      "SCAM",             "Phone or Internet Scam",
      "RUNAWAYJUV",       "Runaway Juvenile",
      "ROBUNARMED",       "Robbery-Unarmed",
      "ROBARMED",         "Robbery-Armed",
      "ROADHAZARD",       "Road Hazard",
      "RETAILFRAUD",      "Retail Fraud",
      "REPOSSESSION",     "Repossession",
      "PSYCHIATRIC",      "Abnormal Behavior/Suicide",
      "PROBVIOLATION",    "Probation Violation",
      "PREGNANCY",        "Pregnancy/Birth/Miscarriage",
      "PPOVIOLATION",     "Personal Protection Order Vio",
      "PLANECRASHWATER",  "Plane Crash Water",
      "PLANECRASH",       "Plane Crash",
      "PERJURY",          "Perjury",
      "PAROLEVIOL",       "Parole Violation",
      "PARKING",          "Illegal Parking",
      "PAPERSERVICE",     "Paper Service",
      "OWI",              "Operating While Intoxicated",
      "OVERDOSE",         "Overdose/Poisoning (Ingestion)",
      "NSFCHECK",         "Non Sufficient Funds Check",
      "NOLICENSE",        "No Operators License",
      "NOISE",            "Noise/Loud Party Complaint",
      "NOINSURANCE",      "No Insurance",
      "NOACCOUNT",        "No Account Check",
      "NMMAERT",          "Emerg Response Team Call Out",
      "NMMACALLOUT",      "Northern MI Mutual Aid",
      "NEIGHBOR",         "Neighbor Trouble",
      "MVCROLLOVER",      "MVC Rollover",
      "MVCPP",            "MVC Private Property",
      "MVCI",             "MVC Injuries/Transportation",
      "MVCFLUIDS",        "MVC Fluids Leaking",
      "MVC",              "Motor Vehicle Crash",
      "MOTORISTASSIST",   "Motorist Assist",
      "MISSPERJUVENILE",  "Missing Person Juvenile",
      "MISSINGPERSON",    "Missing Person",
      "MISCJUVENILE",     "Miscellanenus Juvenile Activit",
      "MISCCOMP",         "Miscellaneous Complaint",
      "MIP4100",          "Minor in Possession Alcohol",
      "MIP3500",          "Minor in Possession Drugs",
      "MEDICALALARM",     "Medical Alarm - No Contact",
      "MDOP",             "MDOP Property",
      "LOSTPROPERTY",     "Lost Property",
      "LOCKDOWN",         "Lockdown",
      "LITTERING",        "Littering",
      "LIQUORINSPECT",    "Liquor Inspection",
      "LEAVESCENEMVCI",   "Leaving Scene Injury Accident",
      "LEAVESCENEMVC",    "Leaving Scene Prop. Damage Acc",
      "LAWADMIN",         "LAW ENFORCEMENT ADMINISTRATIVE",
      "LARCENYVEHICLE",   "Larceny From Vehicle",
      "LARCENY",          "Larceny",
      "KIDNAPPING",       "Kidnapping",
      "INTIMIDATION",     "INTIMIDATION",
      "INMATE",           "Inmate Transport",
      "INFO",             "Patrol Info",
      "IDENTITYTHEFT",    "Identity Theft",
      "ICERESCUE",        "Ice Rescue",
      "HUNTILLEGAL",      "Illegal Hunting",
      "HOSPICE",          "Hospice Death",
      "HOMICIDE",         "Homicide",
      "HEMORRHAGE",       "Hemorrhage/Laceration",
      "HEAT/COLDEXP",     "Heat Cold Exposure",
      "HEARTPROBLEMS",    "Heart Problems A.I.C.D",
      "HEADACHE",         "Headache",
      "HAZMAT",           "Hazardous Materials Incident",
      "HARASSMENT",       "Harrassment",
      "GUNSHOTS",         "Gun Shots",
      "GUNPERMIT",        "Gun Permit to Purchase",
      "FUELSPILL",        "Fuel Spill",
      "FTRPROPERTY",      "Failure To Return Rental Prop",
      "FRAUD",            "Fraud",
      "FOUNDPROPERTY",    "Found Property",
      "FLEEALLUDE",       "Fleeing Alluding",
      "FIREWORKS",        "Illegal Fireworks",
      "FIREWIRESDOWN",    "Fire-Power Wires Down",
      "FIREVEHICLE",      "Fire-Vehicle",
      "FIRETECH",         "Fire-Tech Rescue",
      "FIRESTRUCTURE",    "Fire-Structure",
      "FIRESMOKE",        "Fire Smoke",
      "FIREMISC",         "Fire Miscellaneous",
      "FIRELINESARCING",  "Fire-Power Line Arching",
      "FIREGRASS",        "Fire-Grass",
      "FIREGASLEAK",      "Fire-Gas Leak",
      "FIREEXPLOSION",    "Fire-Explosion",
      "FIREDUMPSTER",     "Fire-Dumpster",
      "FIRECHIMNEY",      "Fire-Chimney",
      "FIRECARBONMON",    "Fire-Carbon Monoxide",
      "FIREALARM",        "Fire Alarm",
      "FIGHT",            "Fight",
      "FAMTROUBLE",       "Family Trouble",
      "FALSEREPORT",      "False Police Report",
      "FALLS",            "Falls",
      "FAILREPORT",       "Failure to Report Property Dam",
      "EYEPROBLEMS",      "Eye Problems/Injuries",
      "EVENT",            "Fest, Parade, Pre-plan",
      "ENTRAPMENT",       "Inaccessible Incident",
      "EMBEZZLEMENT",     "Embezzlement",
      "ELECTROCUTION",    "Electrocution and Lightning",
      "DWRL",             "Driving With Rest. License",
      "DWLS",             "Driving While License Suspend",
      "DUMPING",          "Illegal Dumping",
      "DROWNING",         "Drowning",
      "DRIVEOFF",         "Drive Off From Gas Station",
      "DOMESTIC",         "Domestic",
      "DISPATCHDEER",     "Dispatch Deer",
      "DISORDERLY",       "Disorderly Person",
      "DIABETICPROB",     "diabetic problems",
      "DEERPERMIT",       "Deer Kill Permit",
      "DEATH",            "Death",
      "CSC",              "Criminal Sexual Conduct",
      "COUNTERFEITING",   "Counterfeiting",
      "CONV/SEIZURE",     "convulsions and seizures",
      "COMMITMENT",       "Mental Commitment",
      "CO2/HAZMAT/CBRN",  "CO2/Inhalation/HAZMAT/CBRN",
      "CIVILDEFENTEST",   "Civil Defense Test",
      "CIVIL",            "Civil Standby Civil Complaint",
      "CITIZENASSIST",    "Citizen Assist",
      "CHOKING",          "Choking",
      "CHILDABUSE",       "Child Abuse/Neglect",
      "CHESTPAIN",        "ChestPain/Dscmfrt (Non Trauma)",
      "CARDIACARREST",    "Cardiac/Respiratory/Death",
      "CARDEER",          "Car Deer",
      "CARANIMAL",        "Car vs Animal Accident",
      "BURNS",            "Burn (Scald) Explosion (Blast)",
      "BURNPERMIT",       "Burn Permits",
      "BUILDINGCHECK",    "Building Check",
      "BREATHINGPROB",    "Breathing Problems",
      "BREAKENTER",       "Breaking Entering",
      "BONDVIOLATION",    "Bond Violation",
      "BOMBTHREAT",       "Bomb Threat",
      "BIKECRASH",        "Bicycle Crash",
      "BACKPAIN",         "Back Pain (Non-Trauma/Recent)",
      "BACKGROUNDCHECK",  "Background Check",
      "ASSISTDEPT",       "Assist Another Department",
      "ASSAULTBATTERY",   "Assault and Battery",
      "ASSAULT",          "Sexual Assault/Stun Gun",
      "ARSON",            "Arson",
      "ANIMAL BITES",     "Animal Bites/Attacks",
      "ALLERGIES",        "Reactions/Envenomations Stings",
      "ALARMONSTAR",      "Alarm, OnStar",
      "ALARMHOLDUP",      "Alarm, Hold-up",
      "ALARMBE",          "Alarm, Breaking and Entering",
      "ALARMBANK",        "Alarm, Bank",
      "ALARMAUDIBLE",     "Alarm, Audible",
      "ACTIVESHOOTER",    "Active Shooter",
      "ACOWELCHECK",      "Animal Welfare Check",
      "ACOTRAP",          "Animal Trap Request",
      "ACOPICKUP",        "Animal For Pick-up",
      "ACOMISC",          "Animal Miscellaneous Complaint",
      "ACOLOST",          "Animal Lost",
      "ACOLARGE",         "Animal At Large",
      "ACOKENNEL",        "Animal Kennel Inspection",
      "ACOINJURY",        "Animal Injury",
      "ACOFOUND",         "Animal Found",
      "ACOBITE",          "Animal Bite",
      "ACOBARK",          "Animal Barking Complaint",
      "ABDOMINALPAIN",    "Abdominal Pain / Problems",
      "ABANDVEHICLE",     "Abandoned Vehicle",
      "911HANGUP",        "911 Hang-up"
  });

  static final Properties CITY_CODES = buildCodeTable(new String[]{
    "001", "CEDAR",
    "002", "EMPIRE",
    "003", "GLEN ARBOR",
    "004", "LAKE LEELANAU",
    "005", "LELAND",
    "006", "MAPLE CITY",
    "007", "NORTHPORT",
    "008", "OMENA",
    "009", "SUTTONS BAY",
    "010", "TRAVERSE CITY",
    "014", ""   // Unknown
  });
}
