package net.anei.cadpage.parsers.WA;

import java.util.Properties;

import net.anei.cadpage.parsers.dispatch.DispatchA41Parser;

public class WAKingCountyCParser extends DispatchA41Parser {

  public WAKingCountyCParser() {
    super(CITY_CODES, "KING COUNTY", "WA", "FIR\\d|[A-Z]9|[A-ZS]\\d|MD|TACP", A41_FLG_ID, CALL_CODES);
  }

  @Override
  public String getFilter() {
    return "cad@valleycom.org,@versaterm.cloud";
  }

  private static final Properties CALL_CODES = buildCodeTable(new String[]{
      "ACCINF", "Vehicle Accident",
      "ACCMDF", "Serious Vehicle accident",
      "ACCWAF", "Accident with fire",
      "ADVISE", "Informational dispatch/page",
      "AFA",    "Automatic fire alarm",
      "AID",    "Aid call",
      "AIDH",   "Aid call",
      "AIDMD",  "Aid call with medics",
      "AIDSVC", "Service call of an EMS nature",
      "AIDUNK", "Unknown Aid call",
      "AIRMJF", "Major aircraft accident",
      "AIRMNF", "Minor aircraft acident",
      "AIRSBY", "Standby for an aircraft in distress",
      "ALERT1", "gone",
      "ALERT2", "gone",
      "ALERT3", "gone",
      "BARK",   "Bark fire",
      "BOAT",   "Assist boat or boat accident",
      "BOATMF", "Boat minor fire",
      "BRSH",   "Brush fire",
      "BRSHEX", "Brush fire with exposures",
      "CFIRE",  "gone",
      "CHIMNE", "Chimney fire",
      "CO",     "Carbon Monoxide problem",
      "COMFIR", "Commercial fire",
      "CPR",    "Cardio-Pulmonary resuscitation",
      "CPRF",   "Cardio-Pulmonary resuscitation",
      "DROWN",  "Drowning",
      "DUMP",   "Dumpster fire",
      "DUMPEX", "Dumpster fire with exposure",
      "ELECTR", "Electrical fire",
      "EOC",    "Emergency Operations Center",
      "EXPLOS", "Explosion",
      "FOREST", "Forest fire",
      "HIRISE", "Hi-rise fire",
      "HZEXPF", "Hazardous materials exposure",
      "HZINV",  "Hazardous material investigation",
      "HZLEAK", "Haz-Mat leak",
      "ILBURN", "Illegal burn",
      "MCI1F",  "Multiple Casualty incident Level1",
      "MCI2F",  "Multiple Casualty incident Level 2",
      "MCI3F",  "Multiple Casualty incident Level 3",
      "MCI4F",  "Multiple Casualty incident Level 4",
      "MEDIC",  "ALS response; medic upgrade",
      "MINFIR", "Minor Fire",
      "MUTUAL", "Mutual aid request",
      "NGASIN", "Natural Gas leak inside a structure",
      "NGASXT", "Natural Gas leak outside a structure",
      "NONSTR", "Non-Structure fire",
      "OBV",    "Obvious death/mortality",
      "ODF",    "Overdose minor in nature",
      "ODMDF",  "Serious overdose with medics",
      "ODORIN", "Odor investigation inside a structure",
      "ODORXT", "odor investigation outside a structure",
      "POOL",   "Swimming pool call-drowning etc.",
      "RESCUE", "Rescue of any nature (special ops)",
      "RESFIR", "Residential fire",
      "RFIRE",  "gone",
      "RIVER",  "flooding or assistance",
      "SEARCH", "Search and rescue mission",
      "SERVIC", "Service call of any type; not aid",
      "SHACK",  "Shack fire",
      "SHOTF",  "Shooting-minor",
      "SHOTMF", "Shooting-serious with medics",
      "SMOKXT", "Smoke investigation-outside",
      "SPILL",  "Unknown substance spilled",
      "STABF",  "Stabbing-minor",
      "STABMF", "Stabbing-major",
      "SUSFIR", "Suspicious Fire",
      "SWFA",   "Sprinkler water flow alarm",
      "TRAINF", "Train fire or problem",
      "UNKFIR", "Unknown type fire",
      "VEHCOM", "Commercial vehicle fire",
      "VEHEX",  "Vehicle fire with exposure(s)",
      "VEHPAS", "Passenger vehicle fire",
      "WASH",   "Wash down(wash stuff off the road)",
      "WELCHK", "Welfare check",
      "WIRES",  "Electrical wires down/arcing",

  });

  private static final Properties CITY_CODES = buildCodeTable(new String[]{
      "ALG",  "Algona",
      "AUB",  "Auburn",
      "BEA",  "Beaux Arts",
      "BEL",  "Bellevue",
      "BLA",  "Black Diamond",
      "BON",  "Bonney Lake",
      "BUR",  "Burien",
      "CLY",  "Clyde Hill",
      "COV",  "Covington",
      "DES",  "Des Moines",
      "EDG",  "Edgewood",
      "ENU",  "Enumclaw",
      "FED",  "Federal Way",
      "FIF",  "Fife",
      "ISS",  "Issaquah",
      "KEN",  "Kent",
      "MED",  "Medina",
      "MER",  "Mercer Island",
      "MIL",  "Milton",
      "MPV",  "Maple Valley",
      "NBD",  "North Bend",
      "NDP",  "Normandy Park",
      "NEW",  "New Castle",
      "PAC",  "Pacific",
      "PRE",  "Preston",
      "RAV",  "Ravensdale",
      "REN",  "Renton",
      "SAM",  "Sammamish",
      "SEA",  "Seatac",
      "STL",  "Seattle",
      "SUM",  "Sumner",
      "TAC",  "Tacoma",
      "TUK",  "Tukwila",
      "VAS",  "Vashon"
  });
}
