package net.anei.cadpage.parsers.MD;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA48Parser;

public class MDTalbotCountyBParser extends DispatchA48Parser {

  public MDTalbotCountyBParser() {
    super(CITY_LIST, "TALBOT COUNTY", "MD", FieldType.PLACE, A48_NO_CODE);
    setupCallList(CALL_LIST);
    setupMultiWordStreets(MWORD_STREET_LIST);
    setupSaintNames("MICHAELS");
  }

  public String getFilter() {
    return "@talbotdes.org,dispatch@ccso.us,4702193527";
  }

  private static final Pattern PREFIX = Pattern.compile("([ A-Za-z0-9]+)(?: Page - Dispatch| - Page)(?=:)");
  private static final Pattern BOX_PTN = Pattern.compile("[ A-Z]+ \\d+-\\d+");
  @Override
  protected boolean parseMsg(String subject, String body, Data data) {
    body = stripFieldStart(body, "TALBOTDES:");
    body = stripFieldStart(body, "All Texts:");
    Matcher match = PREFIX.matcher(body);
    if (match.lookingAt()) {
      subject = match.group(1);
      body = body.substring(match.end());
    }
    int pt = body.indexOf("\nText");
    if (pt >= 0) body = body.substring(0,pt).trim();
    if (!super.parseMsg(subject, body, data)) return false;
    pt = data.strAddress.indexOf(';');
    if (pt >= 0) {
      String part1 = data.strAddress.substring(0, pt).trim();
      String part2 = data.strAddress.substring(pt+1).trim();
      if (BOX_PTN.matcher(part1).matches()) {
        data.strBox = part1;
        data.strAddress = part2;
      } else {
        data.strAddress = part1;
        data.strBox = part2;
      }
    }
    return true;
  }

  @Override
  public String getProgram() {
    return super.getProgram().replace("ADDR", "ADDR BOX");
  }

  private static final String[] MWORD_STREET_LIST = new String[]{
      "ANDERBY HALL",
      "BACHELORS HARBOR",
      "BACHELORS POINT",
      "BAILEYS NECK",
      "BAR NECK",
      "BLACK DOG",
      "BOLINGBROKE POINT",
      "BOONE CREEK",
      "BOZMAN NEAVITT",
      "BRICK ROW",
      "CALVES ACRE",
      "CAMBRIDGE MARKET PLACE",
      "CEDAR POINT",
      "CHANCELLOR POINT",
      "CHESAPEAKE HOUSE",
      "CHIURCH CREEK",
      "CROUSE MILL",
      "DEEP BRANCH",
      "DEEP NECK",
      "DOVER BRIDGE",
      "DUKES BRIDGE",
      "EAST SIXTH",
      "FOX MEADOW",
      "GLEBE CREEK",
      "GOOSE NECK",
      "GREEN BANKS",
      "HAWKES HILL",
      "HELS HALF ACRE",
      "HOPKINS NECK",
      "HORNS POINT",
      "HOWELL POINT",
      "INDUSTRIAL PARK",
      "KITTYS CORNER",
      "LANDING NECK",
      "LE GATES COVE",
      "LLOYDS LANDING",
      "LONG POINT",
      "MALLARD POINT",
      "MARENGO FARM",
      "MILES RIVER",
      "MT PLEASANT",
      "NINE TOWN",
      "NORTH BEND",
      "NORTH LIBERTY",
      "NORTH SIXTH",
      "PEACE CLIFF",
      "PIN OAK",
      "PINEY HILL",
      "POLLYS HILL",
      "PORPOISE CREEK",
      "QUAIL RUN",
      "QUAKER NECK",
      "QUEEN ANNE",
      "ROYAL OAK",
      "RUSTLING OAKS",
      "RYDERS REST",
      "SAILORS RETREAT",
      "SHERWOOD MANOR",
      "SKIPTON CORDOVA",
      "SKIPTON LANDING",
      "ST MICHAELS",
      "SWANN HAVEN",
      "TAPPERS CORNER",
      "TARBUTTON MILL",
      "THIRD HAVEN",
      "THREE BRIDGE BRANCH",
      "TILGHMAN ISLAND",
      "TOWN POINT",
      "TUNIS MILLS",
      "TURKEY CREEK",
      "WADES POINT",
      "WHITE MARSH",
      "WILLOUGHBY CANNERY",
      "WILLOW OAK",
      "WINDY HILL",
      "WORLD FARM",
      "WYE MILLS"

  };

  private static final CodeSet CALL_LIST = new CodeSet(
      "ABDOMINAL PAIN",
      "ABDOMINAL PAIN FEMALE W PAIN ABOVE NAVEL",
      "ABDOMINAL PAIN MALES W PAIN ABOVE NAVEL",
      "ABDOMINAL PAIN MALES W PAIN ABOVE NAVEL GREATER THAN 35 YOA",
      "ALARMS COMMERCIAL/INDUSTRIAL BUILDING",
      "ALARMS HIGH LIFE HAZARD - CO ALARM",
      "ALARMS RESIDENTIAL (MULTIPLE)",
      "ALARMS RESIDENTIAL (MULTIPLE) - CO ALARM",
      "ALARMS RESIDENTIAL (SINGLE)",
      "ALARMS RESIDENTIAL (SINGLE) - CO ALARM",
      "ANIMAL BITE SUPERFICIAL BITES",
      "ASSAULT NOT IN PROGRESS",
      "ASSIST EMS",
      "ASSIST FIRE DEPARTMENT",
      "BACK PAIN NON-TRAUMATIC",
      "BREATHING PROBLEM ABNORMAL BREATHING",
      "BREATHING PROBLEMS ABNORMAL BREATHING",
      "BREATHING PROBLEM  CLAMMY",
      "BREATHING PROBLEM DIFFICULTY SPEAKING",
      "BREATHING PROBLEM NOT ALERT",
      "CARDIAC/RESPIRATORY ARREST BREATHING UNCERTAIN",
      "CARDIAC/RESPIRATORY ARREST NOT BREATHING AT ALL",
      "CHEST PAINS - BREATHING NORMALLY >35",
      "CHEST PAINS - HEART ATTACK/ANGINA HX",
      "CHEST PAINS COCAINE",
      "CHEST PAINS CLAMMY",
      "CHEST PAINS NOT ALERT",
      "CHEST PAINS/DIFFICULTY SPEAKING BETWEEN BREATHS",
      "CITIZEN ASSIST/SERVICE CALL LOCKED IN/OUT BUILDING (NON MEDICAL ASSISTANCE)",
      "COMM STRUCTURE",
      "COURT ON DUTY",
      "DIABETIC PROBLEMS ABNORMAL BREATHING",
      "DIABETIC PROBLEMS NOT ALERT",
      "FALLS - NON-RECENT >6HR W INJURIES",
      "FALLS - NOT ALERT",
      "FALLS - NOT DANGEROUS BODY AREA",
      "FALLS - PUBLIC ASSIST NO INJURIES",
      "FALLS NOT DANGEROUS BODY AREA",
      "FALLS POSSIBLY DANGEROUS BODY AREA",
      "FALLS PUBLIC ASSIST NO INJURIES",
      "FALLS UNKNOWN STATUS",
      "FIRE DEPT WASHDOWN",
      "FUEL SPILL/ODOR CONTAINED SMALL SPILL",
      "FUEL SPILL/ODOR FUEL ODOR",
      "FUEL SPILL/ODOR MINOR SPILL",
      "GAS LEAK/ODOR COMMERCIAL/INDUSTRIAL BUILDING",
      "GAS LEAK/ODOR OUTSIDE ODOR",
      "GAS LEAK/ODOR RESIDENTIAL (SINGLE)",
      "HEADACHE ABNORMAL BREATHING",
      "HEART PROBLEMS/A.I.C.D CARDIAC HISTORY",
      "HEART PROBLEMS/A.I.C.D HEART RATE >50 OR 130",
      "HEART PROBLEMS/A.I.C.D UNKNOWN STATUS",
      "HEAT/COLD EXPOSURE NOT ALERT",
      "HEMORRHAGE/LACERATION - SERIOUS HEMORRHAGE",
      "HEMORRHAGE/LACERATIONS - NOT ALERT",
      "HEMORRHAGE/LACERATIONS - DANGEROUS HEMMORHAGE",
      "HEMORRHAGE/LACERATION BLOOD THINNERS",
      "HEMORRHAGE/LACERATION NOT DANGEROUS",
      "HEMORRHAGE/LACERATION POSSIBLY DANGEROUS",
      "HOUSE FIRE",
      "MEDICAL ALARM",
      "MEDICAL CALL NO INFO",
      "MISCELLANEOUS MEDICAL",
      "MISCELLANEOUS",
      "MISCELLANEOUS FIRE",
      "MOTOR VEHICLE COLLISION",
      "MOTOR VEHICLE COLLISION WITH PED",
      "MVC SERIOUS",
      "ODOR (STRANGE/UNKNOWN) ODOR INSIDE W SINGLE SICK PERSON",
      "OUTSIDE FIRE EXTINGUISHED",
      "OUTSIDE FIRE LARGE BRUSH/GRASS FIRE",
      "OUTSIDE FIRE SMALL BRUSH/GRASS FIRE",
      "OVERDOSE/POISONING NARCOTICS",
      "OVERDOSE/POISONING OVERDOSE",
      "OVERDOSE/POISONING UNCONSCIOUS",
      "OVERDOSE/POISONING UNKNOWN STATUS",
      "Paramount ProQA",
      "PATIENT WALKED INTO STATION",
      "POLICE ASK FOR FIRE",
      "POLICE ASK FOR MEDICAL",
      "PSYCHIATRIC/ABNORMAL BEHAVIOR/SUICIDE ATTEMPT NON SUICIDAL",
      "PSYCHIATRIC/ABNORMAL BEHAVIOR/SUICIDE ATTEMPT NOT ALERT",
      "SEIZURES - CONTINUOUS/MULTIPLE SEIZURES",
      "SEIZURES - DIABETIC",
      "SEIZURES - FOCAL/ABSENCE SEIZURE",
      "SEIZURES - FOCAL NOT ALERT",
      "SEIZURES - NOT SEIZING NOW BREATHING VERIFIED",
      "SEIZURES - NOT SEIZING NOW EFFEC BREATHING",
      "SICK PERSON - ALERTED LEVEL OF - CONFIRM 36",
      "SICK PERSON - DIZZINESS/VERTIGO",
      "SICK PERSON - FEVER/CHILLS",
      "SICK PERSON - GENERAL WEAKNESS",
      "SICK PERSON - GENERAL WEAKNESS - CONFIRM 36",
      "SICK PERSON - NAUSEA",
      "SICK PERSON - UNWELL/ILL",
      "SICK PERSON - VOMITING",
      "SICK PERSON 2-28 NON-PRIORITY COMPLAINTS",
      "SICK PERSON ALTERED LEVEL OF CONSCIOUSNESS",
      "SICK PERSON ABNORMAL BREATHING",
      "SICK PERSON NO PRIORITY SYMPTOMS",
      "SICK PERSON NOT ALERT",
      "SMOKE INVESTIGATION LIGHT SMOKE",
      "SMOKE INVESTIGATION ODOR OF SMOKE",
      "STROKE (CVA) - UNKNOWN STATUS",
      "STROKE (CVA) NOT ALERT",
      "STROKE (CVA) STROKE HISTORY",
      "STROKE (CVA) SUDDEN SPEACH PROBLEMS",
      "STRUCTURE FIRE APPLIANCE (CONTAINED)",
      "STRUCTURE FIRE CHIMNEY",
      "STRUCTURE FIRE COMMERCIAL/INDUSTRIAL",
      "STRUCTURE FIRE EXTINGUISHED FIRE",
      "STRUCTURE FIRE HIGH LIFE HAZARD",
      "STRUCTURE FIRE RESIDENTIAL (MULTIPLE)",
      "STRUCTURE FIRE RESIDENTIAL (SINGLE)",
      "STRUCTURE FIRE SMALL NON-DWELLING (SHED)",
      "TRAFFIC ACCIDENT PI",
      "TRAUMATIC INJURIES - NOT DANGEROUS AREA",
      "TRAUMATIC INJURIES SERIOUS HEMORRHAGE",
      "UNCONSCIOUS/FAINTING  EFFECTIVE BREATHING",
      "UNCONSCIOUS/FAINTING  UNCONSCIOUS AGONAL/INEFFECTIVE BREATHING",
      "UNCONSCIOUS/FAINTING ALERT W ABNORMAL BREATHING",
      "UNCONSCIOUS/FAINTING FAINTING EPISODE W ALERT >35 W CARDIAC HISTORY",
      "UNCONSCIOUS/FAINTING FAINTING EPISODE W ALERT >35 W/O CARDIAC HISTORY",
      "UNCONSCIOUS/FAINTING FAINTING EPISODE W ALERT 35 W/O CARDIAC HISTORY",
      "UNCONSCIOUS/FAINTING UNCONSCIOUS AGONAL/INEFFECTIVE BREATHING",
      "UNCONSCIOUS/FAINTING UNCONSCIOUS BREATHING EFFECTIVE",
      "VEHICLE FIRE",
      "VEHICLE FIRE THREATENED BUILDING/STRUCTURE",
      "WATER RESCUE A3"
  );

  private static final String[] CITY_LIST = new String[]{
      // Towns
      "EASTON",
      "OXFORD",
      "QUEEN ANNE",
      "SAINT MICHAELS",
      "ST MICHAELS",
      "TRAPPE",

      // Census-designated places
      "CORDOVA",
      "TILGHMAN ISLAND",

      // Unincorporated communities
      "BOZMAN",
      "CLAIBORNE",
      "FAIRBANKS",
      "MCDANIEL",
      "NEAVITT",
      "NEWCOMB",
      "ROYAL OAK",
      "SHERWOOD",
      "WITTMAN",
      "WINDY HILL",
      "WYE MILLS"
  };

}
