package net.anei.cadpage.parsers.WV;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.SmartAddressParser;
import net.anei.cadpage.parsers.MsgInfo.Data;

public class WVGreenbrierCountyParser extends SmartAddressParser {
  
  public WVGreenbrierCountyParser() {
    super(CITY_LIST, "GREENBRIER COUNTY", "WV");
    setFieldList("ID CALL ADDR APT CITY ST");
  }
  
  @Override
  public String getFilter() {
    return "greenbrier@pagingpts.com";
  }
  
  private static final Pattern MASTER = Pattern.compile("(\\d{10})([A-Z]+.*?)(?:[, ]+(WV)(?: +(\\d{5}))?)?");
  private static final Pattern CALL_ADDR_PTN = Pattern.compile("([A-Z]+)(\\d.*)");
  
  @Override
  protected boolean parseMsg(String subject, String body, Data data) {
    
    if (!subject.startsWith("CAD Autopage EventID:")) return false;
    
    Matcher match = MASTER.matcher(body);
    if (!match.matches()) return false;
    data.strCallId = match.group(1);
    String addr = match.group(2).trim();
    data.strState = getOptGroup(match.group(3));
    String zip = match.group(4);
    
    String call = CALL_LIST.getCode(addr);
    if (call != null) {
      data.strCall = call;
      addr = addr.substring(call.length()).trim();
    } else {
      match = CALL_ADDR_PTN.matcher(addr);
      if (!match.matches()) return false;
      data.strCall = match.group(1);
      addr = match.group(2);
    }
    
    parseAddress(StartType.START_ADDR, FLAG_ANCHOR_END, addr, data);
    if (data.strCity.length() == 0 && zip != null) data.strCity = zip;
    
    return true;
  }
  
  private static final CodeSet CALL_LIST = new CodeSet(
      "911ABN",
      "ABDMN",
      "ABDUC",
      "ABNVH",
      "ABUSE",
      "AIRCF",
      "ALLGY",
      "ALRBG",
      "ALRFR",
      "ALRHU",
      "ALRM",
      "ALRMD",
      "ALRPN",
      "AMBER",
      "AMPTN",
      "ANMCN",
      "APS",
      "ARREST",
      "ASLT",
      "ASTHM",
      "B/E",
      "BACK",
      "BATT",
      "BITE",
      "BLEED",
      "BOLO",
      "BOMB",
      "BP",
      "BRDIF",
      "BURG",
      "BURN",
      "CABLE",
      "CBMNX",
      "CHBRT",
      "CHF",
      "CHOKE",
      "CHSPN",
      "CI",
      "CIRC",
      "CIVIL",
      "CLOT",
      "CPRAD",
      "CPRCH",
      "CPRTC",
      "CPS",
      "CRDC",
      "CUSDS",
      "DHYDR",
      "DIABT",
      "DIZZY",
      "DMSTC",
      "DNRLW",
      "DNRWL",
      "DOA",
      "DOG",
      "DRGAC",
      "DROWN",
      "DRVWO",
      "DSBVH",
      "DSLC",
      "DSTB",
      "DSTPRP",
      "DUI",
      "DVPRQ",
      "DVPVL",
      "ELCUT",
      "ENVIR",
      "ESCPE",
      "ESCRT",
      "EVAC",
      "EVAL",
      "EXPSUR",
      "EXTRC",
      "EYE",
      "FALL",
      "FIGHT",
      "FIRARSN",
      "FIRBRU",
      "FIRELCT",
      "FIRFLUE",
      "FIRRKND",
      "FIRSTRCT",
      "FIRUNK",
      "FIRVHCL",
      "FLOOD",
      "FLWUP",
      "FOBJCT",
      "FOUND",
      "FRAUD",
      "FRBRK",
      "FRGRY",
      "FVR",
      "GAS",
      "GNRTR",
      "GSDRV",
      "GSW",
      "HEAD",
      "HMCDE",
      "HMCON",
      "HRASS",
      "HSTAG",
      "HTRN",
      "HUMAN",
      "HZCND",
      "HZMAT",
      "ILBRN",
      "ILDRV",
      "ILL",
      "INFCT",
      "INTOX",
      "JUVNL",
      "LAC",
      "LARC",
      "LETH",
      "LFAST",
      "LOST",
      "LPR",
      "LTTR",
      "LVSTCK",
      "LZ",
      "MAG",
      "MDAST",
      "MEDEX",
      "MINE",
      "MNTHG",
      "MNTL",
      "MOCK",
      "MSSNG",
      "MUTAID",
      "MVA",
      "NAUSEA",
      "NCIC",
      "NUMB",
      "OBGYN",
      "OBSTC",
      "OD",
      "OFAST",
      "OI",
      "PAIN",
      "PAPSE",
      "PHONE",
      "PNEUM",
      "POISN",
      "POSS",
      "POWER",
      "PRBVIO",
      "PRSUT",
      "PRWL",
      "PS",
      "PTRL",
      "RABIES",
      "RADIO",
      "RAIL",
      "RASH",
      "RBBRY",
      "RCKLS",
      "RDOBS",
      "RECOV",
      "REPO",
      "RESCUE",
      "RNWY",
      "SHPLF",
      "SHTFR",
      "SLVR",
      "SMOKE",
      "SOLIC",
      "SOS",
      "SRVC",
      "STAB",
      "STDBY",
      "STRKE",
      "SUCAT",
      "SUICD",
      "SUSPC",
      "SWELL",
      "SXASL",
      "SYNCP",
      "SZR",
      "TCHRES",
      "TEST",
      "THEFT",
      "THRT",
      "TOW",
      "TOWER",
      "TRAIN",
      "TRAUM",
      "TRFCN",
      "TRSPS",
      "TX",
      "UNCNS",
      "UNK",
      "UNRSP",
      "UOF",
      "URINE",
      "VNDL",
      "VOMIT",
      "VRBL",
      "WATER",
      "WEAK",
      "WLBNG",
      "WNTD",
      "WRNT"
  );

  private static final String[] CITY_LIST = new String[]{
    "ALDERSON",
    "ALTA",
    "ALVON",
    "ANJEAN",
    "ANTHONY",
    "ASBURY",
    "AUTO",
    "BELLBURN",
    "BEND",
    "BINGHAM",
    "BLAKER",
    "BLUE",
    "BLUE",
    "BOWES",
    "BRANTVILLE",
    "BURDETTE",
    "CALDWELL",
    "CALDWELL",
    "CAVE",
    "CHARMCO",
    "CLEARCO",
    "CLENDENENVILLE",
    "CLINTONVILLE",
    "COBB",
    "CORDOVA",
    "CORNSTALK",
    "CRAG",
    "CRAWLEY",
    "CRICHTON",
    "DAWSON",
    "DENNIS",
    "DICKSON",
    "DROOP MOUNTAIN",
    "DUO",
    "ESTY",
    "FAIRLEA",
    "FALLING SPRING",
    "FARMDALE",
    "FORT DONNALLY",
    "FORT SPRING",
    "FRANKFORD",
    "FRAZIER",
    "FRIARS HILL",
    "GARDNER",
    "GOLDEN",
    "GRASSY MEADOWS",
    "HALF WAY",
    "HENNING",
    "HICKORY GROVE",
    "HILL",
    "HINES",
    "HOKES MILL",
    "HOPPER",
    "HORROCK",
    "HUGHART",
    "JULIA",
    "KEISTER",
    "KESSLER",
    "KIEFFER",
    "LAWN",
    "LEONARD",
    "LESLIE",
    "LEWISBURG",
    "LILE",
    "LILLY PARK",
    "LOOPEMOUNT",
    "LOVERIDGE",
    "MAPLEDALE",
    "MARFRANCE",
    "MAXWELTON",
    "MCROSS",
    "MEADOW BLUFF",
    "MILLS",
    "MODOC",
    "MORLUNDA",
    "NEOLA",
    "NORTH",
    "NORTH BEND",
    "NUTTERVILLE",
    "ORGAN",
    "ORIENT",
    "OSCAR",
    "PALESTINE",
    "PATTON",
    "PIERCYS MILL",
    "QUINWOOD",
    "RAINELLE",
    "RENICKS VALLEY",
    "RICHLANDS",
    "ROCK CLIFF",
    "ROCKLAND",
    "RONCEVERTE",
    "RORER",
    "RUPERT",
    "SAM BLACK CHURCH",
    "SHAWVER",
    "SHAWVERS CROSSING",
    "SHRYOCK",
    "SIMS",
    "SMOOT",
    "SNOWFLAKE",
    "SPRING CREEK",
    "SPRINGS",
    "SUE",
    "SULPHUR",
    "SUNLIGHT",
    "TEABERRY",
    "TRAINER",
    "TROUT",
    "TUCKAHOE",
    "UNUS",
    "VAGO",
    "VALE",
    "WHITE SULPHUR SPRINGS",
    "WHITEOAK GROVE",
    "WILD MEADOW",
    "WILLIAMSBURG",
    "WOODMAN"
  };
}
