package net.anei.cadpage.parsers.WV;

import java.util.Properties;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA48Parser;

/**
 * Preston County, WV
 */
public class WVPrestonCountyParser extends DispatchA48Parser {
  
  public WVPrestonCountyParser() {
    super(CITY_LIST, "PRESTON COUNTY", "WV", FieldType.NAME, A48_ONE_WORD_CODE,
          Pattern.compile("\\d{1,3}[A-Z]?|NRP\\d+|PD\\d+"), CALL_CODES);
  }
  
  @Override
  public String getFilter() {
    return "Preston911@preston911.com";
  }
  
  @Override
  protected boolean parseMsg(String subject, String body, Data data) {
    if (!super.parseMsg(subject, body, data)) return false;
    int pt = data.strCall.indexOf('/');
    if (pt >= 0) {
      data.strPriority = data.strCall.substring(0,pt).trim();
      data.strCall = data.strCall.substring(pt+1).trim();
    }
    return true;
  }
  
  @Override
  public String getProgram() {
    return super.getProgram().replace("CALL", "PRI CALL");
  }

  private static final Properties CALL_CODES = buildCodeTable(new String[]{
      "ABDU",   "1/ABDUCTION",
      "ABUS",   "1/ABUSE",
      "ACCI",   "1/ACCIDENT",
      "ACFA",   "1/ACCIDENT - FATALITY",
      "ACIN",   "1/ACCIDENT - INJURY",
      "ACSH",   "1/ACTIVE SHOOTER /ASSAILANT",
      "AIDO",   "1/AIRCRAFT DOWN",
      "AIEM",   "1/AIRCRAFT EMERGENCY",
      "ALCODU", "1/ALARM COUNTY PANIC OR DURESS",
      "ALRE",   "1/ALLERGIC REACTION",
      "ALTR",   "1/ALS INTERF TRAN",
      "ANBI",   "1/ANIMAL BITE",
      "ARRO",   "1/ARMED ROBBERY",
      "ASAG",   "1/ASST",
      "ASAM",   "1/ASST EMS",
      "ASFD",   "1/ASST FD",
      "ASPD",   "1/ASST PD",
      "ATRO",   "1/ATTEMPTED ROBBERY",
      "BAPA",   "1/BACK PAIN",
      "BATT",   "1/BATTERY",
      "BLEE",   "1/BLEEDING",
      "BLTR",   "1/BLS INTERFACILITY TRANSFER",
      "BOAC",   "1/BOATING ACCIDENT",
      "BOLO",   "1/ATTENTION ALLUNITS",
      "BOMB",   "1/BOMB THREAT",
      "BRAN",   "1/BRANDISHING",
      "BRDI",   "1/BREATHING DIFF",
      "BREN",   "1/BREAKING AND ENTERING",
      "BRFI",   "1/BRUSH FIRE",
      "BUAL",   "1/BURGLAR ALARM",
      "BURN",   "1/BURN",
      "CAAR",   "1/CARDIAC ARREST",
      "CAJA",   "1/CAR JACKING",
      "CHAB",   "1/CHILD ABUSE",
      "CHOK",   "1/CHOKING",
      "CHPA",   "1/CHEST PAIN/HEART PR",
      "CHSP",   "1/CHEMICAL SPILL",
      "CO",     "1/CO2",
      "COPO",   "1/CO POISONING",
      "CUDI",   "1/CUSTODY DISPUTE",
      "CVA",    "1/STROKE",
      "DEPR",   "1/DESTRUCTION OF PROPERTY",
      "DIAB",   "1/DIABETIC",
      "DIST",   "1/DISTURBANCE",
      "DOME",   "1/DOMESTIC",
      "DROW",   "1/DROWNING",
      "DUEM",   "1/COUNTY DURESS/EMERGENCY",
      "DUI",    "1/DRIVING UNDERTHE INFLUENCE",
      "EMER",   "1/1 ENEM ENVIRONMENTAL EMERGENCY",
      "EXPL",   "1/EXPLOSION",
      "FALL",   "1/FALL",
      "FIAL",   "1/FIRE ALARM",
      "FIGH",   "1/FIGHT",
      "FLFI",   "1/FLUE FIRE",
      "FLOO",   "1/FLOODING",
      "FLST",   "1/FLOODED STRUCTURE",
      "FOFI",   "1/FOREST FIRE",
      "FOPE",   "1/FOUND PERSON",
      "FORG",   "1/FORGERY",
      "FRAU",   "1/FRAUD",
      "FUGI",   "1/FUGITIVE",
      "FUSP",   "1/FUEL SPILL",
      "GALE",   "1/GAS LEAK",
      "GAVI",   "1/GAME VIOLATION",
      "GYNE",   "1/GYNECOLOGY/MISCARRIAGE",
      "HAMA",   "1/HAZARDOUS MATERIALS",
      "HEAD",   "1/HEADACHE",
      "HEIN",   "1/HEAD INJURY",
      "HIRU",   "1/HIT AND RUN",
      "HIRUFA", "1/HIT AND RUN WITH FATALITY",
      "HIRUIN", "1/HIT AND RUN WITH INJURIES",
      "HOAL",   "1/HOLD UP ALARM",
      "HOCOVI", "1/HOME CONFINEMENT VIOLATION",
      "HOIN",   "1/HOME INVASION",
      "HOMI",   "1/HOMICIDE",
      "HOST",   "1/HOSTAGE",
      "ILBU",   "1/ILLEGAL BURN",
      "IMOF",   "1/IMPERSONATINGAN OFFICER",
      "INEX",   "1/INDECENT EXPOSURE",
      "K9DE",   "1/K9 DETAIL",
      "KIDN",   "1/KIDNAPPING",
      "LARC",   "1/LARCENY",
      "MEAL",   "1/MEDICAL ALARM",
      "MEAS",   "1/MEDIC ASSIST",
      "MIPE",   "1/MISSING PERSON",
      "MOAS",   "1/MOTORIST ASSIST",
      "ODIN",   "1/ODOR INVESTIGATION",
      "OFAS",   "1/OFFICER ASSISTANCE",
      "OPLI",   "1/OPEN LINE",
      "OVER",   "1/OVERDOSE/POISONING",
      "PAAL",   "1/PANIC ALARM",
      "PI",     "1/PERSONAL INJURY ACCIDENT",
      "POSTPR", "1/POSSESSION OFSTOLEN GOODS",
      "PREG",   "1/PREGNANCY/CHILDBIRTH",
      "PRLE",   "1/PROPANE LEAK",
      "PSYC",   "1/PSYCHIATRIC",
      "REDR",   "1/RECKLESS DRIVER",
      "REKI",   "1/RE-KINDLE",
      "RESTPR", "1/RECOVERING STOLEN PROPERTY",
      "ROBB",   "1/ROBBERY",
      "ROHA",   "1/ROAD HAZARD",
      "RUJU",   "1/RUNAWAY JUVENILE",
      "SCAM",   "1/SCAM",
      "SEAR",   "1/SEARCH",
      "SEAS",   "1/SEXUAL ASSAULT",
      "SEIZ",   "1/SEIZURE",
      "SELZ",   "1/SET UP LANDING ZONE",
      "SHFI",   "1/SHOTS FIRED",
      "SHOO",   "1/SHOOTING",
      "SHOP",   "1/SHOP LIFTING",
      "SIG5",   "1/OFFICER NEEDSASSISTANCE - EMERGENCY",
      "SIPE",   "1/SICK PERSON",
      "SMIN",   "1/SMOKE INVEST",
      "STARAS", "1/STRONG ARM ASSAULT",
      "STCO",   "1/STRUCTURE COLLAPSE",
      "STFI",   "1/STRUCTURE FIRE",
      "STFIEX", "1/STRUCTURE FIRE W/EX",
      "STFIFA", "1/STRUCTURE FIRE WITH FATALITY",
      "STVE",   "1/STOLEN VEHICLE",
      "SUAT",   "1/SUICIDE ATT",
      "SUEV",   "1/SUSPICIOUS EVENT",
      "SUIC",   "1/SUICIDE",
      "SUPE",   "1/SUSPICIOUS PERSON",
      "SUTH",   "1/SUICIDE THREAT",
      "THIN",   "1/THERMAL INVERSION",
      "TP",     "1/TRAFFIC PURSUIT",
      "TRAR",   "1/TRAUMATIC ARREST",
      "TRCOMP", "1/TRAFFIC COMPLAINT",
      "TRDE",   "1/TRAFFIC DETAIL",
      "TRDO",   "1/TREE DOWN",
      "TRES",   "1/TRESPASSING",
      "TRIN",   "1/TRAUMATIC INJURY",
      "TS",     "1/TRAFFIC STOP",
      "UNCO",   "1/UNCONSCIOUS",
      "UNDE",   "1/UNATTENDED DEATH",
      "UNDR",   "1/UNDERAGE DRINKING",
      "UNPO",   "1/UNDERAGE POSSESSION",
      "UNPR",   "1/UNK MED /SICKPERSON",
      "VAND",   "1/VANDALISM",
      "VEAC",   "1/VEHICLE ACCIDENT",
      "VEACFA", "1/VEHICLE ACCIDENT W/FATALITY",
      "VEACIN", "1/VEHICLE ACCIDENT WITH INJURY",
      "VEAN",   "1/VEHICLE VS ANIMAL",
      "VEFI",   "1/VEHICLE FIRE",
      "VEPE",   "1/VEHICLE VS PEDESTRIAN",
      "WARE",   "1/WATER RESCUE",
      "WEOF",   "1/WEAPON OFFENSE",
      "WIDO",   "1/WIRE DOWN",
      "ABCA",   "2/ABANDONED CALL - 911",
      "ABPA",   "2/ABDOM PAIN",
      "ADDE",   "2/ADMIN DETAIL",
      "ALAR",   "2/ALARM",
      "ALMEST", "2/ALT MENTAL",
      "ASSA",   "2/ASSAULT",
      "BURG",   "2/BURGLARY",
      "FICO",   "2/FIREWORKS COMPLAINT",
      "HACA",   "2/HANG UP - 911",
      "HARA",   "2/HARASSMENT",
      "HOCO",   "2/HOME CONFINEMENT",
      "HUCO",   "2/HUMANE COMPLAINT",
      "MIFI",   "2/MISCELLANEOUSFIRE",
      "PASE",   "2/PAPER SERVICE",
      "PRORVI", "2/PROTECTIVE ORDER VIOLATION",
      "PUIN",   "2/PUBLIC INTOXICATION",
      "SEWA",   "2/2 STPL STOLENPLATE",
      "SUVE",   "2/SUSPICIOUS VEHICLE",
      "THRE",   "2/THREATS",
      "WALK",   "2/WALK A WAY",
      "WASE",   "2/WARRANT SERVICE",
      "WEAL",   "2/2 WECH WELFARE CHECK",
      "ABVE",   "3/ABANDONED VEHICLE",
      "ADNO",   "3/ADMIN NOTIFICATION",
      "ANCO",   "3/ANIMAL COMPLAINT",
      "ATVE",   "3/ALL TERRAIN VEHICLE COMPLAINT",
      "BLNOTR", "3/BLS NON-EM TRANS",
      "CICO",   "3/CIVIL COMPLAINT",
      "CONT",   "3/CONTRIBUTING TO DELINQUENCY",
      "DRCO",   "3/DRUG COMPLAINT",
      "FOPU",   "3/FOOT PURSUIT",
      "FOUP",   "3/FOLLOW UP",
      "GOIN",   "3/GOOD INTENT",
      "JOYR",   "3/JOYRIDING",
      "LITT",   "3/LITTER",
      "MIPO",   "3/MISC POLICE",
      "OBT",    "3/ONE BUTTON TRANSFER",
      "PROR",   "3/PROTECTIVE ORDER",
      "REOR",   "3/REVOCATION ORDER",
      "RETOLE", "3/REFUSAL TO LEAVE",
      "STAL",   "3/STALKING",
      "TAOF",   "3/TALK WITH OFFICER",
      "TRCO",   "3/TRAFFIC CONTROL",
      "ADMI",   "4/ADMIN NOTIFICATION",
      "ASPE",   "4/ASSIST PERSON",
      "DEME",   "4/DELIVER MESSAGE",
      "DETA",   "4/SPECIAL DETAIL",
      "DUPL",   "4/DUPLICATE CALL",
      "INRE",   "4/INFORMATION REPORT",
      "MEHY",   "4/MENTAL HYGIENE",
      "NOCO",   "4/NOISE COMPLAINT",
      "NOEM",   "4/NON-EMERGENCY911",
      "PUSE",   "4/PUBLIC SERVICE",
      "REPO",   "4/REPOSSESSION",
      "STAN",   "4/STAND BY",
      "TRANP",  "4/TRANSPORT POLICE",
      "WROC",   "4/WRONGFUL OCCUPATION",
      "PACO",   "5/PARKING COMPLAINT",
      "WECO",   "5/WEAPONS COMPLAINT",
      "RAAS",   "6/RADAR ASSIGNMENT",
      "TRAI",   "6/TRAINING",
      "ARRA",   "7/ARRAIGNMENT",
      "FUES",   "7/FUNERAL ESCORT",
      "SERE",   "7/SEX OFFENDER REGISTER",
      "GADR",   "8/GAS DRIVE OFF",
      "VEMA",   "8/VEHICLE MAINTENANCE",
      "BUSY",   "9/BUSY",
      "DIDR",   "9/DISASTER DRILL",
      "LODO",   "9/LOST DOG",
      "TRANE",  "9/TRANSPORT EMS",
      "AREA",   "10/PATROL AREA PATROL",
      "FODO",   "10/FOUND DOG",
      "UTIL",   "10/WATER/SEWER/POWER/PHONE/CABLE",
      "ARPA",   "11/AREA PATROL",
      "CODE",   "11/COURT DETAIL",
      "PEDE",   "11/PERSONAL DETAIL",
      "SPDE",   "11/SPECIAL DETAIL",
      "OAA",    "12/ON THE AIR AVAILABLE",
      "ANNO",   "13/SCHEDULE ANNOUNCEMENT",
      "VIVE",   "13/VIN VERIFICATION",
  });
  
  private static final String[] CITY_LIST = new String[]{
    
    //Cities and towns
    "ALBRIGHT",
    "BRANDONVILLE",
    "BRUCETON MILLS",
    "KINGWOOD",
    "MASONTOWN",
    "NEWBURG",
    "REEDSVILLE",
    "ROWLESBURG",
    "TERRA ALTA",
    "TUNNELTON",

    // Unincorporated communities
    "AFTON",
    "ALPINE LAKE",
    "AMBOY",
    "ARTHURDALE",
    "AURORA",
    "AUSTEN",
    "BORGMAN",
    "BRETZ",
    "BULL RUN",
    "CASCADE",
    "CLIFTON MILLS",
    "COLEBANK",
    "CORINTH",
    "CUZZART",
    "DENVER",
    "EGLON",
    "ETAM",
    "EVANSVILLE",
    "FELLOWSVILLE",
    "GLADEFARMS",
    "HAZELTON",
    "HOPEMONT",
    "HOPEWELL",
    "HORSE SHOE RUN",
    "HOWESVILLE",
    "INDEPENDENCE",
    "ISRAEL",
    "LENOX",
    "LITTLE SANDY",
    "MANHEIM",
    "MACOMBER",
    "MANOWN",
    "MARQUESS",
    "MOUNT OLIVET",
    "MOUNT VERNON",
    "ORR",
    "PISGAH",
    "PLEASANTDALE",
    "PRESTON",
    "ROCKVILLE",
    "RODEMER",
    "ROHR",
    "RUTHBELLE",
    "SAINT JOE",
    "SCOTCH HILL",
    "SELL",
    "SILVER LAKE",
    "SINCLAIR",
    "SNIDER",
    "STEVENSBURG",
    "SUGAR VALLEY",
    "THREEFORK BRIDGE",
    "TURNER DOUGLASS",
    "VALLEY POINT",
    "VICTORIA",
    "WEST END",
    "WHITE OAK SPRINGS",
    "ZEVELY",
    
    // Taylor County
    "THORNTON"
  };
}
