package net.anei.cadpage.parsers.WV;


import java.util.Properties;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchB2Parser;


public class WVRaleighCountyParser extends DispatchB2Parser {
  
  public WVRaleighCountyParser() {
    super(CITY_LIST, "RALEIGH COUNTY", "WV", B2_FORCE_CALL_CODE);
    setupCallList(CALL_LIST);
    removeWords("BV", "LANE", "TURNPIKE");
    setupDoctorNames("KELLY");
    setupSaintNames("JOHN");
    setupProtectedNames("L C AND WILDAS");
    setupMultiWordStreets(MWORD_STREET_LIST);
  }
  
  private boolean confirmed;

  @Override
  protected boolean parseMsg(String body, Data data) {
    confirmed = body.startsWith("RALEIGH911:") || body.startsWith("911-CENTER:");
    if (confirmed) body = body.substring(11);
    body = body.replace("L C & WILDAS", "L C AND WILDAS");
    if (!super.parseMsg(body, data)) return false;
    if (data.strCity.endsWith(" CO")) data.strCity += "UNTY";
    return true;
  }
  
  @Override
  public String getProgram() {
    return "PHONE? " + super.getProgram();
  }
  
  @Override
  protected boolean isPageMsg(String body) {
    if (confirmed) return true;
    return super.isPageMsg(body);
  }

  @Override
  protected int getExtraParseAddressFlags() {
    return FLAG_IGNORE_AT;
  }
  
  @Override
  public boolean isValidAddress(String addr) {
    // FMnnn is a valid highway in some states, but not here
    if (addr.startsWith("FM")) return false;
    return super.isValidAddress(addr);
  }

  @Override
  public String adjustMapCity(String city) {
    return convertCodes(city, CITY_PLACE_NAMES);
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
    "4-H LAKE",
    "ACORD MOUNTAIN",
    "AFFINITY COMPLEX",
    "APPALACHIAN HEIGHTS",
    "BARKERS RIDGE-SAND GAP",
    "BEE BRANCH",
    "BLUE JAY SIX",
    "BLUE ROOM",
    "BOB VINES",
    "BOYD CRAWFORD",
    "BURNING ROCK",
    "C AND O DAM",
    "CABELL HEIGHTS",
    "CARL VEST",
    "CHERRY CREEK",
    "CLAY FARM",
    "CLEAR CREEK",
    "CLEAR FORK",
    "CLEVELAND SCHOOL",
    "COAL CITY",
    "COAL RIVER",
    "COUNTRY ROADS",
    "CRAB ORCHARD",
    "D C LILLY",
    "DAVIS CEMETERY",
    "DEVILS FORK",
    "DRY HILL",
    "ELLISON RIDGE",
    "FARLEY BRANCH",
    "FIRE TRAIL",
    "FLAT TOP MOUNTAIN",
    "FLAT TOP MTN",
    "FLAT TOP",
    "FLOYD WORLEY",
    "GLADE CREEK",
    "GLEN GARDEN",
    "GLEN ROGERS-RAVENCLIFF",
    "GREY FLATS",
    "HARPER HEIGHTS",
    "HARPER PARK",
    "HOLLY HILL",
    "HOO HOO",
    "HORSE CREEK",
    "HOT COAL",
    "INDUSTRIAL PARK",
    "IRISH MOUNTAIN",
    "JIM BAILEY FARM",
    "JOHN LANE",
    "JONBEN FIRECO",
    "LAKE STEPHENS",
    "LITTLE BEAVER STATE PARK",
    "MAPLE FORK",
    "MAPLE MEADOW MINING",
    "MAPLE VIEW",
    "MAXWELL HILL",
    "MCKINNEY MOUNTAIN",
    "MCKINNEY MTN",
    "MILL BRANCH",
    "MILL CREEK",
    "MONT PHILLIPS",
    "MOUNTAIN VIEW",
    "MOUNTAIN WILLIAM",
    "MT BREEZE",
    "MT TABOR",
    "MT VIEW BOTTOM",
    "MT VIEW",
    "OAK CREEK",
    "OAK GROVE",
    "ORCHARD HILL",
    "RALEIGH RIDGE",
    "ROBERT C BYRD",
    "ROCK CREEK",
    "ROLLING CREEK",
    "RURAL ACRES",
    "RUSTIC HILLS",
    "SAND BRANCH",
    "SAXON BOLT",
    "SCOTT RIDGE",
    "SHADY LAKE",
    "SLAB FORK",
    "SNUFFER MOUNTAIN",
    "SNUFFER MTN",
    "SOUTHERN INDUSTRIAL",
    "STEPHENS BRANCH",
    "TABLE ROCK",
    "TANK BRANCH",
    "TAYLOR FARM",
    "TOLBERT FARM",
    "TOMMY CREEK",
    "TWIN OAKS",
    "URY POWELL",
    "VALLEY VIEW",
    "WEST VIRGINIA",
    "WHITE OAK CREEK",
    "WILCOX VALLEY"
  };
  
  private static final CodeSet CALL_LIST = new CodeSet(
      "911 HANGUP",
      "ABANDONED VEHICLE",
      "ABDOMINAL PAIN",
      "ABDUCTION",
      "ABNORMALLY DROWSY/LOW TO REACT",
      "ACCIDENT WITH INJURIES",
      "ACCIDENT WITHOUT INJURY",
      "AIRCRAFT DISTRUBANCE",
      "ALARM-HOLDUP",
      "ALARM(SPECIFY)",
      "ALLERGIC REACTION",
      "ALS BACKUP",
      "ANIMAL BITES",
      "ANIMAL PROBLEM",
      "ARMED ROBBERY",
      "ARSON FIRE",
      "ASSAULT",
      "ASSIST OTHER DEPT",
      "ASSULT WITH INJURY",
      "ATTEMPTED SUICIDE",
      "B&E IN PROGRESS",
      "BACK PAIN",
      "BLEEDING/NON-TRAUMAT",
      "BREATHING DIFFICULTY",
      "BRUSH FIRE",
      "BURGLARY IN PROGRESS",
      "BURNS",
      "CARDIAC (NS)",
      "CHECK WELFARE",
      "CHEMICAL LEAK",
      "CHEST PAIN",
      "CHILD BIRTH",
      "CHIMNEY FIRE",
      "CHOKING",
      "CIVIL ASSIST",
      "CONGESTIVE HEART FAILURE",
      "CPR-ADULT",
      "CPR-INFANT",
      "DAMAGE FROM STORM",
      "DEAD BODY",
      "DECEASED PERSON/FOUND BODY",
      "DIABETIC",
      "DISORIENTED",
      "DISTURBANCE",
      "DOMESTIC",
      "EDEMA/SWELLING",
      "EOC PROJECT",
      "ELECTRICAL FIRE",
      "ELEVATOR RESCUES",
      "EMPLOYEE CALL IN SICK",
      "EXERCISE",
      "EXPLOSION",
      "EYE INJURY",
      "FALLS",
      "FIGHT-IN PROGRESS",
      "FIRE",
      "FIRE ALARM",
      "FRACTURE-BONE",
      "GAS LEAK",
      "HAZMAT",
      "HEAD INJURY",
      "HEALTHNET LANDING",
      "HEART ATTACK",
      "ILLEGAL BURN",
      "INTOX PERSON",
      "LACERATION/CUT",
      "LIFTING ASSISTANCE",
      "LINES DOWN",
      "MEDICAL ALARM",
      "MENTAL/EMOTIONAL/PS",
      "MINING ACCIDENT",
      "MISSING PERSON",
      "MOTOR VEH ACCID PRIVATE LOT",
      "MOTOR VEHICLE ACCIDENT",
      "MOTOR VEHICLE ACCIDENT INJURY",
      "MVA LEAVING THE SCENE",
      "NOSE BLEED",
      "OUT OF CONTROL",
      "OVERDOSE",
      "PAGER TEST",
      "PANIC ATTACK",
      "PEDSTRIAN HIT",
      "PERSON DOWN",
      "PLANE CRASH",
      "PLANE MALFUNCTION",
      "POISONING",
      "POSSIBLE DUI",
      "PREGNANCY/CHILDBIRTH",
      "PURSUIT",
      "RECKLESS DRIVER",
      "REKINDLE",
      "RESIDENCE CHECK",
      "RESIDENTIAL/ COMMERCIAL ALARM",
      "ROAD HAZZARD",
      "ROBBERY OCCURED EARLIER",
      "ROCK SLIDE",
      "RUNAWAY JUV",
      "RUN REPORT",
      "SEARCH-LOST PERSON",
      "SEIZURES",
      "SEXUAL ASSAULT NOT IN PROGRESS",
      "SHOOTING",
      "SHOPLIFTING",
      "SHOTS FIRE",
      "SICK",
      "SITEOK",
      "SITETR",
      "SHOTS FIRED",
      "SMOKE",
      "SPECIAL ASSIGNMENT",
      "SPECIFY -(I.E. -ARM/LEG)",
      "SPECIFY-RUN OFF/HIGH",
      "STOLEN VEHICLE",
      "STROKE",
      "STRUCTURE FIRE",
      "SUSPICIOUS ACTIVITY",
      "SUSPICIOUS PACKAGE",
      "SUSPICIOUS PERSON",
      "TEST CALL",
      "TRAFFIC STOP",
      "TRANSFORMER",
      "TREE DOWN",
      "UNCONSCIOUS/SYNCOPE",
      "UNKNOWN MEDICAL PROBLEM",
      "UNRESPONSIVE",
      "VEHICLE- DISABLED",
      "VEHICLE FIRE",
      "WANTED PERSON"
  );
  
  private static final String[] CITY_LIST = new String[]{

    // Cities & Towns
    "BECKLEY",
    "LESTER",
    "MABSCOTT",
    "RHODELL",
    "SOPHIA",
    
    // Subdivisions
    "CALLOWAY HEIGHTS",

    // Unincorporated communities
    "ABNEY",
    "ABRAHAM",
    "AFFINITY",
    "ALS BACKUP",
    "AMIGO",
    "AMEAGLE",
    "ARNETT",
    "ARTIE",
    "BEAVER",
    "BESOCO",
    "BIG STICK",
    "BLUE JAY",
    "BLUE JAY 6",
    "BOLT",
    "BOWYER",
    "BRADLEY",
    "BRAGG",
    "CABELL HEIGHTS",
    "CEDAR",
    "CIRTSVILLE",
    "CLEAR CREEK",
    "COAL CITY",
    "COLCORD",
    "COOL RIDGE",
    "CRAB ORCHARD",
    "CRANBERRY",
    "CROW",
    "DAMERON",
    "DANIELS",
    "DOROTHY",
    "DRY CREEK",
    "DRY HILL",
    "EASTGULF",
    "EAST GULF",
    "ECCLES",
    "EGERIA",
    "EUNICE",
    "FAIRDALE",
    "FARLEY HILL",
    "FIRECO",
    "FITZPATRICK",
    "FLAT TOP",
    "GHENT",
    "GLEN DANIEL",
    "GLEN MORGAN",
    "GLEN VIEW",
    "GLEN WHITE",
    "GRANDVIEW",
    "HELEN",
    "HOLLYWOOD",
    "HOT COAL",
    "HOTCHKISS",
    "IRISH MOUNTAIN",
    "IRISH MTN",
    "JONBEN",
    "JOSEPHINE",
    "HARPER",
    "HARPER HEIGHTS",
    "HARPER PARK",
    "KILLARNEY",
    "LEEVALE",
    "LEGO",
    "LANARK",
    "LILLYBROOK",
    "MABSCOTT",
    "MACARTHUR",
    "MAPLE FORK",
    "MCALPIN",
    "MCCREERY",
    "MCREERY",
    "MCVEY",
    "MEAD",
    "METALTON",
    "MIDWAY",
    "MONTCOAL",
    "MT TABOR",
    "NAOMA",
    "NEW",
    "OAK GROVE",
    "ODD",
    "PACKSVILLE",
    "PEMBERTON",
    "PICKSHIN",
    "PINEPOCA",
    "PINEY VIEW",
    "PLEASANT HILLS",
    "PLUTO",
    "PRICE HILL",
    "PRINCEWICK",
    "PROSPERITY",
    "RALEIGH",
    "REDBIRD",
    "ROCK CREEK",
    "SANDLICK",
    "SHADY SPRING",
    "SHILOH",
    "SITEOK",
    "SITETR",
    "SKELTON",
    "SLAB FORK",
    "SOAK CREEK",
    "SOPHIA",
    "SPRAGUE",
    "STANAFORD",
    "STICKNEY",
    "STOTESBURY",
    "STOVER",
    "SULLIVAN",
    "SUNDIAL",
    "SURVEYOR",
    "SWEENEYSBURG",
    "SYLVIA",
    "TAMS",
    "TOLLEYTOWN",
    "URY",
    "WESTVIEW",
    "WHITBY",
    "WHITE OAK",
    "WICKHAM",
    "WILLIBET",
    "WINDING GULF",
    "WOODPECK",
    
    // Boone County
    "BOONE",
    "BOONE CO",
    "BOONE COUNTY",
    "WHITESVILLE",
    
    // Summers County
    "SUMMERS",
    "SUMMERS CO",
    "SUMMERS COUNTY",
    
    // Wyoming county
    "WYOMING",
    "WYOMING CO",
    "WYOMING COUNTY"
  };
  
  private static final Properties CITY_PLACE_NAMES = buildCodeTable(new String[]{
      "CABELL HEIGHTS",     "BECKLEY",
      "CALLOWAY HEIGHTS",   "BECKLEY",
      "CRANBERRY",          "BECKLEY",
      "DAMERON",            "",
      "DRY HILL",           "BECKLEY",
      "EUNICE",             "WHITESVILLE",
      "FARLEY HILL",        "PRINCEWICK",
      "GLEN VIEW",          "CRAB ORCHARD",
      "HARPER",             "BECKLEY",
      "HARPER HEIGHTS",     "BECKLEY",
      "HARPER PARK",        "BECKLEY",
      "LEEVALE",            "WHITESVILLE",
      "MAPLE FORK",         "MT HOPE",
      "MCCREERY",           "BECKLEY",
      "MCREERY",            "BECKLEY",
      "METALTON",           "BECKLEY",
      "MT TABOR",           "BECKLEY",
      "OAK GROVE",          "BECKLEY",
      "PACKSVILLE",         "",
      "PLEASANT HILLS",     "BECKLEY",
      "SANDLICK",           "BECKLEY",
      "STOVER",             "GLEN DANIEL",
      "TOLLEYTOWN",         "SURVEYOR"
  });
}