package net.anei.cadpage.parsers.VA;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.MsgInfo.MsgType;
import net.anei.cadpage.parsers.dispatch.DispatchSouthernParser;

/**
 * Franklin County, VA
 */
public class VAFranklinCountyBParser extends DispatchSouthernParser {
  
  public VAFranklinCountyBParser() {
    super(CITY_LIST, "FRANKLIN COUNTY", "VA",
        DSFLG_ADDR|DSFLG_ADDR_LEAD_PLACE|DSFLG_ADDR_TRAIL_PLACE|DSFLG_OPT_X|DSFLG_OPT_CODE|DSFLG_OPT_UNIT1|DSFLG_ID|DSFLG_TIME,
        "(?:CO|DP|SQ|M)\\d+[A-Z]?|(?:ATTACK|BRUSH|CRASH|ENGINE|MED|MINI PUMPER|PUMPER|RESPONSE|TANKER|TOWER|UNIT|UTILITY) *[-0-9]+[A-Z]?");
    setupMultiWordStreets(MWORD_STREET_LIST);
    removeWords("LANE", "PLAZA");
  }
      
  
  @Override
  public String getFilter() {
    return "911@FCSO.COM,911_DISPATCH@franklincountyva.gov";
  }
  
  @Override
  public int getMapFlags() {
    return MAP_FLG_PREFER_GPS;
  }
  
  private static final Pattern PREFIX_PTN = Pattern.compile("(?:FCSO_911:|911_DISPATCH:)?(CFS Closed:)?");
  
  @Override
  protected boolean parseMsg(String body, Data data) {
    Matcher match = PREFIX_PTN.matcher(body);
    if (match.lookingAt()) {
      body = body.substring(match.end()).trim();
      if (match.group(1) != null) data.msgType = MsgType.RUN_REPORT;
    }
    
    int pt = body.indexOf("\n\n");
    if (pt >= 0) body = body.substring(0, pt).trim();
    return super.parseMsg(body, data);
  }

  private static final String[] MWORD_STREET_LIST = new String[]{
    "ADNEY GAP",
    "ALLAN KINGERY",
    "AMOS RIDGE",
    "ANGEL RIDGE",
    "ANGLE PLANTATION",
    "ANNIE MAE",
    "ARRINGTON PARK",
    "ASHPONE TAVERN",
    "AUTUMN CHASE",
    "BACK NINE",
    "BAILEYS CABIN",
    "BALL PARK",
    "BAR RIDGE",
    "BARNY BAY",
    "BAY SHORE",
    "BEARDS CREEK",
    "BEAVER CREEK",
    "BEECH MOUNTAIN",
    "BEECH POINT",
    "BEECH TREE",
    "BELLE ISLE",
    "BENNETT PLACE",
    "BEVERLY HILLS",
    "BIG COVE",
    "BIG OAK",
    "BITTY HILL",
    "BLACK ROCK",
    "BLACKWATER HILLS",
    "BLUE BEND",
    "BLUE HERON",
    "BLUE HILLS",
    "BLUE SPRUCE",
    "BLUEBIRD FARM",
    "BONBROOK MILL",
    "BOOKER T WASHINGTON",
    "BOON BERNARD",
    "BOONES MILL",
    "BOWLES VALLEY",
    "BOX ELDER",
    "BRANDY OAK",
    "BRIAR RIDGE",
    "BRIAR SPRINGS",
    "BRICK CHURCH",
    "BRIDGEWATER GRANDE",
    "BRIDGEWATER POINTE",
    "BROOKS MILL",
    "BROOKS POINT",
    "BROWN HILL",
    "BROWNS POINT",
    "BUFF CREEK",
    "BUFFALO RIDGE",
    "BUNNY RIDGE",
    "BURNT CHIMNEY",
    "BYRDS MILL",
    "CALICO ROCK",
    "CANTON CHURCH",
    "CANVAS BACK",
    "CARDINAL RIDGE",
    "CAROLINA SPRINGS",
    "CARVER LEE",
    "CATHEDRAL OAKS",
    "CEDAR HILL",
    "CHESTNUT ACORN",
    "CHESTNUT FOREST",
    "CHESTNUT GROVE",
    "CHESTNUT HILL",
    "CHESTNUT MEADOWS",
    "CHESTNUT MOUNTAIN",
    "CHESTNUT PARK",
    "CHIGGER RIDGE",
    "CIRCLE CREEK",
    "CLARK HOLLOW",
    "CLUB HOUSE",
    "CLUBHOUSE TOWER",
    "COAST GUARD",
    "COBWEBB HILL",
    "COLD SPRING",
    "COLES CREEK",
    "COMPASS COVE",
    "COOKS KNOB",
    "COOL SPRING",
    "COOPERS COVE",
    "COOPERS MOUNTAIN",
    "COUNTRY MILE",
    "CRAFTS FORD",
    "CRAZY HORSE",
    "CREST VIEW",
    "CROOKED OAK",
    "CROOKED RUN",
    "CROWELL GAP",
    "CUSTERS RIDGE",
    "DAVIS MILL",
    "DEAN RIDGE",
    "DEER CREEK",
    "DELILAHS PLACE",
    "DIGBY GREENE",
    "DILLARDS HILL",
    "DILLONS MILL",
    "DOE RUN",
    "DOGWOOD HILL",
    "DOGWOOD PARK",
    "DOUBLE BRANCH",
    "DOUBLE OAKS",
    "DOUBLE TWIN",
    "DOVE FIELD",
    "DRY HILL",
    "DUDLEY AMOS",
    "DUDLEY CREEK",
    "DUSTY HILL",
    "DUTCH WIND",
    "EAGLE MOUNTAIN",
    "EAST CHURCH",
    "EAST COURT",
    "EASTER MOUNTAIN",
    "EDGEWOOD FARM",
    "ELLWOOD WRAY",
    "FACTORY HILL",
    "FAIRWAY OAKS",
    "FAIRY STONE PARK",
    "FALCON RIDGE",
    "FANNY COOK",
    "FARM VIEW",
    "FERN RIDGE",
    "FERRUM MOUNTAIN",
    "FERRUM SCHOOL",
    "FISHBURN MOUNTAIN",
    "FIVE MILE MOUNTAIN",
    "FLINT HILL",
    "FLINT RIDGE",
    "FOGGY BOTTOM",
    "FOGGY RIDGE",
    "FORK MOUNTAIN",
    "FOUR BRANCH",
    "FOUR CORNERS",
    "FOX CHASE",
    "FOX TRAIL",
    "FRALINS PLACE",
    "FRYING PAN HOLLOW",
    "GAP GATE",
    "GILLS CREEK",
    "GILLS RIDGE",
    "GILMER BRANCH",
    "GLADE CREEK",
    "GLADE FARMS",
    "GLEN MEADOW",
    "GLEN OAK",
    "GOLDEN VIEW",
    "GOODE MOUNTAIN",
    "GOOSE DAM",
    "GRASSY HILL",
    "GRAVEYARD KNOB",
    "GREEN LEVEL",
    "GREEN MEADOW",
    "GREEN RIDGE",
    "GREEN VALLEY",
    "GREERS PARK",
    "GRIFFITH HILL",
    "HALEY SCOTT",
    "HARBOR LANDING",
    "HARMONY SCHOOL",
    "HAVEN RIDGE",
    "HAW PATCH",
    "HAWK RIDGE",
    "HENRY SCHOOL",
    "HICKS HOLLOW",
    "HIDDEN FALLS",
    "HIGH MEADOWS",
    "HIGHLAND FARM",
    "HILL SIDE",
    "HILLCREST HEIGHTS",
    "HILLTOP VIEW",
    "HOLLAND FARM",
    "HOLLEY RIDGE",
    "HORSESHOE POINT",
    "HUNT VALLEY",
    "HURDS BRANCH",
    "INDIAN POINTE",
    "INDIAN ROCK",
    "INDIAN RUN",
    "IRON BRIDGE",
    "IRON RIDGE",
    "ISLAND BAY",
    "ISLAND POINTE",
    "ISLAND VIEW",
    "IVY RIDGE",
    "JACKS CREEK",
    "JACKS MOUNTAIN",
    "JAMES ACRES",
    "JAMISON MILL",
    "JOHN ARTHUR",
    "JOHN BROWN",
    "JOHNNYS RIDGE",
    "JOHNSON HILL",
    "JOURNEYS END",
    "JUBAL EARLY",
    "KAY FORK",
    "KEITHS PLACE",
    "KELLY LEIGH",
    "KEMP FORD",
    "KERMIT HOLLOW",
    "KEY LAKEWOOD",
    "KIN VALE",
    "KING RICHARD",
    "KINSEY HILL",
    "KNOB CHURCH",
    "KNOB RIDGE",
    "KNOLL RIDGE",
    "LAKE PARK",
    "LAKE PINES",
    "LAKE POINTE",
    "LAKE RIDGE",
    "LAKESHORE TERRACE",
    "LAKEWATCH CENTER",
    "LAKEWOOD FOREST",
    "LAPRADE MILL",
    "LARKIN BRANCH",
    "LAUREL BLUFF",
    "LAWS HAVEN",
    "LAWS PARK",
    "LEANING OAK",
    "LIBERTY HALL",
    "LISTENING HILL",
    "LITTLE MOUNTAIN",
    "LOG CABIN",
    "LONDON RIDGE",
    "LONG BRANCH HILL",
    "LONG ISLAND",
    "LOOKOUT POINTE",
    "LOST MOUNTAIN",
    "LOVELY VALLEY",
    "LUCY WADE",
    "LYNN HAVEN",
    "MAGGODEE CREEK",
    "MALLARD COVE",
    "MALLARD POINT",
    "MARINA BAY",
    "MARIO FARM",
    "MARKET PLACE",
    "MARSHALL HILL",
    "MARVIN GARDENS",
    "MARY COGER",
    "MASONS KNOB",
    "MCKINLEY HILLS",
    "MEADOW BRANCH",
    "MEADOW BROOK",
    "MEADOW FARM",
    "MEADOW RIDGE",
    "MEADOW RIVER",
    "MEADOW SPRING",
    "MEADOW VIEW",
    "MEMBER ONE",
    "MIDDLE SCHOOL",
    "MIDDLE VALLEY",
    "MONTEGO BAY",
    "MONTGOMERY FARMS",
    "MORGAN CLAY",
    "MORGANS FORK",
    "MOUNT CARMEL",
    "MOUNT CASTLE",
    "MOUNT ZION",
    "MOUNTAIN BREEZE",
    "MOUNTAIN GAP",
    "MOUNTAIN RIDGE",
    "MOUNTAIN SIDE",
    "MOUNTAIN TOP",
    "MOUNTAIN VALLEY",
    "MUDDY FORK",
    "MULLINS COURT",
    "MURRAY HILL",
    "MURRAY KNOB",
    "MUSE FIELD",
    "NICHOLAS CREEK",
    "NOLENS HILL",
    "NORTH CHURCH",
    "NORTH MAIN",
    "OAK GARDEN",
    "OAK GROVE",
    "OAK MEADOWS",
    "OAK VIEW",
    "OLE TAYLOR",
    "ORCHARD GROVE",
    "OXEN HILL",
    "PARADISE ACRES",
    "PARK PLACE",
    "PARK WAY",
    "PARKER RIDGE",
    "PEA RIDGE",
    "PEACEFUL ACRES",
    "PEACEFUL VALLEY",
    "PENINSULA POINT",
    "PENN HALL",
    "PETERS PIKE",
    "PIGG RIVER",
    "PINE GROVE",
    "PINE NEEDLE",
    "PINE SPRINGS",
    "PINTO HOLLOW",
    "PLEASANT BREEZE",
    "PLEASANT HILL",
    "POPLAR BRANCH",
    "POPLAR COURT",
    "POPLAR COVE",
    "POPLAR HOLLOW",
    "POTTERS CREEK",
    "POWDER CREEK",
    "POWELLS STORE",
    "POWER DAM",
    "POWER LINE",
    "PRILLAMAN SWITCH",
    "PROVIDENCE CHURCH",
    "QUAIL VALLEY",
    "QUEEN MOTHERS",
    "RABBIT RIDGE",
    "RADFORD HILL",
    "RAMBLING ROSE",
    "RAMSEY MEMORIAL",
    "RED DIRT",
    "RED OAK",
    "RED VALLEY",
    "REDBUD HILL",
    "REPUBLICAN CHURCH",
    "RIDGE MOUNTAIN",
    "RIVER CREEK",
    "RIVER RIDGE",
    "ROARING RUN",
    "ROBIN RIDGE",
    "ROCK CLIFF",
    "ROCK HILL",
    "ROCK LILY",
    "ROCKY GLEN",
    "ROCKY SHORE",
    "ROLAND BRANCH",
    "ROLLING HILL",
    "ROUND HILL",
    "RUNNETT BAG",
    "RUSTIC RIDGE",
    "SAILORS COVE",
    "SALEM SCHOOL",
    "SALLYS RIDGE",
    "SALTHOUSE BRANCH",
    "SALTHOUSE VILLAGE",
    "SANDY WOODY",
    "SAULS HILL",
    "SAUNDERS FARM",
    "SCENIC RIVER",
    "SCHOOL BOARD",
    "SCUFFLING HILL",
    "SHADOW WOODS",
    "SHADY GROVE",
    "SHOOTING CREEK",
    "SHOPPERS PRIDE",
    "SHORE SIDE",
    "SILVER LAKE",
    "SIMMONS CREEK",
    "SIX MILE POST",
    "SLEEPY HOLLOW",
    "SMITH MOUNTAIN",
    "SMITH MT",
    "SMITH RIDGE",
    "SNOW CREEK",
    "SOUTH MAIN",
    "SPANISH OAK",
    "SPINNAKER SAIL",
    "ST JAMES",
    "STANLEY BRANCH",
    "STAVE MILL",
    "STONEY MILL",
    "STONEY POINTE",
    "STRAWBERRY BANKS",
    "STRIPERS LANDING",
    "SUNNY COVE",
    "SUNNY FIELD",
    "SUNSET RIDGE",
    "SUTTON HOLLOW",
    "SWEET GUM",
    "TAYLOR TYREE",
    "TAYLORS RIDGE",
    "TEEL CREEK",
    "THARP CREEK",
    "THOMPSON RIDGE",
    "THREE BOWMANS",
    "THREE FORKS",
    "THREE OAKS",
    "THREE QUARTER POINT",
    "TIMBER LINE",
    "TIMBER RIDGE",
    "TOBACCO FIELDS",
    "TOM BEAL",
    "TOMS KNOB",
    "TRAILS END",
    "TRIPPLE CREEK",
    "TROUBLE CREEK",
    "TRUMAN HILL",
    "TURKEY BRANCH",
    "TURNER RIDGE",
    "TURNERS CREEK",
    "TURTLE HILL",
    "TWELVE OAKS",
    "TWIN CREEKS",
    "TWIN OAKS",
    "TWIN RIDGE MARINA",
    "TY VALLEY",
    "VALLEY HIGH",
    "VALLEY VIEW",
    "VIC TYREE",
    "VILLAGE SPRINGS",
    "VILLAGE VIEW",
    "VIRGIL H GOODE",
    "VIRGINIA MARKET PLACE",
    "WADES GAP",
    "WALNUT HILL",
    "WALTER LEE",
    "WATERS EDGE",
    "WEBB MOUNTAIN",
    "WEBSTER CORNER",
    "WELCOME VALLEY",
    "WEST COLLEGE",
    "WEST END",
    "WEST FRANKLIN",
    "WHIPPOORWILL RIDGE",
    "WHISPERING CREEK",
    "WHISPERING MEADOWS",
    "WHIT LAND",
    "WHITE OAK",
    "WHITE TAIL",
    "WILD GOOSE",
    "WILLOW CREEK",
    "WINDING WATERS",
    "WINDING WAY",
    "WINDSOR POINT",
    "WINDWARD POINTE",
    "WINDY CREEK",
    "WINDY GAP",
    "WINDY OAKS",
    "WINDY RIDGE",
    "WOODLAND FOREST",
    "WRAYS CHAPEL",
    "WYSONG MILL"
  };
  
  private static final String[] CITY_LIST = new String[]{

    // Cities
    "BOONES MILL",
    "ROCKY MOUNT",

    // Unincorporated communities
    "BENT MOUNTAIN",
    "CALLAWAY",
    "FERRUM",
    "GLADE HILL",
    "HALES FORD",
    "HARDY",
    "NORTH SHORE",
    "PENHOOK",
    "REDWOOD",
    "SNOW CREEK",
    "UNION HALL",
    "WESTLAKE CORNER",
    "WIRTZ",
    
    // Independent Cities
    "ROANOKE",
    
    // Bedford County
    "BEDFORD",
    "BIG ISLAND",
    "CHAMBLISSBURG",
    "FOREST",
    "GOODE",
    "HARDY",
    "HUDDLESTON",
    "MONETA",
    "MONTVALE",
    "NEW LONDON",
    "STEWARTSVILLE",
    "THAXTON",
    
    // Floyd County
    "ALUM RIDGE",
    "BURKS FORK",
    "CARTHAGE",
    "CHECK",
    "CONNERS GROVE",
    "COPPER HILL",
    "COPPER VALLEY",
    "COURT HOUSE",
    "DUNCAN",
    "FLOYD",
    "HAYCOCK",
    "HEMLOCK",
    "HUFFVILLE",
    "INDIAN VALLEY",
    "LAUREL BRANCH",
    "LITTLE RIVER",
    "LOCUST VALLEY",
    "MABRY MILL",
    "MARTINSVILLE",
    "PIZARRO",
    "POFF",
    "SHELORS MILL",
    "SIMPSONS",
    "SMART",
    "SOWERS",
    "TERRYS FORK",
    "TURTLE ROCK",
    "UNION",
    "WILLIS",
    
    // Henry County
    "AXTON",
    "BASSETT",
    "CHATMOSS",
    "COLLINSVILLE",
    "FIELDALE",
    "HENRY",
    "HORSEPASTURE",
    "LAUREL PARK",
    "OAK LEVEL",
    "RIDGEWAY",
    "SANDY LEVEL",
    "SPENCER",
    "STANLEYTOWN",
    "VILLA HEIGHTS",
    
    // Patrick County
    "ARARAT",
    "CLAUDVILLE",
    "CRITZ",
    "FAIRYSTONE",
    "MAYBERRY",
    "MEADOWS OF DAN",
    "PATRICK SPRINGS",
    "PENNS STORE",
    "REYNOLDS HOMESTEAD",
    "RUSSELL CREEK",
    "STUART",
    "VESTA",
    "WOOLWINE",
    
    // Bachelors Hall
    "BACHELORS HALL",
    "BLAIRS",
    "BROSVILLE",
    "CHALK LEVEL",
    "CHATHAM",
    "CLIMAX",      //?
    "DRY FORK",
    "GRETNA",      //?
    "GRIT",
    "HURT",                //+
    "KEELING",
    "MOUNT AIRY",
    "MT HERMON",
    "PICKERAL'S CROSSING",
    "PITTSVILLE",
    "RENAN",
    "RINGGOLD",
    "SONANS",
    "STRAIGHTSTONE",
    "TIGHTSQUEEZE",
    "WHITTLES DEPOT",
    
    // Roanoke County
    "BACK CREEK",
    "BENT MOUNTAIN",
    "BONSACK",
    "CATAWBA",
    "CAVE SPRING",
    "CLEARBROOK",
    "FORT LEWIS",
    "GLENVAR",
    "HANGING ROCK",
    "HOLLINS",
    "MASONS COVE",
    "MOUNT PLEASANT",
    "OAK GROVE",
    "PENN FOREST",
    "POAGES MILL",
    "READ MOUNTAIN",
    "VINTON",


  };

}