package net.anei.cadpage.parsers.VA;

import java.util.Properties;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchDAPROParser;



public class VARockinghamCountyParser extends DispatchDAPROParser {

  public VARockinghamCountyParser() {
    this("ROCKINGHAM COUNTY", "VA");
  }
  protected VARockinghamCountyParser(String defCity, String defState) {
    super(CITY_CODES, defCity, defState);
    setupCallList(CALL_SET);
    setupMultiWordStreets(MWORD_STREET_LIST);
  }
  
  @Override
  public String getAliasCode() {
    return "VARockinghamCounty";
  }

  @Override
  public String getFilter() {
    return "messaging@iamresponding.com,mailbox@hrecc.org,MAILBOX@pagesheriff.COM,93001,5402446442";
  }

  private static final Pattern MASHED_SUBJECT_PTN = Pattern.compile("[A-Z]+\\d+ \\d\\d|.* CROSS");
  @Override
  public boolean parseMsg(String subject, String body, Data data) {
    
    if (MASHED_SUBJECT_PTN.matcher(subject).matches()) {
      boolean prefix = body.startsWith("MAILBOX:");
      if (prefix) body = body.substring(8);
      body = subject + ":" + body;
      if (prefix) body = "MAILBOX:" + body;
    }
    return super.parseMsg(body, data);
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
    "AMERICAN LEGION",
    "ANDRICK MILL",
    "APPLE RIDGE",
    "APPLE VALLEY",
    "AUTUMN VIEW",
    "AYLOR GRUBBS",
    "BEAR MOUNTAIN",
    "BEAVER CREEK",
    "BENNETT RUN",
    "BETHEL CHURCH",
    "BIG OAK",
    "BIRD SONG",
    "BLACK WALNUT",
    "BLUE BELL",
    "BLUE HERON",
    "BLUE MOUNTAIN",
    "BLUESTONE HILLS",
    "BRANCH POINT",
    "BRIDGEWATER COLLEGE",
    "BRIERY BRANCH",
    "BROCKS GAP",
    "BRYANT HOLLOW",
    "BYRD ORCHARD",
    "CABIN VIEW",
    "CAMPUS VIEW",
    "CANOE RIVER",
    "CAPT SHANDS",
    "CAPTAIN YANCEY",
    "CEDAR KNOB",
    "CEDAR SPRING",
    "CHERRY GROVE",
    "CHESTNUT RIDGE",
    "CINDER RUN",
    "CIRCLE R",
    "CLOVER HILL",
    "COAL RUN",
    "COLLEGE VIEW",
    "COMMUNITY CENTER",
    "CONVOCATION SERV",
    "COOPERS MTN",
    "COUNTRY CLUB",
    "CROSS KEYS",
    "DANIEL CUPP",
    "DAVE BERRY",
    "DAVIS MILLS",
    "DON LITTEN",
    "DOVE LANDING",
    "DRY HOLLOW",
    "DRY RIVER",
    "DRY RUN",
    "DRY RUN ACRES",
    "DUCK RUN",
    "EAGLE ROCK",
    "EAST POINT",
    "EAST SIDE",
    "EGYPT BEND",
    "ELLENS ROOST",
    "EVELYN BYRD",
    "EVERGREEN VALLEY",
    "FOX MOUNTAIN",
    "FRIEDENS CHURCH",
    "GARBERS CHURCH",
    "GIANTS GRAVE",
    "GLEN HOLLOW",
    "GLEN LOCH",
    "GOLDEN CREEK",
    "GOODS MILL",
    "GRACE CHAPEL",
    "GRANNY SMITH",
    "GREEN VALLEY",
    "GUM TREE",
    "HANSE MOUNTAIN",
    "HARNESS SHOP",
    "HARPER VALLEY",
    "HIDDEN CREEK",
    "HIDDEN VALLEY",
    "HILL VIEW",
    "HOME VIEW",
    "HONE QUARRY",
    "HONEY RUN",
    "HOPKINS GAP",
    "HOREB CHURCH",
    "IKENBERRY SERVICE",
    "INDIAN SPRING",
    "ISLAND FORD",
    "J ELLIS",
    "J J",
    "JESS AREY",
    "JESSE BENNETT",
    "JOHN WAYLAND",
    "JUDGE PAUL",
    "KETTLE VIEW",
    "LACEY SPRING",
    "LADY BUG",
    "LAKESIDE SERVICE",
    "LAMBERT TOWN",
    "LAYMAN HOLLOW",
    "LEISURE LIVING",
    "LINVILLE EDOM",
    "LITTLE GAP",
    "LITTLE PASS",
    "LITTLE SPRING",
    "LONE PINE",
    "LONG MEADOW",
    "LUMBER MILL",
    "LURAY MOBILE HOMES",
    "MALL RING",
    "MARTIN MILLER",
    "MASSANETTA SPRINGS",
    "MEADOWS NORTH",
    "MEMORIAL PARK",
    "MILKY WAY",
    "MILL CREEK",
    "MILL RUN",
    "MINNICK HOLLOW",
    "MODULAR HILL",
    "MONGER HILL",
    "MORRIS POTTERY",
    "MOUNT HERMON",
    "MOUNTAIN FARM",
    "MOUNTAIN RUN",
    "MOUNTAIN VALLEY",
    "MOUNTAIN VIEW",
    "MT CARMEL",
    "MT CLINTON",
    "MT CRAWFORD",
    "MT HERMON",
    "MT PLEASANT",
    "MT SINAI",
    "MYSTIC WOODS",
    "NAKED CREEK",
    "NAZARENE CHURCH",
    "NEWDALE SCHOOL",
    "NORTH MOUNTAIN",
    "NORTH RIVER",
    "NOW LOOK",
    "OAK RIDGE",
    "OAK SHADE",
    "OAK VILLA",
    "OLIVIA DAWN",
    "PAGE VALLEY",
    "PAYNE HOLLOW",
    "PEACH GROVE",
    "PEACH ORCHARD",
    "PEAKE MOUNTAIN",
    "PHEASANT RUN",
    "PIG FARMERS",
    "PIKE CHURCH",
    "PINE GROVE",
    "PINE HARBOR",
    "PINEY WOODS",
    "PLEASANT HILL",
    "PLEASANT VALLEY",
    "PLEASANT VIEW",
    "PORCH SWING",
    "PORT REPUBLIC",
    "PROSPECT KNOLL",
    "RADERS CHURCH",
    "RED BRUSH",
    "RED CHURCH",
    "RED HILL",
    "RINACAS CORNER",
    "RIVER VIEW",
    "ROCK CAVE",
    "ROLLING CREEK",
    "ROSE HILL",
    "ROUND HILL",
    "RUNKLES GAP",
    "SAND PIT",
    "SANDY BOTTOM",
    "SANDY HOOK",
    "SAPLING RIDGE",
    "SHELL HOLLOW",
    "SHENANDOAH MOUNTAIN",
    "SHENANDOAH RIVER",
    "SHIFFLETT HILL",
    "SHORT RUN",
    "SILVER CREEK",
    "SILVER LAKE",
    "SIMMERS VALLEY",
    "SINGERS GLEN",
    "SKIDMORE FORK",
    "SMITH MOUNTAIN",
    "SNAPPS CREEK",
    "SOUTH BRANCH",
    "SOUTH CREEK",
    "SPAR MINE",
    "SPRING CREEK",
    "ST STEPHENS",
    "STEAMBOAT HOLLOW",
    "STONE SPRING",
    "STROLE FARM",
    "SUGAR MAPLE",
    "SUN VALLEY",
    "SWEET CORN",
    "SWITZER LAKE",
    "TALL CEDARS",
    "TANNERS RIDGE",
    "TANYARD BRIDGE",
    "TARA DAWN",
    "THOMAS SPRING",
    "TOWN RESERVOIR",
    "TRAILING IVY",
    "TREE SIDE",
    "TRINITY CHURCH",
    "TRIPLE Z",
    "TURNER ASHBY",
    "UNION SPRINGS",
    "VALLEY VIEW",
    "VISTA GLEN",
    "WAGGYS CREEK",
    "WALKING HORSE",
    "WAR BRANCH",
    "WEEPING WILLOW",
    "WELL HOLLOW",
    "WEST VIEW",
    "WEST WIND",
    "WHISPERING WINDS",
    "WHITE PICKET",
    "WHITESEL CHURCH",
    "WHITMORE SHOP",
    "WILLIE B",
    "WILLOW HILL",
    "WINDY COVE",
    "WINE STORE",
    "WISE HOLLOW",
    "WOODED VIEW",
    "ZION CHURCH",
    "ZIRKLE HEIGHTS"
  };

  private static final CodeSet CALL_SET = new CodeSet(
      "911 OPEN LINE",
      "ABDOMINAL PAIN",
      "ALARM SOUNDING",
      "ALCOHOL RELATED ILLNESS-LIFE T",
      "ALCOHOL RELATED ILLNESS-NON LI",
      "ALLERGIC REACTION",
      "ALLERGIC REACTION-LIFE THREATE",
      "ALLERGIC REACTION-NON LIFE THR",
      "ALS ASSIST",
      "ALTERED LOC",
      "ANIMAL BITE-MINOR INJURY",
      "AUTOMATIC FIRE ALARM",
      "BACK PAIN",
      "BLEEDING CONTROLLED",
      "BLEEDING UNCONTROLLED",
      "BRUSH FIRE",
      "BRUSH FIRE THREATENING A STRUC",
      "BURNS-SEVER/LIFE THREATENING",
      "CARDIAC ARREST",
      "CARDIAC CALL",
      "CARDIAC CALL TANNERS RIDGE OVERLOOK SNP",
      "CARDIAC CONDITION",
      "CHEST PAIN",
      "CHEST PAINS",
      "CHOKING-FR",
      "CO EVENT W/O ILLNESS",
      "COMMERCIAL ALARM",
      "CONTROLLED BURN",
      "DIABETIC EMERGENCY",
      "DIABETIC EMERGENCY-LIFE THREAT",
      "DIABETIC EMERGENCY-NON LIFE TH",
      "DIFFICULTY BREATHING",
      "DIZZINESS",
      "DROWNING/NEAR DROWNING",
      "ELEVATOR ENTRAPMENT",
      "EMS-ABDOMINAL PAIN",
      "EMS-CARDIAC CONDITION",
      "EMS-CHEST PAIN",
      "EMS-DIFFICULTY BREATHING",
      "EMS-FALLS",
      "EMS-ILLNESS",
      "EMS-MENTAL PROBLEM",
      "EMS-STROKE",
      "EMS-TRAUMA INJURIES",
      "EXPLOSION",
      "EXPOSURE TO HEAT/COLD-MINOR",
      "FALLS>PATIENT HEIGHT-MAJOR INJ",
      "FALLS<PATIENT HEIGHT-MINOR INJ",
      "FEVER-NON-LIFE THREATENING",
      "FILL QUARTERS",
      "FIRE ALARM",
      "FIRE REPORTED OUT ALMA RECYCLING CENTER",
      "FRACTURE",
      "GENERAL ILLNESS",
      "GRASS FIRE",
      "GRASS FIRE CROSS",
      "GRASS FIRE THREATENING A STRUC",
      "GUNSHOT-MINOR",
      "HAZMAT INCIDENT",
      "HEADACHE",
      "HEMORRHAGING",
      "HYPER/HYPOTENSIVE EVENT-MAJOR",
      "HYPER/HYPOTENSIVE EVENT-MINOR",
      "ILLNESS",
      "ILLNESS-NON LIFE THREATENING",
      "INCIDENT STRUCTURE FIRE",
      "INJURIES FROM A FALL",
      "INJURIES FROM ASSAULT-MINOR",
      "INJURY - LEG, ARM, ETC.",
      "INJURY-MINOR",
      "LACERATION-MINOR",
      "LANDING ZONE",
      "LINES DOWN",
      "LOCK OUT SERVICE",
      "LZ SET-UP RILEYVILLE BAPTIST #31",
      "MANPOWER REQUESTED",
      "MEDICAL ALARM",
      "MENTAL HEALTH",
      "NON-RESPONSIVE PERSON",
      "NON-RESPONSIVE PERSON DARK HOLLOW FALLS SNP",
      "NOSEBLEED",
      "OB RELATED EVENT-MAJOR",
      "OB RELATED EVENT-MINOR",
      "ODOR INVESTIGATION",
      "ODOR INVESTIGATION IN STRUCTUR",
      "OVERDOSE",
      "OVERDOSE-LIFE THREATENING",
      "PAIN",
      "POSSIBLE STRUCTURE FIRE",
      "PSYCHIATRIC EMERGENCY",
      "PUBLIC SERVICE CALL",
      "PUBLIC SERVICE CALL NEW FAMILY DOLLAR",
      "REQUEST FOR ALS",
      "SEIZURE-ACTIVE",
      "SEIZURE-NOT ACTIVE OR MULTIPLE",
      "SEIZURES",
      "SIMPLE ASSAULT",
      "SIMPLE ASSAULT SOUTH END CONVENIENCE",
      "SMOKE IN THE AREA",
      "SMOKE INVESTIGATION",
      "SMOKE INVESTIGATION SANDY",
      "SPORTS INJURY-MINOR",
      "STAND-BY",
      "STAND-BY BRIERY",
      "STAND-BY REDDISH",
      "STROKE/STROKE SYMPTOMS",
      "STRUCTURE FIRE",
      "SUICIDE ATTEMPT",
      "SUICIDE THREAT",
      "TRAFFIC CRASH",
      "TRAFFIC CRASH INVOLVING A BUS",
      "TRAFFIC CRASH INVOLVING PEDEST",
      "TRAFFIC CRASH INVOLVING TRACTO",
      "TRANSFER QUARTERS",
      "TRANSFORMER/POLE FIRE",
      "TRANSFORMER/POLE FIRE 21063  BLUE AND",
      "TRAUMA INJURIES-MAJOR",
      "UNCONSCIOUS PERSON",
      "UNKNOWN MEDICAL",
      "UNKNOWN MEDICAL CONDITION",
      "UNKNOWN SITUATION",
      "UNRESPONSIVE PERSON",
      "UNRESPONSIVE PERSON 20593  BLUE AND",
      "VEHICLE FIRE",
      "VEHICLE FIRE INVOLVING TRACTOR",
      "VEHICLE FIRE THREATENING STRUC",
      "WATER EVENT",
      "WATER REMOVAL",
      "WELFARE CHECK",
      "WOMAN DOWN"

  );

  private static final Properties CITY_CODES = buildCodeTable(new String[]{
      "BER", "BERGTON",
      "BRO", "BROADWAY",
      "BRI", "BRIDGEWATER",
      "CLO", "CLOVER HILL",
      "DAY", "DAYTON",
      "ELK", "ELKTON",
      "FUL", "FULKS RUN",
      "GRO", "GROTTOES",
      "HAR", "HARRISONBURG",
      "HIN", "HINTON",
      "KEE", "KEEZLETOWN",
      "LIN", "LINVILLE",
      "LUR", "LURAY",
      "MCG", "MCGAHEYSVILLE",
      "MOU", "MOUNT CRAWFORD",
      "NEW", "NEW MARKET",
      "PEN", "PENN LAIRD",
      "POR", "PORT REPUBLIC",
      "SHE", "SHENANDOAH",
      "RIL", "RILEYVILLE",
      "ROC", "ROCKINGHAM COUNTY",
      "SIN", "SINGERS GLEN",
      "STA", "STANLEY",
      "TIM", "TIMBERVILLE",
      "WEY", "WEYERS CAVE"
  });
}