package net.anei.cadpage.parsers.CA;

import java.util.Properties;
import net.anei.cadpage.parsers.dispatch.DispatchA20Parser;

/**
 * Oroville, CA
 */
public class CAOrovilleParser extends DispatchA20Parser {

  public CAOrovilleParser() {
    super(CALL_CODES, "OROVILLE", "CA", A20_UNIT_LABEL_REQ);
  }

  @Override
  public String getFilter() {
    return "@OROPD.ORG";
  }

  @Override
  public int getMapFlags() {
    return MAP_FLG_SUPPR_LA;
  }

  private static final Properties CALL_CODES = buildCodeTable(new String[]{
      "AIRCRAFT", "AIRCRAFT 1 OR 2 ENGINE FIRE",
      "AIRPASS",  "AIRPLANE PASSENGER FIRE",
      "AIRPORT",  "AIRPORT FIRE",
      "ALF",      "ASSISTED LIVING/NURSING HOME FIRE",
      "APTFIRE",  "APARTMENT COMPLEX FIRE",
      "CASFIRE",  "CASINO FIRE",
      "DMPSTFIRE","DUMPSTER FIRE",
      "FDASSIST", "PUBLIC ASSIST",
      "FDFIRE1",  "VEHICLE/OTHER FIRE",
      "FDFIRE2",  "VEHICLE FIRE (OCCUPIED)",
      "FDFIRE3",  "VEGETATION",
      "FDFIRE4",  "STRUCTURE",
      "FDFIRE5",  "COMMERCIAL STRUCTURE",
      "FDGEN",    "LEVEL 1 STAFFING",
      "FDHAZD3",  "FLOODING",
      "FDHAZMA1", "MINOR HAZMAT",
      "FDHAZMA2", "MAJOR HAZMAT",
      "FDHAZMAT", "HAZARDOUS CONDITION",
      "FDINVEST", "ALARM SOUNDING/SMOKE CHECK",
      "FDMED",    "MEDICAL",
      "FDMED2",   "MEDICAL (CPR)",
      "FDRESCUE", "TECHNICAL RESCUE",
      "FDTC1",    "T/C",
      "FDTC2",    "T/C POSSIBLE MCI",
      "FDW/ALAR", "WATER FLOW ALARM",
      "FDWATER",  "WATER RESCUE",
      "HAZMAT1",  "HAZMAT LEVEL 1",
      "HAZMAT2",  "HAZMAT LEVEL 2",
      "HAZMAT3",  "HAZMAT LEVEL 3",
      "HAZMATMC", "HAZMAT LEVEL 3 MASS CASUALTIES",
      "HOSPFIRE", "HOSPITAL FIRE",
      "HTLFIRE",  "HOTEL FIRE",
      "HYDRANT",  "HYDRANT LEAKING/SHEARED OFF",
      "INDCFIRE", "INDUSTRIAL COMPLEX FIRE",
      "INVEST",   "SMOKE/FIRE ALARM NO CONFIRMATION",
      "ISF",      "INDUSTRIAL STRUCTURE FIRE",
      "LANDFILL", "LANDFILL FIRE",
      "LINE DWN", "POWER LINES DOWN",
      "MED BLSE", "MED AID BLS EMERGENCY",
      "MED LT",   "MED AID ALS LIFE THREATENING",
      "MEDNLT",   "MED AID ALSO NON THREATENING",
      "ODOR GI",  "ODOR OF GAS INSIDE",
      "ODOR GO",  "ODOR OF GAS OUTSIDE",
      "PUB LIFT", "PUBLIC ASSIST - LIFT ASSIST",
      "RAILFIRE", "TRAIN-RAILWAY FIRE",
      "RSF",      "RESIDENTIAL STRUCTURE FIRE",
      "RUPGAO",   "RUP GAS LINE INSIDE",
      "RUPGASI",  "RUPT GAS LINE INSIDE",
      "SUSDVICE", "SUSPICIOUS DEVICE",
      "TC",       "TWO VEHICLE TC",
      "TCBUS",    "PASSENGER BUSS INVOLVED",
      "TCCOMVEH", "COMMERCIAL VEHICLE INVOLVED",
      "TCFIRE",   "LARGE VEH. TC W-FIRE",
      "TCMC",     "SINGLE MOTORCYCLE",
      "TCROLL",   "SINGLE VEHICLE ROLLOVER",
      "TCV-M",    "VEHICLE VS MOTORCYCLE",
      "TCV-PED",  "VEHICLE VS PEDESTRIAN OR BICYCLIST",
      "TRBUS",    "PASSENGER BUSS OVER SIDE",
      "TRCONSPA", "CONFINED SPACE ENTRAPMENT",
      "TREE-OS",  "TREE IN OCCUPIED STRUCTURE",
      "TREE-US",  "TREE INTO UNOCCUPIED STRUCTURE",
      "TRPERSON", "PERSON TRAPPED ON LEDGE",
      "TRTRENCH", "TRENCH ENTRAPMENT",
      "TRVEHB",   "VEH ON EDGE OF BRIDGE OVER WATER",
      "TRVEHOP",  "VEH ON EDGE OF BRIDGE OVERPASS",
      "TRVOSH",   "VEH OVER SIDE HIGH ANGLE",
      "TRVOSL",   "VEH OVER SIDE LOW ANGLE",
      "VBFIRE",   "BUS FIRE",
      "VCFIRE",   "COMMERCIAL VEHICLE FIRE",
      "VEGEFIRE", "VEGETATION FIRE",
      "VEGMTZ",   "VEGETATION FIRE IN MTZ",
      "VEGSFIRE", "VEGETATION FIRE STRUCTURE THREATENED",
      "VPFIRE",   "PASSENGER VEHICLE FIRE",
      "VRVFIRE",  "RECREATIONAL VEHICLE FIRE",
      "VSFIRE",   "VEH IN-NEAR STRUCTURE FIRE",
      "VTFIRE",   "HAZMAT TANKER FIRE",
      "WFA",      "WATER FLOW ALARM",
      "WLB IN",   "WATER LINE BREAK INSIDE",
      "WLB OUT",  "WATER LINE BREAK OUTSIDE",
      "WRDYNA",   "DYNAMIC WATER RESCUE RIVER",
      "WRPERS",   "MULTI VICTIM WATER RESCUE",
      "WRSTATIC", "STATIC WATER RESCUE",
      "WRVEH",    "VEHICLE IN WATER"

  });
}
