package net.anei.cadpage.parsers.CA;

import java.util.Properties;

import net.anei.cadpage.parsers.dispatch.DispatchH03Parser;

public class CASantaCruzCountyCParser extends DispatchH03Parser {
  
  public CASantaCruzCountyCParser() {
    super(CITY_CODES, "SANTA CRUZ COUNTY", "CA");
  }
  
  @Override
  public String getFilter() {
    return "@scr911users.org";
  }
  
  private static final Properties CITY_CODES = buildCodeTable(new String[]{
      "AP/LA SELVA",      "APTOS",
      "APTOS AREA",       "APTOS",
      "APTOS HILLS",      "APTOS",
      "APTOS/LA SELVA",   "APTOS",
      "AROMAS SAN BNTO",  "AROMAS",
      "AROMAS SNTA CRZ",  "AROMAS",
      "BEAN CREEK AREA",  "BEAN CREEK",
      "BEULAH PARK",      "SANTA CRUZ",
      "BIG BASIN",        "BOULDER CREEK",
      "BIG REDWOOD PRK",  "SCOTTS VALLEY",
      "BOULDER CRK",      "BOULDER CREEK",
      "BRANCIFORTE",      "SANTA CRUZ",
      "BUENA VISTA ARE",  "WATSONVILLE",
      "BURRELL AREA",     "LOS GATOS",
      "CALABASAS RD",     "WATSONVILLE",
      "CAPITOLA PD",      "SANTA CRUZ",
      "CARBONERA AREA",   "SANTA CRUZ",
      "CASTLE ROCK",      "BOULDER CREEK",
      "COUNTY POCKET",    "HOLLISTER",
      "CPD ONLY",         "SANTA CRUZ",
      "DIMEO LN AREA",    "SANTA CRUZ",
      "DOMINICAN AREA",   "SANTA CRUZ",
      "DVNPT/BNY DN",     "SANTA CRUZ",
      "EAST SV AREA",     "SCOTTS VALLEY",
      "EMPIRE GRD AREA",  "BOULDER CREEK",
      "FELTON MT HERM",   "MT HERMON",
      "FELTON QUARRY",    "FELTON",
      "FLT EMPIRE AREA",  "FELTON",
      "FRDM BL CORIDOR",  "APTOS",
      "FRESNO CO",        "FRESNO COUNTY",
      "GLEN CANYN AREA",  "SCOTTS VALLEY",
      "GLENWOOD ACRES",   "SCOTTS VALLEY",
      "GLENWOOD AREA",    "SCOTTS VALLEY",
      "GRAM HILL AREA",   "SANTA CRUZ",
      "GRANIT CRK AREA",  "SCOTTS VALLEY",
      "HARKINS SLOUGH",   "WATSONVILLE",
      "HENRY COWELL",     "FELTON",
      "HOLL TRAFF ONLY",  "HOLLISTER",
      "HOLLISTER HILLS",  "HOLLISTER",
      "HPD TRAFF ONLY",   "HOLLISTER",
      "HUTCHINSON AREA",  "LOS GATOS",
      "IDRIA",            "PAICINES",
      "JARVIS RD AREA",   "SANTA CRUZ",
      "KINGS CRK AREA",   "BOULDER CREEK",
      "LARKIN VALLEY",    "WATSONVILLE",
      "LAS CUMBRES",      "LOS GATOS",
      "LITTLE BASIN AR",  "BOULDER CREEK",
      "LIVE OAK",         "SANTA CRUZ",
      "LKHRT GLCH AREA",  "SCOTTS VALLEY",
      "LOCKEWOOD AREA",   "SCOTTS VALLEY",
      "LOVE CREEK AREA",  "BEN LOMOND",
      "MANANA WOODS",     "SCOTTS VALLEY",
      "MERCED CO",        "MERCED COUNTY",
      "MISSION SPRINGS",  "SCOTTS VALLEY",
      "MNTRY BAY ACAD",   "WATSONVILLE",
      "MONTEREY CO",      "MONTEREY COUNTY",
      "MT BIELAWSKI AR",  "LOS GATOS",
      "MT HRMN BYPASS",   "SCOTTS VALLEY",
      "MTN CHARLIE",      "SCOTTS VALLEY",
      "MTN VIEW RD ARE",  "SANTA CRUZ",
      "NEW BRIGHTON",     "APTOS",
      "NISENE MARKS",     "APTOS",
      "NORTH CNTY",       "BEN LOMOND",
      "NORTH COAST",      "SANTA CRUZ",
      "OCEAN ST EXT",     "SANTA CRUZ",
      "OLD PLKNTN AREA",  "SANTA CRUZ",
      "OUTER BLDR CRK",   "BOULDER CREEK",
      "PAJARO DUNES",     "WATSONVILLE",
      "PAJARO VLY",       "WATSONVILLE",
      "PARADISE PK",      "SANTA CRUZ",
      "PASATIEMPO",       "SANTA CRUZ",
      "PAUL SWEET AREA",  "SANTA CRUZ",
      "PINACLS NAT MON",  "PAICINES",
      "PLEASANT VALLEY",  "APTOS",
      "RANCHO LARIOS",    "SAN JUAN BAUTISTA",
      "RIDGEMARK",        "HOLLISTER",
      "ROLLING WOODS",    "SCOTTS VALLEY",
      "S CRUZ GDNS",      "SANTA CRUZ",
      "SAN ANDREAS ARE",  "WATSONVILLE",
      "SAN BENITO CO",    "HOLLISTER",
      "SAN JUAN BTSTA",   "SAN JUAN BAUTISTA",
      "SAN MATEO AREA",   "DAVENPORT",
      "SAN MATEO CO",     "SAN MATEO COUNTY",
      "SANTA CLARA CO",   "SANTA CLARA COUNTY",
      "SANTA CRUZ AREA",  "SANTA CRUZ",
      "SB SHERIFFS OFF",  "HOLLISTER",
      "SCOTTS VLY AREA",  "SCOTTS VALLEY",
      "SCOTTS VLY",       "SCOTTS VALLEY",
      "SCPD ONLY",        "SANTA CRUZ",
      "SEND TO CHP CAP",  "CAPITOLA",
      "SEND TO CHP SO",   "WATSONVILLE",
      "SEND TO CHP SP",   "SANTA CRUZ",
      "SEND TO CHP WP",   "WATSONVILLE",
      "SHERIFFS OF",      "SANTA CRUZ",
      "SIMS RD AREA",     "SANTA CRUZ",
      "SN JN BTSTA ARE",  "SAN JUAN BAUTISTA",
      "SO ONLY",          "WATSONVILLE",
      "SO",               "WATSONVILLE",
      "SR1 N OF WATS",    "WATSONVILLE",
      "SR17 N SV AREA",   "SCOTTS VALLEY",
      "SR17 S SV AREA",   "SCOTTS VALLEY",
      "SR17 SUMMIT ARE",  "LOS GATOS",
      "SR35 - SUMMIT",    "LOS GATOS",
      "SR9 N OF S CRUZ",  "SANTA CRUZ",
      "SR9 SUMMIT AREA",  "LOS GATOS",
      "SUNSET ST BEACH",  "WATSONVILLE",
      "SWANTON AREA",     "DAVENPORT",
      "UCSC AREA",        "SANTA CRUZ",
      "UCSC",             "SANTA CRUZ",
      "UPR SKYLINE ARE",  "LOS GATOS",
      "UPR SR236/SR9",    "BOULDER CREEK",
      "UPR ZAYANTE ARE",  "LOS GATOS",
      "VINE HILL RD",     "SCOTTS VALLEY",
      "W BEACH AREA",     "WATSONVILLE",
      "W RIVERSIDE ARE",  "WATSONVILLE",
      "WATSNVIL AREA",    "WATSONVILLE",
      "WESTON RD AREA",   "SCOTTS VALLEY",
      "WILDER RANCH",     "SANTA CRUZ",
      "WPD ONLY",         "SANTA CRUZ",
      "WPD TRANSP",       "SANTA CRUZ",
      "ZAYANTE",          "FELTON"
      
  });
}
