package net.anei.cadpage.parsers.IL;

import net.anei.cadpage.parsers.GroupBestParser;

public class ILLakeCountyParser extends GroupBestParser {

  public ILLakeCountyParser() {
    super(new ILLakeCountyAParser(),
          new ILLakeCountyCParser(),
          new ILLakeCountyDParser(),
          new ILLakeCountyEParser(),
          new ILLakeCountyFParser(),
          new ILLakeCountyGParser(),
          new ILLakeCountyHParser(),
          new ILLakeCountyIParser());

  }

  static final String[] CITY_LIST = new String[] {

      // Cities
      "HIGHLAND PARK",
      "HIGHWOOD",
      "LAKE FOREST",
      "MCHENRY",
      "NORTH CHICAGO",
      "PARK CITY",
      "WAUKEGAN",
      "ZION",

      // Villages
      "ANTIOCH",
      "BANNOCKBURN",
      "BARRINGTON",
      "BARRINGTON HILLS",
      "BEACH PARK",
      "BUFFALO GROVE",
      "DEERFIELD",
      "DEER PARK",
      "FOX LAKE",
      "FOX RIVER GROVE",
      "GRAYSLAKE",
      "GREEN OAKS",
      "GREEN OAKES",
      "GURNEE",
      "HAINESVILLE",
      "HAWTHORN WOODS",
      "INDIAN CREEK",
      "ISLAND LAKE",
      "KILDEER",
      "LAKE BARRINGTON",
      "LAKE BLUFF",
      "LAKE VILLA",
      "LAKE ZURICH",
      "LAKEMOOR",
      "LIBERTYVILLE",
      "LINCOLNSHIRE",
      "LINDENHURST",
      "LONG GROVE",
      "METTAWA",
      "MUNDELEIN",
      "NORTH BARRINGTON",
      "OLD MILL CREEK",
      "PORT BARRINGTON",
      "RIVERWOODS",
      "ROUND LAKE",
      "ROUND LAKE BEACH",
      "ROUND LAKE HEIGHTS",
      "ROUND LAKE PARK",
      "THIRD LAKE",
      "TOWER LAKES",
      "VERNON HILLS",
      "VOLO",
      "WADSWORTH",
      "WAUCONDA",
      "WHEELING",
      "WINTHROP HARBOR",

      // Census-designated places
      "CHANNEL LAKE",
      "FOREST LAKE",
      "FOX LAKE HILLS",
      "GAGES LAKE",
      "GRANDWOOD PARK",
      "KNOLLWOOD",
      "LAKE CATHERINE",
      "LONG LAKE",
      "VENETIAN VILLAGE",

      // Unincorporated communities
      "APTAKISIC",
      "DIAMOND LAKE",
      "EDDY",
      "FORT SHERIDAN",
      "FREMONT CENTER",
      "GILMER",
      "GRANGE HALL",
      "GRASS LAKE",
      "HALF DAY",
      "INGLESIDE",
      "IVANHOE",
      "KENNEDY",
      "LOON LAKE",
      "MILLBURN",
      "MONAVILLE",
      "PALM BEACH",
      "PRAIRIE VIEW",
      "RONDOUT",
      "ROSECRANS",
      "RUSSELL",
      "SYLVAN LAKE",
      "WEST MILTMORE",
      "WILDWOOD",
      "WILSON",

      // Townships
      "ANTIOCH",
      "AVON",
      "BENTON",
      "CUBA",
      "ELA",
      "FREMONT",
      "GRANT",
      "LAKE VILLA",
      "LIBERTYVILLE",
      "MORAINE",
      "NEWPORT",
      "SHIELDS",
      "VERNON",
      "WARREN",
      "WAUCONDA",
      "WAUKEGAN",
      "WEST DEERFIELD",
      "ZION",

      // Cook County
      "GLENCOE",
      "GLENVIEW",
      "NORTHBROOK"
  };
}
