package net.anei.cadpage.parsers.PA;

import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchB2Parser;

public class PAButlerCountyParser extends DispatchB2Parser {
  
  private static final Pattern MARKER = Pattern.compile(" Cad: \\d{4}-\\d{10}$");
  private static final Pattern NAME_COUNTY_PTN = Pattern.compile("([A-Z]+)\\b(?!,) *(?:BEAVER *)?(?:CO(?:UNTY)?)? *(?:911|9-1-1)? *(.*)");

  public PAButlerCountyParser() {
    super("BUTLER911:", CITY_LIST, "BUTLER COUNTY", "PA", B2_CROSS_FOLLOWS);
    setupSaintNames("BARNABAS","JOHNS");
    removeWords("TURNPIKE");
    setupMultiWordStreets(MWORD_STREET_LIST);
  }
  
  @Override
  public String getFilter() {
    return "@butlerco.911,@co.butler.pa.us";
  }
  
  @Override
  public String adjustMapAddress(String addr) {
    addr = PA_TPKE_PTN.matcher(addr).replaceAll("PENNSYLVANIA TURNPIKE");
    return super.adjustMapAddress(addr);
  }
  private static final Pattern PA_TPKE_PTN = Pattern.compile("\\bPA (?:TPKE|TURNPIKE)\\b", Pattern.CASE_INSENSITIVE);
  
  @Override
  protected boolean isPageMsg(String body) {
    return MARKER.matcher(body).find();
  }

  @Override
  public boolean parseMsg(String body, Data data) {
    
    if (body.startsWith(":")) body = "BUTLER911" + body;
    body = body.replace("TOWNSHIP", "TWP");
    if (! super.parseMsg(body, data)) return false;
    
    data.strCity = stripFieldEnd(data.strCity, " BORO");
    if (data.strCity.endsWith(" T")) data.strCity += "WP";
    data.strCity =  convertCodes(data.strCity, CITY_CONVERSION_TABLE);
    
    if (data.strName.equals("NOT ENTERED")) data.strName = "";
    else {
      data.strName = stripFieldStart(data.strName, "-");
      Matcher match = NAME_COUNTY_PTN.matcher(data.strName);
      if (match.matches()) {
        String county = COUNTY_CONVERSION_TABLE.getProperty(match.group(1));
        if (county != null) {
          data.strCity = append(data.strCity, ", ", county);
          data.strName = match.group(2);
        }
      }
    }
    if (data.strMap.equals("00000,000")) data.strMap = "";
    return true;
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
      "ADAMS POINTE",
      "ADAMS POINTE",
      "ADAMS RIDGE",
      "ADAMS SHOPPES",
      "ALAMEDA PARK",
      "APPLE BLOSSOM",
      "ARMSTRONG HILL",
      "ARMSTRONG RUN",
      "BAUDER MILL",
      "BAUDER SCHOOL",
      "BEACON LIGHT",
      "BEAHM CREST",
      "BEAR CREEK",
      "BENT CREEK",
      "BLACKBERRY HILL",
      "BLAZING STAR",
      "BLUE SPRUCE",
      "BON AIRE",
      "BOY SCOUT",
      "BRIER HILL",
      "BROWNS HILL",
      "BROWNS MILL",
      "BRUIN QUEENSTOWN",
      "BUENA VISTA",
      "BUTLER COMMONS",
      "CAMP TREES",
      "CAMPBELL HOLLOW",
      "CAMPUS SIDE",
      "CANNEL COAL",
      "CANNON HILL",
      "CARBON CENTER",
      "CENTER TWP",
      "CHAPEL RIDGE",
      "CHERRY VALLEY",
      "CHICORA FENELTON",
      "CHRIS BEL",
      "COAL HOLLOW",
      "COMMERCE PARK",
      "COMMONS OF SAXONBURG",
      "CONNOQ SCHOOL",
      "COOL SPRINGS",
      "COUNTRY CLUB",
      "COUNTRY SIDE",
      "COUNTY LINE",
      "COURTNEY MILL",
      "CRAB RUN",
      "CRANBERRY POINTE",
      "CRANBERRY SPRINGS",
      "CRANBERRY SQUARE",
      "CRANBERRY WOODS",
      "CREEK BOTTOM",
      "CRESCENT HILL",
      "CRITCHLOW SCHOOL",
      "DEAHL CREEK",
      "DEER CREEK",
      "EAGLE MILL",
      "EAST BUTLER",
      "EAST RIDGE",
      "EAST VALCORT",
      "EAST VANDERBILT",
      "EAU CLAIRE",
      "ECKERT BRIDGE",
      "EVANS CITY",
      "EVERGREEN MILL",
      "FAIRGROUND HILL",
      "FAIRVIEW MAIN",
      "FAIRVIEW SCHOOL",
      "FIVE OAKS",
      "FOX RUN",
      "FREW MILL",
      "GLADE MILL",
      "GRAHAM SCHOOL",
      "GRANITE RIDGE",
      "GREAT BELT",
      "GROVE CITY",
      "HAINE SCHOOL",
      "HARTZELL SCHOOL",
      "HIGH ACRES",
      "HIGH SCHOOL",
      "IRON BRIDGE",
      "JEFFERSON TWP",
      "JO DEENER",
      "KAYLOR PETROLIA",
      "KITTANNING HOLLOW",
      "LAKE ARTHUR",
      "LAKE SIDE",
      "LAUREL OAK",
      "LEGION MEMORIAL",
      "LIST HILL",
      "LITMAN GROVE",
      "LITTLE CREEK",
      "LITTLE STONE",
      "LOST VALLEY",
      "MAPLE SUGAR",
      "MARS EVANS CITY",
      "MARS VALENCIA",
      "MARY LYNN",
      "MCCALIP FARM",
      "MCCONNELLS MILL",
      "MEADOW LAKE",
      "MEDICAL CENTER",
      "MILLERS EDDY",
      "MITCHELL HILL",
      "MORAINE POINTE",
      "MORNING GROVE",
      "MOUNTAIN LAUREL",
      "MOUNTAIN VIEW",
      "MT NEBO",
      "MUDDY CREEK",
      "MUSHROOM FARM",
      "NEEDLE POINT",
      "NEW CASTLE",
      "NEW HAVEN",
      "NORTH BOUNDARY",
      "NORTH SHORE",
      "NORTH WASHINGTON",
      "NORWEGIAN SPRUCE",
      "OAK HILLS",
      "OAK MANOR",
      "OAK PARK",
      "OAK RIDGE",
      "OFF HESPENHEIDE",
      "ONEIDA VALLEY",
      "OSTERRIED OTTO E",
      "PA TPKE",
      "PEACEFUL VALLEY",
      "PENN WEST",
      "PERSONAL CARE",
      "PINE HAVEN",
      "PINE RIDGE",
      "PINE TRACT",
      "PLAIN GROVE N LIB",
      "PLAINS CHURCH",
      "PLEASANT VALLEY",
      "POINTE VIEW",
      "QUEEN JUNCTION",
      "QUEENS TOWN",
      "RADER SCHOOL",
      "RED BRUSH",
      "ROBINSON RUN",
      "ROCK LAKE",
      "ROCK PRIDE",
      "ROLLING MILLS",
      "ROLLING VALLEY",
      "ROYAL OAK",
      "RUSTIC RIDGE",
      "RUSTIC WOODS",
      "SAINT FRANCIS",
      "SAINT IVES",
      "SAINT JOE",
      "SAINT LAWRENCE",
      "SAINT WENDELIN",
      "SANDY HILL",
      "SANDY POINT",
      "SAWMILL RUN",
      "SCOTT RIDGE",
      "SENCA SCHOOL",
      "SENECA SCHOOL",
      "SETTLERS VILLAGE",
      "SEVEN FIELDS",
      "SEVEN HILLS",
      "SHELTON PLACE",
      "SLIPPERY ROCK",
      "SOUTH LAKE",
      "SOUTHERN VALLEY",
      "SPITHALER SCHOOL",
      "STAR VIEW",
      "STEINER BRIDGE",
      "STONE CHURCH",
      "STONE CREST",
      "STONEY BATTER",
      "STONEY HOLLOW",
      "SUGAR VALLEY",
      "SUN MINE",
      "SUNBURY FIELDS",
      "SWAIN HILL",
      "SWAMP RUN",
      "TALL MAPLES",
      "TEN POINT",
      "THOMSON PARK",
      "THORN HILL",
      "THORN RUN",
      "THREE DEGREE",
      "TOWNSHIP LINE",
      "TREES DALE",
      "UNION CHURCH",
      "VAN BUREN",
      "VETS CLUB",
      "VILLAGE GREEN",
      "VISTA RIDGE",
      "WATTERS STATION",
      "WEST GROVE",
      "WEST JEFFERSON",
      "WEST LIBERTY",
      "WEST PARK",
      "WEST SUNBURY",
      "WHITE OAK",
      "WHITE PINE",
      "WILLIAM FLYNN",
      "WILLIAM FLYNN",
      "WINDY POINT",
      "YELLOW CREEK",
      "ZEHNER SCHOOL"

  };
  
  protected CodeSet buildCallList() {
    return new CodeSet(
        "1ST TRIMESTER HEMORRHAGE OR MI",
        "2ND TRIMESTER HEMORRHAGE OR MI",
        "ABDOMINAL PAIN",
        "ABDOMINAL PAIN",
        "ABNORMAL BEHAVIOR",
        "ABNORMAL BREATHING",
        "ABNORMAL BREATHING (PARTIAL OB",
        "ACCIDENT",
        "AIRCRAFT CRASH / DISTRESS",
        "ALARM/FIRE",
        "ALARM - AUDIBLE",
        "ALARM - PANIC",
        "ALARM / SPRINKLER",
        "ALERT AND BEHAVING NORMALLY",
        "ALERT AND BREATHING NORMALLY",
        "ALERT WITH ABNORMAL BREATHING",
        "ALLERGIC REACTION",
        "ALLERGIES / ENVENOMATIONS",
        "ALTERED LEVEL OF CONSCIOUSNESS",
        "ANY WELL/PROCESS FIRE OR LEAK",
        "ASSAULT / NO INJURIES",
        "ASSIST POLICE",
        "ASSIST WITH EMS",
        "ASSIST WITH FIRE",
        "ATYPICAL SEIZURE",
        "AUTO ALARM TEST",
        "BACK PAIN",
        "BLEEDING",
        "BLOOD PRESSURE ABNORMALITY (AS",
        "BLOOD THINNERS",
        "BOATING EMERGENCY",
        "BREATHING NORMALLY",
        "BREATHING NORMALLY < 35",
        "BREATHING NORMALLY => 35",
        "BREATHING PROBLEMS",
        "BREATHING PROBLEMS",
        "BREATHING UNCERTAIN (AGONAL)",
        "BURGLARY IN PROGRESS",
        "BURNING COMPLAINT",
        "BURNS => 18% BODY AREA",
        "BURNS / EXPLOSION",
        "CAN'T URINATE (WITHOUT ABDOMIN",
        "CARBON MONOXIDE / INHALTATION",
        "CARDIAC HISTORY",
        "CARDIAC OR RESPIRATORY ARREST",
        "CATHETER (IN/OUT WITHOUT HEMOR",
        "CHANGE IN SKIN COLOR",
        "CHANGING COLOR",
        "CHECK WELL BEING",
        "CHEST OR NECK INJURY (WITH DIF",
        "CHEST PAIN => 35",
        "CLAMMY",
        "CO DETECTOR / FIRE RESPONSE",
        "CO DETECTOR / PEOPLE ILL",
        "CONSTIPATION",
        "CONVULSIONS / SEIZURES",
        "CONTINUOUS OR MULTIPLE SEIZURE",
        "DANGEROUS HEMORRHAGE",
        "DETAIL",
        "DIABETIC",
        "DIABETIC PROBLEMS",
        "DIFFICULTY BREATHING OR SWALLO",
        "DIFFICULTY SPEAKING BETWEEN BR",
        "DISABLED VEHICLE",
        "DISTURBANCE",
        "DIZZINESS/VERTIGO",
        "DRILL",
        "DOMESTIC",
        "EFFECTIVE BREATHING NOT VERIFI",
        "EMERGENCY RESPONSE REQUESTED",
        "EMS STAND BY",
        "EMS TRANSPORT",
        "EXPLOSION",
        "FAINTING EPISODE(S) AND ALERT",
        "FAINTING OR NEAR FAINTING => 5",
        "FALLS",
        "FALLS",
        "FEMALES WITH PAIN ABOVE NAVEL",
        "FEVER/CHILLS",
        "FIRE / GRASS OR BRUSH",
        "FIRE / CHIMNEY",
        "FIRE / DUMPSTER",
        "FIRE / POLE",
        "FIRE / UNKNOWN",
        "FIRE - STRUCTURE",
        "FIRE - VEHICLE",
        "FLARING OF GAS WELL",
        "FLOODING / BASEMENT",
        "FLOODING / GENERAL",
        "FLOODING / ROAD",
        "FOCAL SEIZURE (ALERT)",
        "FOCAL SEIZURE (NOT ALERT)",
        "GENERAL WEAKNESS",
        "HANG UP",
        "HAZARDOUS ROAD CONDITION",
        "HEAD VISIBLE/OUT",
        "HEART ATTACK OR ANGINA HISTORY",
        "HEART PROBLEMS",
        "HEART RATE < 50 BPM OR => 130",
        "HEART RATE => 50 BPM AND < 130",
        "HEAT / COLD EXPOSURE",
        "HEMORRHAGE OF DIALYSIS FISTULA",
        "HEMORRHAGE THROUGH TUBES",
        "HISTORY OF SEVERE ALLERGIC REA",
        "IMMINENT DELIVERY (=> 5 MONTHS",
        "INACCESSIBLE INCIDENT / OTHER",
        "INEFFECTIVE BREATHING",
        "INJURED PERSON",
        "INTOXICATED PERSON",
        "LIFE STATUS QUESTIONABLE",
        "LONG FALL",
        "MALES WITH PAIN ABOVE NAVEL => 223",
        "MALES WITH PAIN ABOVE NAVEL => 376",
        "MEDICAL ALARM (ALERT) NOTIFICA",
        "MEDICAL ALARM",
        "MENTAL PATIENT",
        "MODERATE EYE INJURIES",
        "NAUSEA",
        "NEW ONSET OF IMMOBILITY",
        "NO DIFFICULTY BREATHING OR SWA",
        "NON-RECENT (=> 6HRS) INJURIES",
        "NON-RECENT (=> 6HRS) TRAUMATIC",
        "NON-SUICIDAL AND ALERT",
        "NON-TRAUMATIC BACK PAIN",
        "NO PRIORITY SYMPTOMS (COMPLAIN",
        "NO PRIORITY SYMPTOMS (COMPLAIN `85",
        "NOT ALERT",
        "NOT BREATHING AT ALL",
        "NOT CHOKING NOW (CAN TALK OR C",
        "NOT DANGEROUS BODY AREA",
        "NOT DANGEROUS HEMORRHAGE",
        "NOTIFICATION - EMS",
        "NOTIFICATION - FIRE",
        "NOT SEIZING NOW AND EFFECTIVE",
        "NUMBNESS",
        "OBVIOUS OR EXPECTED DEATH QUES",
        "ODOR OF GAS IN A RESIDENCE",
        "OTHER PAIN",
        "OUT OF SERVICE",
        "OVERDOSE / POISONING (INGESTIO",
        "PERSON MISSING",
        "PHONE CALL",
        "POLE DOWN OR BROKEN",
        "POSSIBLY DANGEROUS BODY AREA",
        "POSSIBLY DANGEROUS HEMORRHAGE",
        "PROBLEM UNKNOWN",
        "PSYCHIATRIC",
        "PSYCHIATRIC / ABNORMAL BEHAVIO",
        "PSYCHIATRIC/OVERDOSE",
        "PSYCHIATRIC PROBLEM",
        "PUBLIC ASSIST (NO INJURIES AND",
        "RECKLESS DRIVING",
        "RETAIL THEFT",
        "ROAD CLOSED",
        "ROAD HAZARD",
        "SEIZURES/CONVULSIONS",
        "SERIOUS HEMORRHAGE",
        "SERVICE CALL",
        "SICK PERSON",
        "SMOKE INVESTIGATION",
        "STAB / GUNSHOT / PENETRATING T",
        "STANDING SITTING MOVING OR TAL",
        "STROKE (CVA)",
        "STROKE/CVAV/TIA",
        "SUDDEN ONSET OF SEVERE PAIN",
        "SUDDEN SPEECH PROBLEMS",
        "SUDDEN WEAKNESS OR NUMBNESS (O",
        "SUPERFICIAL BITES",
        "SUSPICIOUS ACTIVITY",
        "SWARMING ATTACK (BEE WASP HORN",
        "THREATENING SUICIDE",
        "TOOTHACHE (WITHOUT JAW PAIN)",
        "TRAFFIC CONTROL",
        "TRAFFIC / TRANSPORTATION ACCID",
        "TRANSPORTATION ONLY",
        "UNCONSCIOUS",
        "UNCONSCIOUS -- AGONAL/INEFFECT",
        "UNCONSCIOUS -- EFFECTIVE BREAT",
        "UNCONSCIOUS OR ARREST",
        "UNEXPECTED CALL CODE:SUDDEN WEAKNESS OR NUMBNESS (O",
        "UNKNOWN STATUS/OTHER CODES NOT",
        "UNWELL/ILL",
        "VA/ENTRAPMENT",
        "VA / FIRE",
        "VA / INJURIES",
        "VA / MOTORCYCLE",
        "VA / MOTORCYCLE EAST",
        "VA / UNKNOWN INJURY",
        "VA / UNKNOWN INJURY WILLIAM",
        "VEHICLE ACCIDENT",
        "VOMITING",
        "WATER PROBLEMS",
        "WIRES DOWN",
        "WOUND INFECTED (FOCAL OR SURFA"
    );
  }
  
  private static final String[] CITY_LIST = new String[]{
    "BUTLER",
    
    "BRUIN BORO",
    "CALLERY BORO",
    "CHERRY VALLEY BORO",
    "CHICORA BORO",
    "CONNOQ BORO",
    "CONNOQUENESSING BORO",
    "EAST BUTLER BORO",
    "EAU CLAIRE BORO",
    "EVANS CITY BORO",
    "FAIRVIEW BORO",
    "HARMONY BORO",
    "HARRISVILLE BORO",
    "KARNS CITY BORO",
    "MARS BORO",
    "PETROLIA BORO",
    "PORTERSVILLE BORO",
    "PROSPECT BORO",
    "SAXONBURG BORO",
    "SEVEN FIELDS BORO",
    "SLIPPERY ROCK BORO",
    "VALENCIA BORO",
    "WEST LIBERTY BORO",
    "WEST SUNBURY BORO",
    "ZELIENOPLE BORO",
    
    "ADAMS TWP",
    "ALLEGHENY TWP",
    "BRADY TWP",
    "BUFFALO TWP",
    "BUTLER TWP",
    "CENTER TWP",
    "CHERRY TWP",
    "CLAY TWP",
    "CLEARFIELD TWP",
    "CLINTON TWP",
    "CONCORD TWP",
    "CONNOQ TWP",
    "CONNOQUENESSING TWP",
    "CRANBERRY TWP",
    "CRANBERRY TOWNSHIP",
    "DONEGAL TWP",
    "FAIRVIEW TWP",
    "FORWARD TWP",
    "FRANKLIN TWP",
    "JACKSON TWP",
    "JEFFERSON TWP",
    "LANCASTER TWP",
    "MARION TWP",
    "MERCER TWP",
    "MIDDLESEX TWP",
    "MUDDY CREEK TWP",
    "MUDDYCREEK TWP",   // Dispatch typo
    "OAKLAND TWP",
    "PARKER TWP",
    "PENN TWP",
    "SLIPPERY ROCK T",
    "SLIPPERY ROCK TWP",
    "SUMMIT TWP",
    "VENANGO TWP",
    "WASHINGTON TWP",
    "WINFIELD TWP",
    "WORTH TWP",
    
    "BOYERS",
    "EIDENAU",
    "HILLIARDS",
    "MURRINSVILLE",
    "RENFREW",
    "SARVER",
    "WAHLVILLE",
    "WATTERS",
    
    // Counties
    "ALLEGHENY COUNTY",
    "BEAVER COUNTY",
    "CLARION COUNTY",
    "LAWRENCE COUNTY",
    "MERCER COUNTY",
    "VENANGO COUNTY",
    "WESTMORELAND COUNTY",
    
    // out of county locations
    "EAST FRNKLIN TWP",
    "ELLWOOD CITY",
    "EMLENTON BORO",
    "FOXBERG BORO",
    "FOXBURG BORO",
    "FREEPORT BORO",
    "HICKORY TWP",
    "HOVE TWP",
    "HOVEY TWP",
    "IRWIN TWP",
    "LIBERTY TWP",
    "MARSHALL T", 
    "MARSHALL TWP",
    "MARSHALL",
    "NEW CASTLE",
    "NEW SEWICKLEY",
    "PARKER CITY",
    "PERRY TWP",
    "PINE TWP",
    "PLAIN GROVE TWP",
    "RICHLAND",
    "RICHLAND TWP",
    "SCOTT TWP",
    "SL ROCK TWP",
    "SLIPPERY ROCK TW",
    "SUGARCREEK REST",
    "SUGAR CREEK TWP",
    "SUGARCREEK T",
    "SUGARCREEK TWP",
    "WEST DEER TWP"
  };
  
  private static final Properties CITY_CONVERSION_TABLE = buildCodeTable(new String[]{
      "CONNOQ",                   "CONNOQUENESSING",
      "CONNOQ TWP",               "CONNOQUENESSING TWP",
      "EAST FRNKLIN TWP",         "EAST FRANKLIN TWP",
      "FOXBERG",                  "FOXBURG",
      "MARSHALL T",               "MARSHALL TWP", 
      "MARSHALL",                 "MARSHALL TWP",
      "MUDDYCREEK TWP",           "MUDDY CREEK TWP",
      "RICHLAND",                 "RICHLAND TWP",
      "SL ROCK TWP",              "SLIPPERY ROCK TWP",
      "SLIPPERY ROCK TW",         "SLIPPERY ROCK TWP",
      "SUGAR CREEK TWP",          "SUGARCREEK TWP",
      "SUGARCREEK REST",          "SUGARCREEK TWP",
      "SUGARCREEK T",             "SUGARCREEK TWP"
  });
  
  private static final Properties COUNTY_CONVERSION_TABLE = buildCodeTable(new String[]{
      "AGC",            "ALLEGHENY COUNTY",
      "ALLEG",          "ALLEGHENY COUNTY",
      "ALLEGHENY",      "ALLEGHENY COUNTY",
      "ARMSTRONG",      "ARMSTRONG COUNTY",
      "BEAVER",         "BEAVER COUNTY",
      "CLARION",        "CLARION COUNTY",
      "LAWRENCE",       "LAWRENCE COUNTY",
      "LEOC",           "LAWRENCE COUNTY",
      "LEOZ",           "LAWRENCE COUNTY",
      "MERCER",         "MERCER COUNTY",
      "VENANGO",        "VENANGO COUNTY",
      "WESTMORELAND",   "WESTMORELAND COUNTY"
      
  });
}
