package net.anei.cadpage.parsers.PA;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchB2Parser;

/**
 * Fayette County, Pennsylvania
 */
public class PAFayetteCountyAParser extends DispatchB2Parser {

  public PAFayetteCountyAParser() {
    super("FAYETTE-911:", -5, CITY_LIST, "FAYETTE COUNTY", "PA");
    setupCallList(CALL_LIST);
    setupMultiWordStreets(MWORD_STREET_LIST);
  }
  
  @Override
  public String getFilter() {
    return "FAYETTE-911@fcema.org";
  }
  
  @Override
  public Field getField(String name) {
    if (name.equals("CALL_ADDR")) return new MyCallAddressField();
    return super.getField(name);
  }
  
  private class MyCallAddressField extends BaseCallAddressField {
    @Override
    public void parse(String field, Data data) {
      field = field.replace('@', '&');
      super.parse(field, data);
    }
  }
  
  private static final String[] MWORD_STREET_LIST = new String[]{
      "4TH EASY",
      "AIRWAY INN",
      "ALBERT KAISER MEMORIAL",
      "ARCH BRIDGE",
      "B WATER",
      "BACK CREEK",
      "BALL FIELD",
      "BALL PARK",
      "BARTON HOLLOW",
      "BARTON MILL",
      "BEAR RUN",
      "BELL GROVE",
      "BELL VIEW",
      "BELLE VIEW",
      "BEN LOMOND",
      "BIG 6",
      "BLUE STAR",
      "BOBISH FARM",
      "BRADDOCK VIEW",
      "BRAZNELL HILL",
      "BRIER CREEK",
      "BUENA VISTA",
      "BUKOVITZ FARM",
      "BULL RUN",
      "BUNKER HILL",
      "CAMP ACHIEVEMENT",
      "CAMP CARMEL",
      "CAMP RIAMO",
      "CANAAN CHURCH",
      "CENTRAL SCHOOL",
      "CHALK HILL OHIOPYLE",
      "CHERRY TREE",
      "CLUB SOPHIA",
      "COLVIN RUN",
      "COOLSPRING JUMONVILLE",
      "COON HOLLOW",
      "COUNTY LINE",
      "CRAFT MOORE",
      "CUNNINGHAM SCHOOL",
      "DARK HOLLOW",
      "DAVIDSON SIDING",
      "DICKERSON RUN",
      "DINNER BELL FIVE FORKS",
      "DINNER BELL OHIOPYLE",
      "DINNER BELL",
      "DONEGAL LAKE",
      "DRY HILL",
      "DUCK HOLLOW",
      "DUCK POND",
      "EAST GATE",
      "ELM GROVE",
      "EUREKA HILL",
      "FAIRBANK HERBERT",
      "FAN HOLLOW",
      "FARMINGTON OHIOPYLE",
      "FAYETTE CITY",
      "FAYETTE SPRINGS",
      "FERN MOUNTAIN",
      "FIKE HOLLOW",
      "FILBERT ORIENT",
      "FIRE SCHOOL",
      "FIRE TOWER",
      "FLAT ROCK",
      "FORKY FORD",
      "FORT HILL",
      "FRENCH ISLAND",
      "FURNACE HILL",
      "GALLAGHER WOODS",
      "GEORGE PRINKEY",
      "GEORGES FAIRCHANCE",
      "GIBBON GLADE",
      "GILLESPIE HOLLOW",
      "GLENDALE CHURCH",
      "GOAT HILL",
      "GREEN JUNCTION",
      "GUN CLUB",
      "HALF KING COLONY",
      "HARDIN HOLLOW",
      "HARDY HILL",
      "HARMONY CHURCH",
      "HARTLEY HILL",
      "HAWKINS HOLLOW",
      "HICKORY SQUARE",
      "HIGHLAND PARK",
      "HILL FARM",
      "HOLLAND HILL",
      "HOPWOOD COOLSPRING",
      "INDIAN CREEK VALLEY",
      "INDIAN HEAD",
      "INDUSTRIAL PARK",
      "JIM MOUNTAIN",
      "JOHN ASH",
      "JOHN HENRY",
      "JOHNSON HOLLOW",
      "KINGIN HILL",
      "LAKE FRONT",
      "LAMBERT FOOTEDALE",
      "LARMAN MILL",
      "LAUREL HILL",
      "LAUREL VIEW",
      "LAURITA HILL",
      "LECKRONE HIGHOUSE",
      "LECKRONE MASONTOWN",
      "LEISENRING VANDERBILT",
      "LIMESTONE HILL",
      "LINDEN HALL",
      "LITTLE SUMMIT",
      "MAE WEST",
      "MAPLE FARM",
      "MAPLE SUMMIT",
      "MARY HALL",
      "MASON DIXON",
      "MCCOY HOLLOW",
      "MEADOW RUN",
      "MILL RUN",
      "MORGAN STATION",
      "MORRIS HOLLOW",
      "MOUNT VERNON",
      "MOUNT ZION",
      "MOUNTAIN VIEW",
      "MT PLEASANT CONNELLSVILLE",
      "MT VERNON",
      "MT VIEW",
      "NARROWS HILL",
      "NAVAHO HOLLOW",
      "NEMACOLIN WOODLANDS",
      "OAK CREEK",
      "OAK HILL",
      "PALMER ADAH",
      "PINE HILL",
      "PINE RIDGE",
      "PIPER HOLLOW",
      "PLEASANT VALLEY",
      "PLEASANT VIEW SMOCK",
      "PRESSLEY RIDGE",
      "PRISON CAMP",
      "QUAIL HILL",
      "QUARKER CHURCH",
      "RALPH NEW SALEM",
      "REDSTONE CHURCH",
      "REDSTONE WAY",
      "REHOBOTH CHURCH",
      "RICES LANDING",
      "RICH HILL",
      "ROCKY RUN",
      "RODERS MILL",
      "RODGERS MILL",
      "ROGERS MILL",
      "ROLLING HILLS",
      "ROSE CREST",
      "ROSE GARDEN",
      "ROSY HILL",
      "ROUND BARN",
      "ROUND TOP",
      "ROUTE 51",
      "ROWES RUN",
      "RT 21",
      "RUBLE MILL",
      "SANDY FLAT",
      "SANDY HOLLOW",
      "SCHOOL HOUSE",
      "SCOTTDALE SMITHTON",
      "SEARIGHTS HERBERT",
      "SHADY GROVE",
      "SHIMKO HOLLOW",
      "SICKLE RIDGE",
      "SLAUGHTER HOUSE",
      "SMITH SCHOOL",
      "SMITHFIELD HIGHHOUSE",
      "SMITHFIELD NEW GENEVA",
      "SNYDER MOBILE HOME",
      "STONE CHURCH",
      "STONEY POINT",
      "STREET CAR",
      "SUFF RIDGE",
      "SUGAR LOAF",
      "SUGAR RUN",
      "SUNSHINE HOLLOW",
      "SURREY HILL",
      "SWINK HILL",
      "SWISS HEIGHTS",
      "TANYARD HOLLOW",
      "THOMPSON 1",
      "THOMPSON 2",
      "TOWER HILL",
      "TOWN COUNTRY",
      "TRAILER COURT",
      "TREE FARM",
      "TWIN HILLS",
      "VALLEY FORGE",
      "VALLEY SCHOOL",
      "VALLEY VIEW",
      "VANCES MILL",
      "WALNUT HILL",
      "WATER TANK",
      "WAYLAND SMITH",
      "WEAVER MILL",
      "WHARTON FURNACE",
      "WICKHAVEN HOLLOW",
      "WILLIAM PENN",
      "WINDY HILL",
      "WIRSING SCHOOL",
      "WYMPS GAP",
      "YAUGER HOLLOW",
      "YORK RUN",
  };
  
  private static final CodeSet CALL_LIST = new CodeSet(
      "911 HANGUP",
      "AED CARDIAC ARREST ALS",
      "AED SEIZURE ALS",
      "AED UNRESPONSIVE ALS",
      "AUTOMATIC FIRE ALARM COMERCIAL",
      "AUTOMATIC FIRE ALARM RESIDENCE",
      "CARDIAC ARREST ALS",
      "E ABDOMINAL PAIN ALS",
      "E_ALLERGIC ALS",
      "E_ALLERGIC BLS",
      "E_BACK PAIN BLS",
      "E BURNS ALS",
      "E CHEST PAINS ALS",
      "E CHOKING ALS",
      "E DIABETIC ALS",
      "E FALLS ALS",
      "E FALLS BLS",
      "E HEADACHE ALS",
      "E MED ALARM ALS",
      "E OB GYN ALS",
      "E POISON/OVERDOSE ALS",
      "E PUBLIC SERVICE BLS",
      "E PSYCH/MENTAL/EMOTIONAL ALS",
      "E SEIZURE ALS",
      "E SHOT ALS",
      "E SICK BLS",
      "E SICK/UNKNOWN ALS",
      "E STROKE ALS",
      "E TRAUMA ALS",
      "E TRAUMA BLS",
      "E UNRESP/UNCONSC/SYNCOPE ALS",
      "E_ASSIST",
      "E_BACK PAIN ALS",
      "E_BLEEDING ALS",
      "E_BREATHING ALS",
      "F-ACCIDENT W/ INJURIES",
      "F_ACCIDENT NO INJURIES",
      "F_ACCIDENT W/ ENTRAPTMENT",
      "F_ASSIST",
      "F_BRUSH FIRE",
      "F_CARBON MONOXIDE NO SYMPTOMS",
      "F_CARBON MONOXIDE W/ SYMPTOMS",
      "F_CHIMNEY FIRE",
      "F_CONTROL BURN",
      "F_DUMPSTER FIRE",
      "F_DRILL",
      "F_ELECTRICAL FIRE",
      "F_EXPLOSION 2",
      "F_FLOODING",
      "F_FUEL SPILL",
      "F_GAS LEAK",
      "F_ILLEGAL BURN",
      "F_INFORMATION",
      "F_LANDING ZONE",
      "F_MISC FIRE",
      "F_MISC RESCUE",
      "F_MULT CALLS",
      "F_ODOR INVESTIGATION",
      "F_PEDESTRIAN ACCIDENT",
      "F_PHYSICAL RESCUE",
      "F_PUBLIC SERVICE",
      "F_REKINDLE",
      "F_ROAD HAZZARD",
      "F_SEARCH",
      "F_SIREN TEST",
      "F_STRUCTURE FIRE COMMERCIAL",
      "F_STRUCTURE FIRE",
      "F_TRAFFIC CONTROL",
      "F_TRASH FIRE",
      "F_TREE DOWN",
      "F_UNKNOWN FIRE",
      "F_WATER RESCUE",
      "F_WIRES DOWN",
      "H HUMAN SERVICES",
      "P ALARM OTHER",
      "P ASSIST",
      "P ASSAULT 2",
      "P ASSAULT 3",
      "P BURNING COMPLAINT",
      "P CHECK ON WELFARE",
      "P CRIMINAL MISCHIEF",
      "P DEAD ON ARRIVAL",
      "P DISABLED VEHICLE",
      "P DISTURBANCE",
      "P DOMESTIC",
      "P_FOLLOW UP",
      "P HIT AND RUN",
      "P LOCK OUT",
      "P MISC",
      "P MULTIPLE CALLS",
      "P RUNAWAY",
      "P SEXUAL ASSAULT",
      "P SUSPICIOUS ACTIVITY",
      "P TRAFFIC HAZARD",
      "PURSUIT/CHASE",
      "SMOKE STRUCTURE",
      "TEST CAD EVENT",
      "TEST CALL",
      "VEHICLE FIRE"

  );
  
  private static final String[] CITY_LIST = new String[]{
      "CONNELLSVILLE",
      "CONNELLSVILLE CITY",
      "UNIONTOWN",
  
      "BELLE VERNON",
      "BROWNSVILLE",
      "DAWSON",
      "DUNBAR",
      "EVERSON",
      "FAIRCHANCE",
      "FAYETTE CITY",
      "MARKLEYSBURG",
      "MASONTOWN",
      "NEWELL",
      "OHIOPYLE",
      "PERRYOPOLIS",
      "POINT MARION",
      "SEVEN SPRINGS",
      "SMITHFIELD",
      "SOUTH CONNELLSVILLE",
      "VANDERBILT",
    
      "BROWNSVILLE TWP",
      "BULLSKIN",
      "CONNELLSVILLE TWP",
      "DUNBAR TWP",
      "FRANKLIN",
      "GEORGES",
      "GERMAN",
      "HENRY CLAY",
      "JEFFERSON",
      "LOWER TYRONE",
      "LUZERNE",
      "MENALLEN",
      "NICHOLSON",
      "NORTH UNION",
      "PERRY",
      "REDSTONE",
      "SALTLICK",
      "SOUTH UNION",
      "SPRINGFIELD",
      "SPRINGHILL",
      "STEWART",
      "UPPER TYRONE",
      "WASHINGTON",
      "WHARTON"
  };
}
