package net.anei.cadpage.parsers.PA;

import java.util.Properties;

import net.anei.cadpage.parsers.MsgInfo;
import net.anei.cadpage.parsers.dispatch.DispatchA45Parser;

public class PANorthumberlandCountyParser extends DispatchA45Parser {
  
  public PANorthumberlandCountyParser() {
    super(CITY_CODES, "NORTHUMBERLAND COUNTY", "PA");
  }
  
  @Override
  public String getFilter() {
    return "@northumberland.alertpa.org,777";
  }

  @Override
  protected boolean parseMsg(String body, MsgInfo.Data data) {
    int pt = body.indexOf("<div style=");
    if (pt >= 0) body = body.substring(0,pt).trim();
    return super.parseMsg(body, data);
  }

  @Override
  public Field getField(String name) {
    if (name.equals("ID")) return new IdField("\\d{10}", true);
    return super.getField(name);
  }

  @Override
  public String adjustMapCity(String city) {
    if (city.equals("POINT TWP")) city += ",NORTHUMBERLAND COUNTY";
    return city;
  }
  
  private static final Properties CITY_CODES = buildCodeTable(new String[]{
      "CBB", "BENTON",
      "CBC", "BRIAR CREEK TWP",
      "CBE", "BEAVER TWP",
      "CBK", "BERWICK",
      "CBL", "BLOOMSBURG",
      "CBN", "BENTON TWP",
      "CBR", "BRIAR CREEK",
      "CCB", "CATAWISSA",
      "CCE", "CENTRALIA",
      "CCL", "CLEVELAND TWP",
      "CCN", "CENTRE-N TWP",
      "CCO", "CONYNGHAM TWP",
      "CCS", "CENTRE-S TWP",
      "CCT", "CATAWISSA TWP",
      "CFI", "FISHING CREEK TWP",
      "CFR", "FRANKLIN TWP",
      "CGR", "GREENWOOD TWP",
      "CHE", "HEMLOCK TWP",
      "CJA", "JACKSON TWP",
      "CLO", "LOCUST TWP",
      "CMA", "MADISON TWP",
      "CMB", "MILLVILLE",
      "CMI", "MIFFLIN TWP",
      "CMN", "MAIN TWP",
      "CMO", "MONTOUR TWP",
      "CMP", "MOUNT PLEASANT TWP",
      "COA", "COAL",
      "COB", "ORANGEVILLE",
      "COR", "ORANGE TWP",
      "CPI", "PINE TWP",
      "CRO", "ROARING CREEK TWP",
      "CSC", "SCOTT TWP",
      "CST", "STILLWATER",
      "CSU", "SUGARLOAF TWP",
      "DBE", "BERRYSBURG",
      "DEL", "ELIZABETHVILLE",
      "DET", "DELAWARE",
      "DGR", "GRATZ",
      "DHA", "HALIFAX",
      "DHT", "HALIFAX TWP",
      "DJE", "JEFFERSON TWP",
      "DJT", "JACKSON TWP",
      "DLT", "LYKENS TWP",
      "DLY", "LYKENS",
      "DMI", "MILLERSBURG",
      "DMT", "MIFFLIN TWP",
      "DPI", "PILLOW",
      "DRE", "REED TWP",
      "DRU", "RUSH TWP",
      "DUP", "UPPER PAXTON TWP",
      "DWA", "WASHINGTON TWP",
      "DWC", "WICONISCO TWP",
      "DWI", "WILLIAMSTOWN",
      "DWT", "WILLIAM TWP",
      "DWY", "WAYNE TWP",
      "EAS", "EAST CAMERON",
      "ECT", "EAST CHILLISQUAQUE",
      "HER", "HERNDON",
      "JAC", "JACKSON",
      "JBE", "BEAGLE TWP",
      "JDE", "DELEWARE TWP",
      "JFA", "FAYETTE TWP",
      "JFE", "FERMANAGH TWP",
      "JGR", "GREENWOOD TWP",
      "JLA", "LACK TWP",
      "JMB", "MIFFLIN",
      "JMI", "MIFFLINTOWN",
      "JMO", "MONROE TWP",
      "JMT", "MILFORD TWP",
      "JOR", "JORDAN",
      "JPR", "PORT ROYAL",
      "JSP", "SPRUCE HILL TWP",
      "JSU", "SUSQUEHANNA TWP",
      "JTH", "THOMPSONTOWN",
      "JTT", "TUSCARORA TWP",
      "JWT", "WALKER TWP",
      "JYU", "TURBETT TWP",
      "KAS", "ASHLAND",
      "KAU", "AUBURN",
      "KBA", "BARRY TWP",
      "KBL", "BLYTHE TWP",
      "KBR", "BRANCH TWP",
      "KBU", "BUTLER TWP",
      "KCA", "CASS TWP",
      "KCO", "COALDALE",
      "KCR", "CRESSONA",
      "KDE", "DELANO TWP",
      "KDL", "DEER LAKE",
      "KEB", "EAST BRUNSWICK TWP",
      "KEL", "ELDRED TWP",
      "KEN", "EAST NOREGIAN TWP",
      "KEU", "EAST UNION TWP",
      "KFO", "FOSTER TWP",
      "KFR", "FRACKVILLE",
      "KFR", "FRAILEY TWO",
      "KGB", "GIRARDVILLE",
      "KGI", "GILBERTON",
      "KGO", "GORDON",
      "KHE", "HEGINS TWP",
      "KHU", "HUBLEY TWP",
      "KKL", "KLINE TWP",
      "KLA", "LANDINGVILLE",
      "KMA", "MAHONY CITY",
      "KMB", "MINERSVILLE",
      "KMC", "MCADOO",
      "KME", "MECHANICSVILLE",
      "KMI", "MIDDLEPORT",
      "KMN", "MT CARBON",
      "KMT", "MAHONY TWP",
      "KNC", "NEW CASTLE TWP",
      "KNN", "NORTH MANHEIM TWP",
      "KNO", "NORWEGIAN TWP",
      "KNP", "NEW PHILADEPLPHIA",
      "KNR", "NEW RINGGOLD",
      "KNU", "NORTH UNION TWP",
      "KOR", "ORWIGSBURG",
      "KPA", "PALO ALTO",
      "KPB", "POTTSVILLE",
      "KPC", "PORT CARBON",
      "KPG", "PINE GROVE",
      "KPO", "PORT CLINTON",
      "KPR", "PORTER TWP",
      "KPT", "PINE GROVE TWP",
      "KRE", "REILLY TWP",
      "KRI", "RINGTOWN",
      "KRU", "RUSH TWP",
      "KRY", "RYAN TWP",
      "KSB", "SHENANDOAH",
      "KSC", "ST CLAIR",
      "KSH", "SCHUYLKILL HAVEN",
      "KSM", "SOUTH MANHEIM",
      "KST", "SCHUYKILL TWP",
      "KTA", "TAMAQUA",
      "KTB", "TREMONT",
      "KTO", "TOWER CITY",
      "KTR", "TREMONT TWP",
      "KUL", "KULPMONT",
      "KUM", "UPPER MAHANTONGO TWP",
      "KUN", "UNION TWP",
      "KWA", "WALKER TWP",
      "KWB", "WEST BRUNSWICK TWP",
      "KWM", "WEST MAHONY TWP",
      "KWP", "WEST PENN TWP",
      "KWT", "WAYNE TWP",
      "LA0", "ANTHONY TWP",
      "LA1", "ARMSTRONG TWP",
      "LB2", "BASTRESS TWP",
      "LB3", "BRADY TWP",
      "LB4", "BROWN TWP",
      "LC5", "CASCADE TWP",
      "LC6", "CLINTON TWP",
      "LC7", "COGAN HOUSE TWP",
      "LC8", "CUMMINGS TWP",
      "LD1", "DUBOISTOWN",
      "LE9", "ELDRED TWP",
      "LET", "LEWIS",
      "LF0", "FAIRFIELD TWP",
      "LF1", "FRANKLIN TWP",
      "LG2", "GAMBLE TWP",
      "LH2", "HUGHESVILLE",
      "LH3", "HEPBURN TWP",
      "LIT", "LITTLE MAHANOY",
      "LJ3", "JERSEY SHORE",
      "LJ4", "JACKSON TWP",
      "LJ5", "JORDAN TWP",
      "LL6", "LEWIS TWP",
      "LL7", "LIMESTONE TWP",
      "LL8", "LOYALSOCK TWP",
      "LL9", "LYCOMING TWP",
      "LM0", "MCHENRY TWP",
      "LM1", "MCINTYRE TWP",
      "LM2", "MCNETT TWP",
      "LM3", "MIFFLIN TWP",
      "LM4", "MILL CREEK TWP",
      "LM4", "MONTGOMERY",
      "LM5", "MONTOURSVILLE",
      "LM5", "MORELAND TWP",
      "LM6", "MUNCY TWP",
      "LM6", "MUNCY",
      "LM7", "MUNCY CREEK TWP",
      "LN8", "NIPPENOSE TWP",
      "LO9", "OLD LYCOMING TWP",
      "LOA", "LOWER AUGUSTA",
      "LOM", "LOWER MAHANOY",
      "LP0", "PENN TWP",
      "LP1", "PIATT TWP",
      "LP2", "PINE TWP",
      "LP3", "PLUNKETTS CREEK TWP",
      "LP4", "PORTER TWP",
      "LP7", "PICTURE ROCKS",
      "LS5", "SHREWSBURY TWP",
      "LS6", "SUSQUEHANNA TWP",
      "LS8", "SALLADASBURG",
      "LS9", "SOUTH WILLIAMSPORT",
      "LU7", "UPPER FAIRFIELD TWP",
      "LW0", "WOLF TWP",
      "LW0", "WILLIAMSPORT CITY",
      "LW1", "WOODWARD TWP",
      "LW8", "WASHINGTON TWP",
      "LW9", "WATSON TWP",
      "MAN", "ANTHONY TWP",
      "MAR", "MARION HEIGHTS",
      "MCE", "MCEWENSVILLE",
      "MCO", "COOPER TWP",
      "MCT", "MOUNT CARMEL TWP",
      "MDA", "DANVILLE",
      "MDE", "DERRY TWP",
      "MIL", "MILTON",
      "MLI", "LIBERTY TWP",
      "MLT", "LIMESTONE TWP",
      "MMA", "MAHONING TWP",
      "MMT", "MAYBERRY TWP",
      "MTC", "MOUNT CARMEL",
      "MVA", "VALLEY",
      "MWA", "WASHINGTON VILLE",
      "MWH", "WEST HEMLOCK TWP",
      "NOB", "NORTHUMBERLAND",
      "NOR", "NORTHUMBERLAND COUNTY",
      "PBL", "BLAIN",
      "PBU", "BUFFOLO TWP",
      "PCA", "CARROLL TWP",
      "PCE", "CENTRE TWP",
      "PDU", "DUNCANNON",
      "PGR", "GREENWOOD TWP",
      "PHO", "HOWE TWP",
      "PIL", "PILLOW",
      "PJA", "JACKSON TWP",
      "PJU", "JUNIATA TWP",
      "PLA", "LANDISBURG",
      "PLI", "LIVERPOOL",
      "PLT", "LIVERPOOL TWP",
      "PMA", "MARYSVILLE",
      "PMB", "MILLERSTOWN",
      "PMT", "MILLER TWP",
      "PNB", "NEW BLOOMFIELD",
      "PNE", "NEWPORT",
      "PNM", "N.E. MADISON TWP",
      "PNO", "NEW BUFFOLO",
      "POI", "POINT TWP",
      "POL", "OLIVER TWP",
      "PPE", "PENN TWP",
      "PRY", "RYE TWP",
      "PSA", "SAVILLE TWP",
      "PSM", "S.W. MADISON TWP",
      "PSP", "SPRING TWP",
      "PTO", "TOBOYNE TWP",
      "PTU", "TUSCARORA TWP",
      "PTY", "TYRONE TWP",
      "PWA", "WATTS TWP",
      "PWH", "WHEATFIELD TWP",
      "RAL", "RALPHO",
      "RIV", "RIVERSIDE",
      "ROC", "ROCKEFELLER",
      "RUS", "RUSH",
      "SHA", "SHAMOKIN",
      "SHT", "SHAMOKIN TWP",
      "SNY", "SNYDERTOWN",
      "SUN", "SUNBURY",
      "TUR", "TURBOTVILLE",
      "TUT", "TURBOT",
      "UBU", "BUFFALO TWP",
      "UEB", "EAST BUFFALO TWP",
      "UGR", "GREGG TWP",
      "UHA", "HARLTETON",
      "UHY", "HARTLEY TWP",
      "UKE", "KELLY TWP",
      "ULE", "LEWISBURG",
      "ULI", "LIMESTONE TWP",
      "ULS", "LEWIS TWP",
      "UMI", "MIFFLINBURG",
      "UNB", "NEW BERLIN",
      "UPA", "UPPER AUGUSTA",
      "UPM", "UPPER MAHANOY",
      "UUN", "UNION TWP",
      "UWB", "WEST BUFFALO TWP",
      "UWD", "WHITE DEER TWP",
      "VTM", "VALLEY TWP",
      "WAS", "WASHINGTON",
      "WAT", "WATSONTOWN",
      "WCT", "WEST CHILLISQUAQUE",
      "WES", "WEST CAMERON",
      "YAD", "ADAMS TWP",
      "YBE", "BEAVERTOWN",
      "YBT", "BEAVER TWP",
      "YCE", "PENNS CREEK",
      "YCH", "CHAPMAN TWP",
      "YFR", "FREEBURG",
      "YFT", "FRANKLIN TWP",
      "YJA", "KRATZERVILLE",
      "YMB", "MCCLURE",
      "YMC", "KREAMER",
      "YMI", "MIDDLEBURG",
      "YMO", "HUMMELS WHARF",
      "YPE", "MT PLEASANT MILLS",
      "YPT", "PENN TWP",
      "YSE", "SELINGSGROVE",
      "YSH", "SHAMOKIN DAM",
      "YSP", "BEAVERSPINGS",
      "YUN", "PORT TREVORTON",
      "YWA", "WASHINGTON TWP",
      "YWB", "BANNER VILLE",
      "YWP", "WEST PERRY TWP",
      "ZER", "ZERBE"

  });
}
