package net.anei.cadpage.parsers.PA;

import net.anei.cadpage.parsers.CodeSet;
import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA48Parser;


public class PATiogaCountyParser extends DispatchA48Parser {

  public PATiogaCountyParser() {
    super(CITY_LIST, "TIOGA COUNTY", "PA", FieldType.NONE, A48_NO_CODE);
    setupCallList(CALL_LIST);
    setupMultiWordStreets(
        "ALDER RUN",
        "AMEIGH VALLEY",
        "BAILEY CREEK",
        "BAKER CREST",
        "BAPTIST HILL",
        "BUCK HILL",
        "CORYLAND PARK",
        "ELK RUN",
        "ENGLISH HILL",
        "GROUSE RUN",
        "GROVES HILL",
        "JACKSON CENTER",
        "LAUREL HILL",
        "PICNIC GROVE",
        "PONY HILL",
        "PUMPKIN HILL",
        "RILEY HILL",
        "ROARING RUN",
        "WHISPERING PINES"
    );
  }
  
  
  @Override
  protected boolean parseMsg(String subject, String body, Data data) {
    if (!super.parseMsg(subject, body, data)) return false;
    
    // Descripioin ending with 3 HRS confuses the address parser
    if (data.strAddress.startsWith("3 HRS ")) {
      data.strCall += " 3 HRS";
      data.strAddress = data.strAddress.substring(6).trim();
    }
    return true;
  }


  private static final CodeSet CALL_LIST = new CodeSet(
      "ABDOMINAL PAIN",
      "ALLERGIES STINGS BITES DIFF SPEAKING BETWEEN BREATHS",
      "BREATHING PROBLEMS - ABNORMAL BREATHING",
      "BREATHING PROBLEMS - ASTHMA - DIFF SPKING BETWEEN BREATHS",
      "BREATHING PROBLEMS - CHANGING COLOR",
      "BREATHING PROBLEMS - DIFF SPEAKING BETWEEN BREATHS",
      "CHEST PAIN - ABNORMAL BREATHING",
      "CHEST PAIN - BREATHING NORMALLY > 35",
      "CHEST PAIN - CLAMMY",
      "CHEST PAIN - DIFFICULTY SPEAKING BETWEEN BREATHS",
      "CONVULSIONS/SEIZURES - DIABETIC - KNOWN SEIZURE DISORDER",
      "CVA/TIA - ABNORMAL BREATHING - CLEAR EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - CLEAR EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - CLEAR EVIDENCE - UNKNOWN TIME",
      "CVA/TIA - ABNORMAL BREATHING - NOT TESTED - GREATER THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - NOT TESTED - LESS THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - NOT TESTED - UNKNOWN TIME",
      "CVA/TIA - ABNORMAL BREATHING - STRONG EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - STRONG EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - ABNORMAL BREATHING - STRONG EVIDENCE - UNKNOWN TIME",
      "CVA/TIA - NOT ALERT - CLEAR EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - NOT ALERT - CLEAR EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - NOT ALERT - CLEAR EVIDENCE - UNKNOWN TIME",
      "CVA/TIA - NOT ALERT - NOT TESTED - GREATER THAN 3 HRS",
      "CVA/TIA - NOT ALERT - NOT TESTED - LESS THAN 3 HRS",
      "CVA/TIA - NOT ALERT - NOT TESTED - UNKNOWN TIME",
      "CVA/TIA - NOT ALERT - STRONG EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - NOT ALERT - STRONG EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - NOT ALERT - STRONG EVIDENCE - UNKNOWN TIME",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - CLEAR EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - CLEAR EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - CLEAR EVIDENCE - UNKNOWN TIME",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - NOT TESTED - GREATER THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - NOT TESTED - LESS THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - NOT TESTED - UNKNOWN TIME",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - STRONG EVIDENCE - GREATER THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - STRONG EVIDENCE - LESS THAN 3 HRS",
      "CVA/TIA - SUDDEN WEAKNESS OR NUMBNESS - STRONG EVIDENCE - UNKNOWN TIME",
      "FALLS - CHEST OR NECK INJURY WITH DIFF BREATHING - STILL ON THE GROUND",
      "FALLS - LONG FALL",
      "FALLS - LONG FALL - STILL ON THE GROUND",
      "FALLS - NON-RECENT >6",
      "FALLS - NON-RECENT >6 - STILL ON THE GROUND",
      "FALLS - NOT DANGEROUS BODY AREA",
      "FALLS - NOT DANGEROUS BODY AREA - STILL ON THE GROUND",
      "FALLS - POSSIBLY DANGEROUS BODY AREA",
      "FALLS - POSSIBLY DANGEROUS BODY AREA - STILL ON THE GROUND",
      "FALLS - PUBLIC ASSIST - NO INJURIES",
      "FALLS - PUBLIC ASSIST - NO INJURIES - STILL ON THE GROUND",
      "HAZMAT",
      "HEMORRHAGE/LACERATIONS - POSSIBLY DANGEROUS HEMORRHAGE",
      "HEMORRHAGE/LACERATIONS - UNCONSCIOUS OR ARREST",
      "LIFTING ASSISTANCE",
      "MEDICAL",
      "MVA",
      "OB EMERGENCY - IMMINENT DELIVERY >5MO / 20WEEKS",
      "OVERDOSE/POISONING - ABNORMAL BREATHING - ACCIDENTAL",
      "OVERDOSE/POISONING - ABNORMAL BREATHING - INTENTIONAL",
      "OVERDOSE/POISONING - UNCONSCIOUS - ACCIDENTAL",
      "OVERDOSE/POISONING - UNCONSCIOUS - INTENTIONAL",
      "PAGE CALL ERWAY AMB",
      "SICK PERSON - ABNORMAL BREATHING",
      "SICK PERSON - NO PRIORITY SYMPTOMS - TRANSPORTATION ONLY",
      "SICK PERSON - NO PRIORITY SYMPTOMS - UNWELL/ILL",
      "SMOKE INVESTIGATION",
      "STRUCTURE FIRE",
      "TRANSFER ASSIGNMENT / FIRE",
      "TREE DOWN",
      "UNCONSCIOUS/FAINTING - NOT ALERT",
      "UNCONSCIOUS/FAINTING - UNCONSCIOUS - EFFECTIVE BREATHING",
      "UNCONSCIOUS/FAINTING - ALERT WITH ABNORMAL BREATHING",
      "UNKNOWN CONDITIONS",
      "UNKNOWN PROBLEM - MEDICAL ALARM - NO INFORMATION",
      "VEHICLE FIRE",
      "WILD FIRE"
  );
  
  private static final String[] CITY_LIST = new String[]{
    "BLOSSBURG BORO",
    "ELKLAND BORO",
    "KNOXVILLE BORO",
    "LAWRENCEVILLE BORO",
    "LIBERTY BORO",
    "MANSFIELD BORO",
    "ROSEVILLE BORO",
    "TIOGA BORO",
    "WELLSBORO BORO",
    "WESTFIELD BORO",

    "BLOSS TWP",
    "BROOKFIELD TWP",
    "CHARLESTON TWP",
    "CHATHAM TWP",
    "CLYMER TWP",
    "COVINGTON TWP",
    "DEERFIELD TWP",
    "DELMAR TWP",
    "DUNCAN TWP",
    "ELK TWP",
    "FARMINGTON TWP",
    "GAINES TWP",
    "HAMILTON TWP",
    "JACKSON TWP",
    "LAWRENCE TWP",
    "LIBERTY TWP",
    "MIDDLEBURY TWP",
    "MORRIS TWP",
    "NELSON TWP",
    "OSCEOLA TWP",
    "PUTNAM TWP",
    "RICHMOND TWP",
    "RUTLAND TWP",
    "SHIPPEN TWP",
    "SULLIVAN TWP",
    "TIOGA TWP",
    "UNION TWP",
    "WARD TWP",
    "WESTFIELD TWP",
    
    // Bradford County
    "CATON",
    "TOWN OF CATON",
    "WELLS TWP",
    
    // Potter County
    "HEBRON TWP"
  };
}
