#! /bin/bash
find cadpage-private/src/test/java -name '*ParserTest.java' -exec grep -E \
   -e 'PARSE FAILURE' \
   -e '"ADDR:[A-Za-z0-9].*[^-&()/.\[\]'\'' A-Za-z0-9].*"' \
   -e '"CITY:.*[^-, A-Za-z'\''].*"' \
   -e '"CITY:[A-Z]{1,3}"' \
   -e '"ST:[A-Z]?[^A-Z]' \
   -e '"ST:[A-Z]{3,}"' \
   {} + | grep -E -v \
   -e '\*\*IGNORE\*\*' \
   -e 'BaseParserTest.java' \
   -e 'ALJeffersonCountyLParserTest.java' \
   -e '"CITY:( .*|\\n|CMCH / GOSHEN|COTTAGE GROVE/HISSOP|EVA|FOX|OPP|RAY|YOE|[0-9]{5})"' \
   -e '"ADDR:(LAT:|LL|[+NS]?[0-9].*[0-9] *[,;] *-?[0-9])'
