#! /bin/bash
find cadpage-private/src/test/java -name '*ParserTest.java' -exec grep -E \
   -e 'PARSE FAILURE' \
   -e '"ADDR:[A-Za-z0-9].*[^-&()/.\[\]'\'' A-Za-z0-9].*"' \
   -e '"CITY:.*[^-, A-Za-z’'\''].*"' \
   -e '"CITY:[A-Z]{1,3}"' \
   -e '"ST:[A-Z]?[^A-Z]' \
   -e '"ST:[A-Z]{3,}"' \
   {} + | grep -E -v \
   -e '\*\*IGNORE\*\*' \
   -e 'BaseParserTest.java' \
   -e 'ALJeffersonCountyLParserTest.java:' \
   -e 'ZSESwedenAParserTest.java:' \
   -e 'OHDelawareCountyBParserTest.java:' \
   -e 'OHWarrenCountyAParserTest.java:' \
   -e 'SmartAddressParserTest.java:' \
   -e '\+[[:space:]]*$' \
   -e '"CITY:(\\n|064/284|ARP|ASH|AMA|AVA|AYR|CMCH / GOSHEN|COTTAGE GROVE/HISSOP|DC|ELA|EVA|FOX|GAY|GUY|HAY|HOU\.R\.|HYE|IRA|IVA|JAY|LEE|OLA|OPP|PG|RAY|RDU|ROY|RYE|SUN|TEA|TOWNSHIP .*|ULM|YOE|.*WARD *[0-9]|.*WD *[0-9]|[0-9]{5})"' \
   -e '"ADDR:(LAT:|LL|[+NS]?[0-9].*[0-9] *[,;] *-?[0-9])'
