#! /bin/bash
. ${0%/*}/common
MODULES="${MODULES#. *} ."

# Check for any unresolved merge conflicts
for DIR in $MODULES; do
  if ( cd $DIR; git merge HEAD>/dev/null ); then
    echo $DIR is OK
  else
    echo "**** Project:$DIR has unresolved conflicts" 1>&2
    exit 1
  fi
done

# Add any untracked files
for DIR in  $MODULES; do
  ( cd $DIR; git add --all )
done

# Now do the final commit
for DIR in $MODULES; do
  echo "$DIR:"
  ( cd $DIR; git commit "$@" )
done