#! /bin/bash

# See if editor was passed from caller
TEDITOR=
if [[ $1 == -editor ]]; then
  TEDITOR="$2"
  shift 2
fi

# Get the master module list
# and reverse order so top menu comes last
. ${0%/*}/common
MODULES="${MODULES#. *} ."

# Check for any unresolved merge conflicts
for DIR in $MODULES
do
  if ( cd $DIR; ! git merge HEAD>/dev/null ); then
    echo "**** Project:$DIR has unresolved conflicts" 1>&2
    exit 1
  fi
done

# Add any untracked files
for DIR in  $MODULES; do
  ( cd $DIR; git add --all )
done

# Do we need to override the editor setting
if [[ -n TEDITOR ]]; then
  OLD_EDITOR=`git config --global core.editor`
  git config --global core.editor $TEDITOR
fi

# Now do the final commit
for DIR in $MODULES; do
  echo "$DIR:"
  ( cd $DIR; git commit -a "$@" )
done

# Restore editor setting
if [[ -n TEDITOR ]]; then
  if [[ -n OLD_EDITOR ]]; then
    git config --global core.editor $OLD_EDITOR
  else
    git config --global --unset core.editor
  fi
fi
exit 0
