#! /bin/bash
. ${0%/*}/common

if [[ $# == 0 ]]; then
  echo "*** Commit comment is always required" 1>&2
  exit 1
fi

if [[ $# > 1 ]]; then
  echo "*** Commit comment must be enclosed in quotes" 1>&2
  exit 1
fi

${0%/*}/gpull

${0%/*}/gcommit -m '$1' || exit 1

# Check for any unresolved merge conflicts
for DIR in $MODULES
do
  if ( cd $DIR; ! git merge HEAD>/dev/null ); then
    echo "**** Project:$DIR has unresolved conflicts" 1>&2
    exit 1
  fi
done


for DIR in $MODULES
do
  echo "$DIR:"
  ( cd $DIR; git push )
done