#! /bin/bash
. ${0%/*}/common

if [[ $# == 0 ]]; then
  echo "*** Commit comment is always required" 1>&2
  exit 1
fi

if [[ $# > 1 ]]; then
  echo "*** Commit comment must be enclosed in quotes" 1>&2
  exit 1
fi

${0%/*}/gpull

${0%/*}/gcommit -m '$1' || exit 1

${0%/*} gpush
