package net.anei.cadpage.parsers.KY;

import java.util.Properties;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA74Parser;

public class KYMetcalfeCountyBParser extends DispatchA74Parser {

  public KYMetcalfeCountyBParser() {
    super("METCALFE COUNTY", "KY");
  }

  @Override
  public String getFilter() {
    return "Dispatch@911comm2.info";
  }

  @Override
  public int getMapFlags() {
    return MAP_FLG_PREFER_GPS;
  }

  @Override
  public boolean parseMsg(String subject, String body, Data data) {
    if (!super.parseMsg(subject, body, data)) return false;
    String call = CALL_CODES.getProperty(data.strCall);
    if (call != null) {
      data.strCode = data.strCall;
      data.strCall = call;
    }
    return true;
  }

  @Override
  public String getProgram() {
    return super.getProgram().replace("CALL", "CODE CALL");
  }

  private static final Properties CALL_CODES = buildCodeTable(new String[] {
      "0149",       "POSS DUI",
      "1012",       "WITH SOMEONE",
      "1014",       "ESCORT",
      "1015",       "ARREST",
      "1026",       "SHOPLIFTER",
      "1029",       "WARRANT",
      "1038",       "SUICIDAL THREATS",
      "1039",       "BREAK IN (NOT IN PROGRESS)",
      "1040",       "HEARD SHOTS HEARD",
      "1041",       "REPORT",
      "1045",       "ACCIDENT - NO INJURIES",
      "1046",       "ACCIDENT WITH INJURIES",
      "1047",       "TAG",
      "1050",       "DOMESTIC",
      "1051",       "BREAK IN (IN PROGRESS)",
      "1052",       "HOLD UP IN PROGRESS",
      "1053",       "PANIC/HOLD UP ALARM",
      "1054",       "BURGLAR ALARM",
      "1060",       "FIGHT",
      "1063",       "SUSPICIOUS LETTER/PKG",
      "1065",       "SUBJECT W/ GUN",
      "1066",       "SUB W/ KNIFE",
      "1067",       "SUBJECT W/ WEAPON ANY KIND",
      "107",        "METCALFE COUNTY CORONER",
      "1070",       "SHOOTING",
      "1071",       "STABBING",
      "1073",       "RIOT",
      "1075",       "ROBBERY",
      "1076",       "ABANDONED VEHICLE",
      "1078",       "DISORDERLY PERSON",
      "1085",       "CHILDREN LEFT ALONE",
      "1086",       "RECKLESS DRIVER",
      "1089",       "BOMB THREAT",
      "1095",       "RAPE - PERP LEFT SCENE",
      "1096",       "RAPE - PERP STILL ON SCENE",
      "2301",       "DRUNK IN PUBLIC PLACE",
      "72HR",       "72HR HOLD",
      "ABC",        "ABC",
      "ABDOM",      "ABDOMINAL PAIN",
      "ABUSE",      "ABUSE",
      "AIRCRAFT",   "AIRCRAFT",
      "ALARM",      "ANY ALARM CALL",
      "ALLRGY",     "ALLERGIC REACTION",
      "AMP",        "AMPUTATION",
      "ANIMAL",     "ANIMAL",
      "ASSAULT",    "ASSAULT",
      "ASSIST",     "ASSIST OTHER AGENCY",
      "ATL",        "ATTEMP TO LOCATE",
      "ATS",        "ATTEMPT TO SERVE",
      "ATV",        "ALL TERRAIN VEHICLE",
      "BACK",       "BACK PAIN",
      "BALL",       "BALL GAME STDBY",
      "BANNED",     "BANNED BANNED FROM LOCATION",
      "BARN",       "FIRE - BARN FIRE",
      "BE",         "BREAKING & ENTERING",
      "BITE",       "ANIMAL BITE OR ATTACK",
      "BLEED",      "SUBJ IS BLEEDING",
      "BOAT",       "FIRE FIRE - BOAT ON FIRE",
      "BOLO",       "BOLO",
      "BOMB",       "BOMB LOCATED",
      "BREATH",     "DIFFICULTY BREATHING",
      "BSUBJ",      "BARRICADED SUBJECT",
      "BURGLARY",   "BURGLARY",
      "BURN",       "BURN INJURY",
      "BUSINESS",   "BUSINESS BUILDING ON FIRE (NOT …",
      "CARMOX",     "CARBON MONOXIDE DETECTOR",
      "CFIRE",      "FIRE - CHIMNEY FIRE",
      "CHASE",      "CHASE",
      "CHECKP",     "TRAFFIC SAFETY CHECKPOINT",
      "CHESTI",     "INJURY CHEST INJURY",
      "CHESTP",     "PAIN CHEST PAIN",
      "CHILD",      "CHILD",
      "CHOKE",      "CHOKE",
      "CHURCH",     "FIRE - CHURCH BUILDING",
      "CM",         "CRIMINAL MISCHIEF",
      "CO",         "CARMOX INHALATION/POISONING",
      "COLD",       "COLD EXPOSURE",
      "COLLAPSE",   "BUILDING COLLAPSE",
      "COMPLT",     "COMPLAINT CALL",
      "CONFINE",    "CONFINED SPACE RESCUE",
      "CONTRL",     "CONTROL BURN",
      "COUNT",      "COUNTERFIT BILLS/SECURITIES",
      "COURT",      "OUT AT COURT",
      "COW",        "COWS OUT",
      "CRUSH",      "CRUSH INJURY",
      "CUSTODY",    "CUSTODY ISSUES",
      "CVA",        "CVA/STROKE/TIA",
      "DEBRIS",     "DEBRIS IN THE ROADWAY",
      "DEER",       "DEER COMPLAINT",
      "DIABETIC",   "DIABETIC EMERGENCY",
      "DIS",        "DISASTER",
      "DISORDERLY", "DISORDERLY PERSON",
      "DISTUR",     "DISTURBANCE",
      "DOA",        "DEAD ON ARRIVAL",
      "DOG",        "DOG COMPLAINT",
      "DROWN",      "DROWNING",
      "DSS",        "DEPARTMENT SOCIAL SERVICES",
      "DUMPING",    "ILLEGAL DUMPING",
      "DUMPSTER",   "DUMPSTER FIRE",
      "DVO",        "DOMESTIC VIOLENCE ORDER",
      "ELEC",       "ELECTROCUTION INJURY",
      "ELEV",       "ELEVATOR RESCUE",
      "EPO",        "EMERGENCY PROTECTIVE ORDER",
      "EQUIPMENT",  "EQUIPMENT ISSUES",
      "EVENT",      "SPECIAL EVENT",
      "EVICT",      "EVICTICTION",
      "EXPLOD",     "EXPLOSION",
      "EXPLOIT",    "EXPLOITATION OF CHILD/ADULT",
      "EYE",        "INJURY - EYE",
      "FACTORY",    "FIRE - FACTORY",
      "FAINT",      "FAINTING OR PASSED OUT",
      "FALL",       "FALL",
      "FARM",       "FARMING ACCIDENT",
      "FEQUIP",     "FIRE - FARM EQUIPMENT",
      "FIELD",      "FIELD FIRE",
      "FIRE",       "FIRE UNSPECIFIED TYPE",
      "FLASH",      "FLASH - PUBLIC INDECENCY",
      "FLOOD",      "FLOOD HAZARD / FLOODED AREA",
      "FOLLOW",     "INVESTIGATION FOLLOW UP",
      "FORGE",      "FORGED CHECKS/DOCUMENTS/ETC",
      "FOUND",      "FOUND OR LOCATED PROPERTY",
      "FRAC",       "POSSIBLE BREAK / FRACTURE",
      "FRAUD",      "CHECK / CREDIT / DEBIT FRAUD",
      "FUEL",       "FUEL SPILL",
      "FWORK",      "COMPLAINT- FIREWORKS",
      "GARAGE",     "FIRE - GARAGE ",
      "GAS",        "GAS STATION ON FIRE",
      "GDO",        "GASS DRIVE OFF",
      "GLEAK",      "GAS LINE LEAK",
      "GOODIN",     "GOOD INTENT",
      "HAR",        "RESCUE - HIGH ANGLE",
      "HARASS",     "HARASSMENT",
      "HAY",        "FIRE - HAY",
      "HAZMAT",     "HAZARDOUS MATERIALS",
      "HEAD",       "HEADACHE",
      "HEART",      "HEART / CARDIAC PROBLEMS",
      "HEAT",       "HEAT EXPOSURE",
      "HITRUN",     "HITRUN",
      "HOME",       "HOME VISIT (SCHOOL)",
      "HORSE",      "HORSES OUT",
      "HOST",       "HOSTAGE SITUATION",
      "HOUSE",      "HOUSE FIRE",
      "I911",       "INCOMPLETE OR OPEN 911 CALL",
      "ICE",        "RESCUE - ICE",
      "ID",         "IDENTITY THEFT",
      "ILL",        "UNDEFINED OR UNKNOWN ILLNESS",
      "IMPERS",     "CRIMINAL IMPERSONATION",
      "INDUST",     "INDUSTRIAL RESCUE / ACCIDENT",
      "INHALE",     "INHALATION INJURY",
      "INSP",       "INSPECTION",
      "INTOX",      "INTOXILIZER OPERATOR",
      "INVEST",     "INVESTIGATION",
      "IPO",        "PROTECTION ORDER",
      "JUV",        "JUVENILE",
      "K9",         "K9",
      "KIDNAP",     "KIDNAPPING",
      "LA",         "LIFE LINE ALARM",
      "LAC",        "LACERATION / CUT",
      "LEAVES",     "FIRE - LEAVES",
      "LIFT",       "LIFT ASSIST",
      "LINES",      "LINES DOWN",
      "LOCK",       "LOCK OUT/CHILD IN VEH",
      "MA",         "MOTORIST ASSIST",
      "MARINE",     "MARINE INCIDENT",
      "MEDIC",      "ANY MEDICAL CALL",
      "METH",       "METH LAB COMPLAINT",
      "MISC",       "OTHER TYPE OF INCIDENT",
      "MISSING",    "MISSING PERSON",
      "MIW",        "MENTAL INQUEST WARRANT",
      "MURDER",     "MURDER",
      "MUSIC",      "MUSIC COMPLAINT",
      "MUTUAL",     "MUTUAL AID REQUEST",
      "NEIGHDISP",  "NEIGHBOR DISPUTE",
      "NGO",        "NATURAL GAS ODOR",
      "NOISE",      "NOISE COMPLAINT",
      "OB",         "OBSTERICS",
      "OD",         "OVERDOSE",
      "ODOWN",      "OFFICER DOWN",
      "OLN",        "OPERATORS LICENSE NUMBER CHECK",
      "OPEN",       "OPEN DOOR",
      "ORD",        "CITY ORDINANCE CODE ENFORCEM…",
      "PAIN",       "PAINT - GENERALIZED PAIN",
      "PAN",        "PANHANDLER /PANHANDLING",
      "PAPER",      "PICK UP PAPERWORK",
      "PARK",       "PARKING COMPLAINT /VIOLATION",
      "PED",        "PEDESTRIAN",
      "POISON",     "POISON",
      "PROPDISP",   "PROPERTY DISPUTE",
      "PROWL",      "PROWLER",
      "PS CALL",    "PUBLIC SERVICE CALL",
      "PSYCH",      "PSYCHIATRIC EMERGENCY",
      "PURSUIT",    "CHASE - VEHICLE OR FOOT PURSUIT",
      "RDHZD",      "ROAD HAZARD",
      "REC",        "RECREATIONAL VEHICLE ACCIDENT",
      "REPO",       "REPOSSESSION",
      "RESCUE",     "RESCUE",
      "ROBB",       "STRONG ARM ROBBERY / ARMED R…",
      "RTL",        "ROUTINE TRANSFER LOCAL",
      "RUNAW",      "RUNAWAY",
      "S VEH",      "SUSIPICIOUS VEHICLE",
      "SC",         "SECURITY CHECK",
      "SCHFIRE",    "FIRE - SCHOOL BUILDING ON FIRE",
      "SCHOOL",     "ANY CALL INVOLVING THE SCHOOL",
      "SD",         "SPECIAL DETAIL",
      "SEIZE",      "SEIZURES",
      "SHED",       "FIRE - SHED OR OUTBUILDING",
      "SHOTS",      "SHOTS FIRED",
      "SIG10",      "DRUG TRAFFIC",
      "SIRENS",     "WEATHER SIRENS",
      "SMOKE",      "SMOKE IN AREA / INVESTIGATION",
      "SNAKE",      "SNAKE COMPLAINT",
      "SOLICIT",    "SOLICITATION / PROSTITUTION",
      "SSUBJ",      "SUSPICIOUS SUBJECT",
      "STALK",      "COMPLAINT - STALKING",
      "STDBY",      "STAND BY SCENE",
      "STOLEN",     "STOLEN VEHICLE",
      "STORM",      "STORM DAMAGE",
      "SZ",         "SCHOOL ZONE",
      "TC",         "TRAFFIC CONTROL",
      "TECH",       "TECHNICAL ISSUES",
      "TEST",       "TEST CALL",
      "THEFT",      "THEFT REPORT",
      "THREAT",     "THREATS MADE",
      "TRAF",       "TRAFFIC STOP",
      "TRAIN",      "TRAINING",
      "TRAINING",   "UNITS TRAINING",
      "TRANSP",     "JAILER TRANSPORT",
      "TRASH FIRE", "FIRE - TRASH",
      "TRASH",      "TRASH COMPLT",
      "TRAUMA",     "SEVERE BODILY TRAUMA / INJURY",
      "TREE",       "TREE DOWN",
      "TRENCH",     "RESCUE NEEDED IN TRENCH",
      "TRESP",      "TRESPASSING",
      "UNK",        "UNKNOWN COMPLAINT",
      "UNRESP",     "UNRESP",
      "UNREST",     "UNRESTRAINED CHILD / NO CARSEAT",
      "VANDAL",     "VANDALISM",
      "VEH",        "VEHICLE FIRE",
      "WE",         "WANTON ENDANGERMENT",
      "WEATH",      "WEATHER",
      "WFC",        "WELFARE CHECK",
      "WOODS",      "FIRE - FORREST / WOODS",
      "XPATROL",    "EXTRA PATROL"

  });
}
