package net.anei.cadpage.parsers.KY;

import java.util.Properties;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA65Parser;

public class KYPulaskiCountyParser extends DispatchA65Parser {

  public KYPulaskiCountyParser() {
    super(CITY_LIST, "PULASKI COUNTY", "KY");
    setupCities(CITY_CODES);
  }

  @Override
  public String getFilter() {
    return "dispatch@911comm2.info,dispatch@911comm3.info,cadreports@pulaski911.com";
  }

  @Override
  protected boolean parseMsg(String subject, String body, Data data) {
    if (!super.parseMsg(subject, body, data)) return false;

    data.strCode = data.strCall;
    data.strCall = convertCodes(data.strCode, CALL_CODES);

    data.strCity = convertCodes(data.strCity.toUpperCase(), CITY_CODES);
    return true;
  }

  @Override
  public String getProgram() {
    return super.getProgram().replaceAll("CALL", "CODE CALL");
  }

  @Override
  public String adjustMapCity(String city) {
    return convertCodes(city, MAP_CITY_TABLE);
  }

  private static final Properties CALL_CODES = buildCodeTable(new String[]{
      "1",      "Receiving Poorly",
      "2",      "Receiving Well",
      "3",      "Stop Transmitting",
      "4",      "ok-Affirmative",
      "5",      "Relay",
      "6",      "Busy",
      "7",      "Out of Service",
      "8",      "In Service",
      "9",      "Repeat",
      "10",     "Out of Car, Subject to Call",
      "10-6",   "10-6",
      "12",     "TRANSPORT",
      "13",     "Weather Conditions/Road Conditions",
      "14",     "ESCORT",
      "149",    "DUI",
      "14B",    "ESCORT - TO THEBANK",
      "14F",    "ESCORT - FUNERALHOME",
      "15",     "PRISONER IN CUSTODY",
      "19",     "Request for Coroner",
      "20",     "Location",
      "23",     "Everything OK",
      "2301",   "PUBLIC INTOXICATION",
      "24",     "Trouble at Dispatch-please respond",
      "25",     "Contact with...",
      "27",     "Arrived with patient at...",
      "29",     "Check for wanted or stolen",
      "30",     "Does not conform with rules and regulations",
      "33",     "Emergency Traffic at your Station",
      "36",     "Correct Time",
      "37",     "Dispatcher on Duty",
      "45",     "PROPERTY DAMAGEACCIDENT",
      "46",     "MVA/INJURY",
      "47",     "Vehicle Registration Check",
      "51",     "Enroute to...",
      "53",     "MOTORIST ASSIST",
      "53K",    "KEYS LOCKED IN CAR",
      "55",     "Active Alarm-Robbery or Burglary in Progress",
      "60",     "Change to Tactical Frequency",
      "61",     "Change to Scrambled Frequency",
      "67",     "Gas Leak",
      "68",     "CONTROLLED BURN",
      "68I",    "ILLEGAL CONTROLLEDBURN",
      "69",     "Inspection",
      "70",     "Bomb Threat",
      "74",     "Verbal Warning Issued",
      "75",     "Citation Issued",
      "76",     "SUICIDE - ATTEMPTED",
      "76T",    "SUICIDE - THREATENED",
      "77",     "N.C.I.C Hit",
      "81",     "Precaution",
      "88",     "Phone Number",
      "97",     "Arrived at Scene",
      "98",     "Finished with Last Assignment",
      "ABC",    "ALCOHOL BEVERAGE CONTROL",
      "ABD",    "ABDUCTION",
      "AC",     "ANIMAL COMPLAINT",
      "ACI",    "ACCIDENT INVESTIGATION",
      "AIP",    "ASSAULT IN PROGRESS",
      "ALS",    "ADVANCED LIFE SUPPORT TRANSFER",
      "AMP",    "AMPUTATION",
      "AMS",    "ALTERED MENTAL STATUS",
      "ANT",    "ANTHRAX",
      "AO",     "AIRWAY OSBTRUCTION",
      "AOA",    "ASSIST OTHER AGENCY",
      "AOD",    "ACCIDENTAL OVERDOSE",
      "AR",     "ALLERGIC REACTION",
      "ARS",    "ARSON INVESTIGATION",
      "AS",     "ACTIVE SHOOTER",
      "ASS",    "ASSAULT",
      "ATL",    "ATTEMPT TO LOCATE",
      "AV",     "ABANDONED VEHICLE",
      "AW",     "ASSAULT/WEAPON",
      "AWOL",   "AWOL - MILITARY ONLY",
      "BA",     "BOATING ACCIDENTS",
      "BAR",    "BARRICADE",
      "BC",     "BUSINESS CHECK",
      "BF",     "BRUSH FIRE",
      "BIP",    "BURGLARY IN PROGRESS",
      "BLS",    "BASIC LIFE SUPPORT TRANSFER",
      "BOLO",   "BE ON THE LOOKOUT",
      "BP",     "PAIN - BODY/MUSCLE",
      "BT",     "BOMB THREAT",
      "BUR",    "BURGLARY",
      "BV",     "BURN VICTIM",
      "C19",    "COVID",
      "CA",     "CARDIAC ARREST",
      "CAD",    "CAD ERROR",
      "CAN",    "CANCELLED",
      "CAVE",   "CAVE/CONFINED SPACE RESCUE",
      "CD",     "CUSTODIAL DISPUTE",
      "CE",     "CHEMICAL EXPOSURE",
      "CHM",    "CHASE MODE INITIATED",
      "CHO",    "CHOKING",
      "CI",     "CRIMINAL INVESTIGATION",
      "CL",     "CRITICAL LABS",
      "CM",     "CRIMINAL MISCHIEF",
      "CMI",    "CARBON MONOXIDE INVESTIGATION",
      "CODE",   "CODE 300",
      "Code1",  "Non-Emergency",
      "Code2",  "Lights and No Siren",
      "Code3",  "Lights and Siren",
      "COLD",   "COLD EXPOSURE",
      "COLL",   "STRUCTURAL COLLAPSE",
      "COR",    "CORONER",
      "COU",    "COUNTERFEIT",
      "COV",    "CITY ORDINANCE VIOLATION",
      "CP",     "CANCER PATIENT",
      "CR",     "CODE RED",
      "CS",     "CHEMICAL SPILL",
      "CSC",    "CAR SEAT CHECK",
      "CT",     "CRIMINAL TRESSPASS",
      "CTD",    "COLLAPSED TRENCH",
      "CVA",    "STROKE",
      "DC",     "DISORDERLY CONDUCT",
      "DEH",    "DEHYDRATION",
      "DF",     "DUMPSTER FIRE",
      "DI",     "DEATH INVESTIGATION",
      "DIA",    "DIABETIC",
      "DIP",    "DOMESTIC IN PROGRESS",
      "DIZ",    "DIZZINESS",
      "DOM",    "DOMESTIC",
      "DOS",    "FATAL",
      "DRO",    "DROWNING",
      "DRU",    "DRUG RELATED TRAFFIC",
      "DUI",    "DRIVING UNDER INFLUENCE",
      "EF",     "ELECTRICAL FIRE",
      "EH",     "ELECTRICAL HAZARD",
      "ELE",    "STUCK IN ELEVATOR",
      "ELEC",   "ELECTROCUTION",
      "EP",     "EXTRA PATROL",
      "ESC",    "ESCAPEE",
      "ETOH",   "INTOXICATED",
      "EUF",    "ELECTRICAL UTILITY FIRE",
      "EXP",    "EXPLOSION",
      "FALL",   "FALL W/O INJURY",
      "FAP",    "FOUND/ABANDONED PERSON",
      "FF",     "FOREST FIRE",
      "FI",     "FIRE INVESTIGATION",
      "FIP",    "FIGHT IN PROGRESS",
      "FL",     "FUEL LEAK",
      "FLU",    "FLU LIKE SYMPTOMS",
      "FMI",    "FIRE MARSHAL INSPECTION",
      "FOR",    "FORGERY",
      "FP",     "FOUND PROPERTY",
      "FRA",    "FRAUD",
      "FRAC",   "FRACTURE",
      "FWI",    "FALL WITH INJURY",
      "GA",     "GOLDEN ALERT",
      "GAM",    "GAMBLING INVESTIGATION",
      "GF",     "GRASS FIRE",
      "GI",     "GENERAL ILLNESS",
      "GL",     "NATURAL GAS LEAK",
      "GSW",    "SHOOTING VICTIM/INCIDENT",
      "HAR",    "HARRASSMENT",
      "HBP",    "HYPERTENSION - HIGHBP",
      "HEAT",   "HEAT EXPOSURE",
      "HEM",    "HEMORRHAGE/BLEEDING",
      "HI",     "HOME INVASION",
      "HIGH",   "HIGH ANGLE RESCUE",
      "HOM",    "HOMICIDE",
      "HOS",    "HOSTAGE",
      "HP",     "HEART PATIENT",
      "HR",     "HUMAN REMAINS",
      "HR45",   "HIT & RUN PROPERTY DAMAGE",
      "HR46",   "HIT & RUN W/ INJURY",
      "HT",     "HIGH FEVER",
      "HV",     "HOME VISIT",
      "HWR",    "HIGH WATER RESCUE",
      "IC",     "CHEST INJURY",
      "ICE",    "ICE RESCUE",
      "ID",     "IDENTITY THEFT",
      "IE",     "INDECENT EXPOSURE",
      "IF",     "FIRE INSPECTION",
      "IM",     "IMPERSONATION",
      "INS",    "INSPECTION - AUTO",
      "INV",    "INVESTIGATION",
      "JA",     "JUVENILE ABUSE",
      "JM",     "JUVENILE MISCHIEF PROBLEM",
      "JOC",    "JUVENILE OUT OF CONTROL",
      "KID",    "KIDNAPPING",
      "LA",     "LIFT ASSIST",
      "LAC",    "LACERATION",
      "LBP",    "HYPOTENSION - LOWBP",
      "LD",     "LANDLORD DISPUTE",
      "LE",     "LETHARGIC",
      "LO",     "LOCKED OUT",
      "LP",     "LOST PROPERTY",
      "MA",     "MEDICAL ALARM",
      "MCTF",   "MAJOR CRIMES TASK FORCE",
      "MD",     "MESSAGE DELIVERY",
      "MEET",   "MEETING",
      "METH",   "METH LAB INVESTIGATION",
      "MF",     "MULCH FIRE",
      "MI",     "MACHINE ACCIDENT",
      "MIJ",    "MISSING - JUVENILE",
      "MIS",    "MISSING - ADULT",
      "MIW",    "MIW",
      "MOCK",   "MOCK DRILL",
      "MP",     "MENTAL PROBLEM",
      "NC",     "NOISE COMPLAINT",
      "NCB",    "NON-COMPLAINT BUSINESS",
      "NCIC",   "NCIC HIT",
      "ND",     "NEIGHBOR DISPUTE",
      "OB",     "OBSTETRICS/GYNECOLOGY",
      "OD",     "OVERDOSE",
      "OOC",    "OUT OF COUNTY",
      "OOL",    "OUT OF LIMITS",
      "OR45",   "OFF ROAD 10-45",
      "OR46",   "OFF ROAD 10-46",
      "PACK",   "SUSPICIOUS PACKAGE",
      "PAR",    "PARKING COMPLAINT",
      "PB",     "PAIN - BACK",
      "PC",     "PAIN - CHEST",
      "PD",     "PROPERTY DISPUTE",
      "PE",     "PAIN - EYE",
      "PED",    "PEDESTRIAN ACCIDENT",
      "PER",    "PERSON CHECK",
      "PF",     "PAIN - FACE",
      "PH",     "PAIN - HIP-PELVIC",
      "PHE",    "PAIN - HEAD",
      "PLA",    "PAIN - LOWER ABDOMEN",
      "PLC",    "PLANE CRASH",
      "PLE",    "PAIN - LOWER EXTREMITY",
      "PN",     "PAIN - NECK",
      "POI",    "POISONING",
      "PR",     "PUBLIC RELATIONS",
      "PRO",    "PROWLER",
      "PROS",   "PROSTITUTION",
      "PROTRUDINGBONE",          "PROTRUDING BONE",
      "PS",     "PAPER SERVICE",
      "PT",     "PRISONER TRANSPORT",
      "PUA",    "PAIN - UPPER ABDOMEN",
      "PUE",    "PAIN - UPPER EXTRIMITY",
      "PUR",    "PURSUIT",
      "PW",     "PAPERWORK",
      "RA",     "RESPIRATORY ARREST",
      "RAP",    "RAPE",
      "RC",     "RESIDENCE CHECK",
      "RD",     "RECKLESS DRIVING",
      "RED",    "RESPIRATORY DIFFICULTY",
      "REP",    "REPORT",
      "REPO",   "REPO",
      "RIO",    "RIOT",
      "RIP",    "ROBBERY IN PROGRESS",
      "RO",     "REQUEST OFFICER",
      "ROB",    "ROBBERY",
      "RR",     "ROAD RAGE",
      "RUN",    "RUNAWAY",
      "SC",     "STATUS CHECK",
      "SCD",    "SCHOOL CROSSING DETAIL",
      "SD",     "SPECIAL DETAIL",
      "SE",     "SYNCOPAL EPISODE",
      "SEI",    "SEIZURE",
      "SF",     "STRUCTURE FIRE",
      "SHF",    "SHOTS FIRED",
      "SHO",    "SHOPLIFTING",
      "SI",     "SMOKE INVESTIGATION",
      "SIG-1",  "Residence or Family Member",
      "SIG-2",  "Meet with...",
      "SIG-3",  "Message or Information",
      "SIG-4",  "Station or Office",
      "SIG-5",  "Eating",
      "SIG-6",  "Call by Phone",
      "SIG-7",  "Officer in Extreme Danger",
      "SIG-8",  "Disregard",
      "SIG-9",  "Rush,Quick Action Desired",
      "SIG-10", "Confidential Information",
      "SL",     "SEVERED LIMB",
      "SMS",    "SMS TEXT TEST",
      "SOA",    "SEXUAL OFFENSE -ADULT",
      "SOJ",    "SEXUAL OFFENSE -JUVENILE",
      "SR",     "SEARCH & RESCUE",
      "SS",     "SUSPISCIOUS SUBJECT",
      "STAB",   "STABBING VICTIM",
      "STAL",   "STALKING",
      "STI",    "STING/BITE",
      "SV",     "SUSPISCIOUS VEHICLE",
      "T0",     "THEFT - OTHER",
      "T4",     "TROUBLE AT YOUR SIG 4",
      "T911",   "TROUBLE AT 911",
      "TB",     "THEFT - BUSINESS",
      "TC",     "TRAFFIC CONTROL",
      "TDEC",   "THEFT BY DECEPTION/COLDCHECKS",
      "TEST",   "TEST CALL",
      "TF",     "TRASH FIRE",
      "TFV",    "THEFT FROM VEH",
      "TH",     "TRAFFIC HAZARD",
      "TI",     "TRAIN INCIDENT",
      "TIP",    "TIP",
      "TR",     "THEFT - RESIDENCE",
      "TRAU",   "TRAUMA",
      "TRE",    "TRESSPASSING",
      "TRG",    "TRAINING",
      "TS",     "TRAFFIC STOP",
      "TT",     "TERRORISTIC THREATENING",
      "TV",     "THEFT - VEHICLE",
      "UFO",    "UFO",
      "UNC",    "UNCONSCIOUS",
      "UNR",    "UNRESPONSIVE",
      "UP",     "UNKNOWN PROBLEM",
      "USP",    "UNSECURED PREMISES",
      "UU",     "UNAUTHORIZED USE",
      "VAN",    "VANDALISM",
      "VF",     "VEHICLE FIRE",
      "VOM",    "VOMITING/DIARRHEA",
      "VT",     "VIOLENT TRAUMA",
      "WAR",    "WARRANT - EXECUTING",
      "WD",     "WEATHER DAMAGE",
      "WF",     "WATERCRAFT/BOATFIRE",
      "WIC",    "WALK-IN COMPLAINT",
      "WR",     "WATER RESCUE",
      "WT",     "WALK THROUGH",
      "WW",     "WEATHER WARNING"

  });

  private static final String[] CITY_LIST = new String[]{
      "BRONSTON",
      "BURNSIDE",
      "ETNA",
      "EUBANK",
      "FAUBUSH",
      "FERGUSON",
      "HAYNES KNOB",
      "INGLE",
      "NANCY",
      "OAK HILL",
      "SCIENCE HILL",
      "SHOPVILLE",
      "SOMERSET",
      "VALLEY OAK",
      "WHITE LILY",
      "WOODSTOCK",
  };

  private static final Properties CITY_CODES = buildCodeTable(new String[]{
     "SOMERSET CO", "SOMERSET",
     "SS",          "SOMERSET",
  });

  private static final Properties MAP_CITY_TABLE = buildCodeTable(new String[] {
      "HAYNES KNOB",    "SOMERSET",
      "WHITE LILY",     "SOMERSET"
  });
}
